// Run with Playwright installed and Microsoft Edge available: node broker.browser.test.cjs
const { chromium } = require('playwright');
const { createServer } = require('node:http');
const { readFile } = require('node:fs/promises');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
  const server=createServer(async(req,res)=>{
    const name=new URL(req.url,'http://localhost').pathname.slice(1);
    if(!['studio.html','sample-furniture.js','studio.js','broker.js'].includes(name)){res.writeHead(404);res.end();return}
    res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8');
    res.end(await readFile(path.join(__dirname,name)));
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser;
  try {
    browser=await chromium.launch({channel:'msedge',headless:true});
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    const page=await context.newPage(),errors=[];
    let allowDecisionReplacement=false,decisionReplacementPrompts=0;
    page.on('pageerror',error=>errors.push(error.message));
    page.on('dialog',dialog=>{if(dialog.type()==='confirm'&&dialog.message().includes('replace the current locally saved project')){decisionReplacementPrompts++;return allowDecisionReplacement?dialog.accept():dialog.dismiss()}return dialog.dismiss()});
    const url=`http://127.0.0.1:${server.address().port}/studio.html`;
    await page.goto(url);
    assert.equal(await page.locator('#useExample b').evaluate(el=>getComputedStyle(el).display),'block');
    assert.equal(await page.locator('#startProject small').evaluate(el=>getComputedStyle(el).display),'block');
    await page.locator('#useExample').click();
    assert.equal(await page.locator('[data-simulation]').count(),3);
    assert.match(await page.locator('#simulationResults').innerText(),/Two columns/);
    await page.locator('#decisionSite').selectOption('spacious');
    await page.locator('#decisionReason').fill('Investigate access and the exact measured plan before any commitment.');
    await page.locator('#decisionCreate').click();
    assert.equal(await page.locator('#decisionModal').isVisible(),true);
    assert.equal(await page.locator('#decisionContent details').count(),3);
    assert.match(await page.locator('#decisionContent').innerText(),/Continue investigating: Large office with fixed core/);
    assert.match(await page.locator('#decisionContent').innerText(),/does not mean it fits, is code-compliant/);
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('office-planner-decision-v1')).sites.length),3);
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.testDecisionURL=value}}));
    await page.locator('#decisionShare').click();
    const decisionURL=await page.evaluate(()=>window.testDecisionURL);
    assert.ok(decisionURL?.includes('#decision='));
    const cleanContext=await browser.newContext({viewport:{width:1100,height:850}}),decisionClient=await cleanContext.newPage();
    await decisionClient.goto(decisionURL);
    assert.equal(await decisionClient.locator('#decisionModal').isVisible(),true);
    assert.equal(await decisionClient.locator('#decisionClose').isVisible(),false);
    assert.equal(await decisionClient.locator('#decisionContinue').isVisible(),false);
    assert.equal(await decisionClient.locator('.app').isVisible(),false);
    assert.match(await decisionClient.locator('#decisionContent').innerText(),/Investigate access and the exact measured plan/);
    await cleanContext.close();
    await page.locator('#decisionClose').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true);
    const savedPage=await context.newPage();
    await savedPage.goto(url);
    assert.equal(await savedPage.locator('#decisionOpen').isVisible(),true);
    assert.equal(await savedPage.locator('#decisionWelcome').isVisible(),true);
    await savedPage.locator('#decisionWelcome').click();
    assert.match(await savedPage.locator('#decisionContent').innerText(),/40 requested workstations/);
    assert.match(await savedPage.locator('#decisionContent').innerText(),/Investigate access and the exact measured plan/);
    await savedPage.locator('#decisionClose').click();
    assert.equal(await savedPage.locator('#welcomeModal').isVisible(),true);
    await savedPage.close();
    await page.locator('#simPeople').fill('80');
    await page.locator('#simulationRefresh').click();
    assert.equal(await page.locator('#simulationResults .fit-status').count(),3);
    assert.match(await page.locator('#simulationResults').innerText(),/Best concept:/);
    assert.match(await page.locator('#simulationResults').innerText(),/hard requirement gap/);
    assert.match(await page.locator('#simulationResults').innerText(),/18\.0 × 12\.0 m/);
    await page.locator('#simPeople').fill('40');
    await page.locator('[data-simulation=balanced]').click();
    assert.equal(await page.locator('#catalog [data-kind]').count(),12);
    assert.equal(await page.evaluate(()=>SAMPLE_FURNITURE.every(item=>item.sku.startsWith('DEMO-')&&item.modelParts.length>0&&item.width>0&&item.depth>0&&item.height>0)),true);
    assert.equal(await page.evaluate(()=>P.furniture.every(item=>item.sku&&item.catalogVersion===SAMPLE_CATALOG_VERSION&&item.priceStatus==='illustrative')),true);
    assert.match(await page.locator('#bom').innerText(),/DEMO-/);
    await page.locator('[data-view="3d"]').click();
    assert.equal(await page.evaluate(()=>view),'3d');
    await page.locator('[data-view="2d"]').click();
    assert.equal(await page.evaluate(()=>P.source.kind),'simulated');
    assert.equal(await page.evaluate(()=>P.source.fixtureId),'balanced');
    assert.deepEqual(await page.evaluate(()=>[P.w,P.h]),[18000,12000]);
    assert.equal(await page.evaluate(()=>P.objects.filter(o=>o.type==='column').length),2);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.match(await page.locator('#projectTitle').innerText(),/Mid-size office with columns/);
    await page.locator('#newProject').click();
    await page.locator('#startProject').click();
    assert.equal(await page.locator('#naturalBrief').isVisible(),true);
    let extractionCalls=0;
    await page.route('**/api/extract-brief',route=>{extractionCalls++;return route.abort()});
    assert.equal(await page.locator('#naturalBriefPin').isVisible(),false);
    assert.match(await page.locator('#naturalBrief').innerText(),/Mock requirement extraction/i);
    await page.locator('#naturalBriefText').fill('Forty staff need office space and meeting rooms.');
    await page.locator('#naturalBriefExtract').click();
    await page.locator('#brokerForm').waitFor({state:'visible'});
    assert.equal(await page.locator('#brokerForm').isVisible(),true);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),true);
    await page.locator('#reviewRefine').click();
    await page.locator('#naturalBriefText').fill('Client needs 40 workstations, 3 private offices, two 6-person meeting rooms, 2 phone booths and a pantry at Los Angeles · Test suite.');
    await page.locator('#naturalBriefExtract').click();
    await page.locator('#brokerForm').waitFor({state:'visible'});
    assert.match(await page.locator('#extractedSummary').innerText(),/40 workstations/);
    assert.match(await page.locator('#extractedAnswers').innerText(),/Not mentioned/);
    await page.locator('#extractedAnswers [data-answer="reception"]').selectOption('not-needed');
    assert.equal(extractionCalls,0);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),false);
    await page.locator('#brokerForm button[type=submit], #brokerForm button.primary').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true);
    assert.match(await page.locator('#simulationBriefSummary').innerText(),/40 workstations/);
    assert.equal(await page.locator('[data-simulation]').count(),3);
    await page.locator('#simulationManual').click();
    await page.locator('#siteWidth').fill('20');
    await page.locator('#siteHeight').fill('15');
    await page.locator('#brokerLengthUnit').selectOption('ft');
    assert.ok(Math.abs(Number(await page.locator('#siteWidth').inputValue())-65.6168)<.001);
    await page.locator('#brokerLengthUnit').selectOption('m');
    await page.locator('#createProjectSubmit').click();
    assert.equal(await page.evaluate(()=>P.w),20000);
    assert.equal(await page.evaluate(()=>P.broker.people),40);
    assert.equal(await page.evaluate(()=>P.broker.extractionMode),'mock');
    assert.equal(await page.evaluate(()=>P.broker.intakeAnswers.reception),'not-needed');
    assert.equal(await page.evaluate(()=>P.broker.intakeAnswers.diningSeats),'unknown');
    assert.equal(await page.evaluate(()=>P.broker.intakeConfirmed),true);
    assert.equal(await page.evaluate(()=>JSON.stringify(P).includes('Client needs 40 workstations')),false);
    assert.equal(await page.locator('#briefMeeting').getAttribute('readonly'),'');
    assert.match(await page.locator('#quickAssessment').innerText(),/Site review in progress/);
    assert.doesNotMatch(await page.locator('#quickAssessment').innerText(),/Add a property to begin/);
    // Place entrance and exit through canvas UI using the current displayed transform.
    const canvas=await page.locator('#canvas').boundingBox();
    const positions=await page.evaluate(()=>({left:screen(0,P.h/2),right:screen(P.w,P.h/2)}));
    await page.locator('[data-setup-tool=door]').click();
    assert.equal(await page.locator('[data-setup-tool=door]').getAttribute('aria-pressed'),'true');
    assert.equal(await page.locator('#hint').isVisible(),true);
    assert.match(await page.locator('#hint').innerText(),/click the correct exterior wall/i);
    await page.mouse.click(canvas.x+positions.left[0],canvas.y+positions.left[1]);
    assert.equal(await page.locator('[data-setup-tool=exit]').getAttribute('aria-pressed'),'true');
    await page.mouse.click(canvas.x+positions.right[0],canvas.y+positions.right[1]);
    assert.match(await page.locator('#quickAssessment').innerText(),/Site ready for confirmation/);
    await page.locator('#openBrief').click();
    const briefSummary=await page.locator('#briefSiteSummary').innerText();
    assert.equal((briefSummary.match(/20\.0 × 15\.0 m/g)||[]).length,1);
    assert.match(await page.locator('#briefCapabilityNote').innerText(),/shared-use zones/);
    assert.match(await page.locator('#briefCapabilityNote').innerText(),/professional review/);
    await page.locator('#briefForm button.primary').click();
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Private offices/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Unconfirmed · Dining seats/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Confirmed not needed: Reception/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Placed · concept|Shortfall/);
    await page.locator('#brokerNext').selectOption('Ask a designer to verify rooms and access');
    await page.locator('#brokerReportClose').click();
    assert.equal(await page.locator('.left').isVisible(),false);
    await page.locator('#advancedToggle').click();
    assert.equal(await page.locator('.left').isVisible(),true);
    await page.locator('#briefMode').selectOption('private');
    await page.reload();
    assert.equal(await page.locator('#briefMode').inputValue(),'private');
    assert.equal(await page.evaluate(()=>P.draftsStale),true);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Assessment out of date/);
    const blockedShare=page.waitForEvent('dialog');
    await page.locator('#brokerShare').click();
    assert.match((await blockedShare).message(),/not current/);
    await page.locator('#brokerReportClose').click();
    await page.locator('#quickUpdatePlans').click();
    await page.locator('#advancedToggle').click();
    // Export and re-import the actual downloaded project.
    const downloadPromise=page.waitForEvent('download');
    await page.evaluate(()=>document.querySelector('#exportBtn').click());
    const download=await downloadPromise;
    await page.locator('#fileInput').setInputFiles(await download.path());
    await page.waitForTimeout(150);
    assert.equal(await page.evaluate(()=>P.broker.next),'Ask a designer to verify rooms and access');
    // Capture the real share handler without touching the system clipboard.
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.testSharedURL=value}}));
    await page.locator('#shareBtn').click();
    const sharedURL=await page.evaluate(()=>window.testSharedURL);
    assert.ok(sharedURL?.includes('#project='));
    const client=await context.newPage();
    client.on('pageerror',error=>errors.push(error.message));
    await client.goto(sharedURL);
    assert.equal(await client.locator('#brokerReport').isVisible(),true);
    assert.equal(await client.locator('#brokerNext').isDisabled(),true);
    await client.locator('#brokerReportClose').click();
    assert.equal(await client.locator('#brokerEdit').isDisabled(),true);
    assert.equal(await client.locator('#undoBtn').isDisabled(),true);
    await client.setViewportSize({width:390,height:844});
    await client.locator('#brokerResult').click();
    assert.equal(await client.locator('#brokerReport').isVisible(),true);
    await page.locator('#newProject').click();
    await page.locator('#useExample').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true);
    await page.locator('#simPeople').fill('100');
    await page.locator('[data-simulation=compact]').click();
    assert.deepEqual(await page.evaluate(()=>[P.w,P.h,P.objects.filter(o=>o.type==='column').length]),[12000,9000,0]);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.broker.people),100);
    assert.match(await page.locator('#quickAssessment').innerText(),/Not a fit yet/);
    await page.locator('#newProject').click();
    await page.locator('#useExample').click();
    await page.locator('#simPeople').fill('16');
    await page.locator('[data-simulation=spacious]').click();
    assert.deepEqual(await page.evaluate(()=>[P.w,P.h,P.objects.filter(o=>o.type==='exit').length]),[24000,16000,2]);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    await page.locator('#openBrief').click();
    await page.locator('#editDetailedNeeds').click();
    await page.locator('#broker-assignedStaff').fill('48');
    await page.locator('#broker-peakOnsite').fill('30');
    await page.locator('#broker-workstationPolicy').selectOption('shared');
    await page.locator('#broker-sourceUrl').fill('https://example.org/public-brief');
    await page.locator('#addExtraSpace').click();
    await page.locator('#extraSpaceRows [data-extra="kind"]').selectOption('meeting');
    await page.locator('#extraSpaceRows [data-extra="seats"]').fill('20');
    await page.locator('#addRelation').click();
    await page.locator('#relationRows [data-relation="from"]').fill('coffee bar');
    await page.locator('#relationRows [data-relation="rule"]').selectOption('away');
    await page.locator('#relationRows [data-relation="to"]').fill('workstations');
    await page.locator('#addDepartment').click();
    await page.locator('#departmentRows [data-department="name"]').fill('Sales');
    await page.locator('#departmentRows [data-department="assigned"]').fill('8');
    await page.locator('#departmentRows [data-department="peakOnsite"]').fill('5');
    await page.locator('#departmentRows [data-department="activity"]').selectOption('calls');
    await page.locator('#addTradeoff').click();
    await page.locator('#tradeoffRows [data-tradeoff="target"]').selectOption('meeting');
    await page.locator('#tradeoffRows [data-tradeoff="action"]').selectOption('reduce');
    await page.locator('#tradeoffRows [data-tradeoff="minimum"]').fill('1');
    await page.locator('#brokerForm button.primary').click();
    assert.equal(await page.evaluate(()=>P.broker.requirements.version),3);
    assert.equal(await page.evaluate(()=>P.broker.requirements.staffing.peakOnsite),30);
    assert.equal(await page.evaluate(()=>P.broker.requirements.spaces.find(s=>s.origin==='extra').seats),20);
    assert.equal(await page.evaluate(()=>P.broker.requirements.relations.length),1);
    assert.equal(await page.evaluate(()=>P.broker.requirements.departments[0].activity),'calls');
    assert.equal(await page.evaluate(()=>P.broker.requirements.tradeoffs[0].minimum),1);
    assert.equal(await page.evaluate(()=>P.draftsStale),true);
    await page.locator('#quickUpdatePlans').click();
    assert.match(await page.locator('#quickAssessment').innerText(),/Not fully assessed/);
    assert.match(await page.locator('#comparisonGrid').innerText(),/additional requirement\(s\) not assessed/);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Not assessed/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Department · Sales/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Tradeoff · Meeting rooms/);
    assert.match(await page.locator('#matchingSuggestions').innerText(),/Sales · Calls \/ video meetings/);
    assert.match(await page.locator('#matchingSuggestions').innerText(),/DEMO-BOOTH-1/);
    assert.match(await page.locator('#matchingSuggestions').innerText(),/Candidate only/);
    await page.locator('#brokerReportClose').click();
    await page.reload();
    assert.equal(await page.evaluate(()=>P.broker.requirements.staffing.policy),'shared');
    assert.equal(await page.evaluate(()=>P.broker.requirements.source.url),'https://example.org/public-brief');
    await page.locator('#openBrief').click();
    await page.locator('#editDetailedNeeds').click();
    assert.equal(await page.locator('#extraSpaceRows [data-extra-id]').count(),1);
    assert.equal(await page.locator('#relationRows [data-relation-id]').count(),1);
    assert.equal(await page.locator('#departmentRows [data-department-id]').count(),1);
    assert.equal(await page.locator('#tradeoffRows [data-tradeoff-id]').count(),1);
    assert.equal(await page.locator('#broker-peakOnsite').inputValue(),'30');
    await page.locator('#brokerCancel').click();
    await page.locator('#newProject').click();
    await page.locator('#startProject').click();
    await page.locator('#naturalBriefText').fill('Client needs 24 workstations, two 6-person meeting rooms, 3 private offices, 2 phone booths and one training room.');
    await page.locator('#naturalBriefExtract').click();
    await page.locator('#brokerForm button.primary').click();
    assert.equal(await page.locator('#simulationQuickFields').isVisible(),false);
    assert.match(await page.locator('#simulationBriefSummary').innerText(),/1 additional space types/);
    const compactPreview=await page.evaluate(()=>simulationPreviews(simulationBrief())[0]);
    await page.locator('[data-simulation="compact"]').click();
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    assert.equal(await page.evaluate(()=>P.broker.meetingRooms),2);
    assert.equal(await page.evaluate(()=>P.broker.extraSpaces[0].kind),'training');
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.drafts[0].label),compactPreview.best);
    assert.equal(await page.evaluate(()=>brokerAssessment(P).rows.filter(row=>row.status==='Shortfall').length),compactPreview.gaps.length);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Training room.*Not assessed/s);
    await page.locator('#brokerTrySpace').click();
    assert.match(await page.locator('#simulationBriefSummary').innerText(),/24 workstations/);
    assert.equal(await page.locator('[data-simulation]').count(),3);
    const spaciousPreview=await page.evaluate(()=>simulationPreviews(simulationBrief())[2]);
    await page.locator('[data-simulation="spacious"]').click();
    assert.equal(await page.evaluate(()=>P.source.fixtureId),'spacious');
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    assert.equal(await page.evaluate(()=>P.broker.extraSpaces[0].kind),'training');
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.drafts[0].label),spaciousPreview.best);
    assert.equal(await page.evaluate(()=>brokerAssessment(P).rows.filter(row=>row.status==='Shortfall').length),spaciousPreview.gaps.length);
    await page.locator('#decisionOpen').click();
    assert.match(await page.locator('#decisionContent').innerText(),/40 requested workstations/);
    await page.evaluate(()=>{savedDecision.sites.find(site=>site.fixtureId==='spacious').fixtureVersion=99});
    await page.locator('#decisionContinue').click();
    assert.match(await page.locator('#decisionContinueError').innerText(),/sample space has changed/);
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    await page.evaluate(()=>{savedDecision.sites.find(site=>site.fixtureId==='spacious').fixtureVersion=1;savedDecision.plannerVersion='old-layout-version'});
    await page.locator('#decisionContinue').click();
    assert.match(await page.locator('#decisionContinueError').innerText(),/layout engine has changed/);
    await page.evaluate(()=>{savedDecision.plannerVersion='mvp-layout-v1';savedDecision.brief.requirements.version=2});
    await page.locator('#decisionContinue').click();
    assert.match(await page.locator('#decisionContinueError').innerText(),/customer needs format has changed/);
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    await page.evaluate(()=>{savedDecision.brief.requirements.version=3});
    await page.locator('#decisionContinue').click();
    assert.equal(await page.locator('#decisionModal').isVisible(),true);
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    allowDecisionReplacement=true;
    await page.locator('#decisionContinue').click();
    assert.equal(decisionReplacementPrompts,2);
    assert.equal(await page.locator('#decisionModal').isVisible(),false);
    assert.equal(await page.evaluate(()=>P.source.fixtureId),'spacious');
    assert.equal(await page.evaluate(()=>P.source.fixtureVersion),1);
    assert.equal(await page.evaluate(()=>P.broker.people),40);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.draftsStale),false);
    await page.locator('#decisionOpen').click();
    assert.match(await page.locator('#decisionContent').innerText(),/40 requested workstations/);
    assert.match(await page.locator('#decisionContent').innerText(),/Investigate access and the exact measured plan/);
    assert.deepEqual(errors,[]);
    console.log('PASS: intake, generation, assessment, reload, export/import, share and saved-decision continuation');
  } finally {if(browser)await browser.close();await new Promise(resolve=>server.close(resolve))}
})().catch(error=>{console.error(error);process.exitCode=1});
