// Run with Playwright installed and Microsoft Edge available: node broker.browser.test.cjs
const { chromium } = require('playwright');
const { createServer } = require('node:http');
const { readFile } = require('node:fs/promises');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
  const server=createServer(async(req,res)=>{
    const name=new URL(req.url,'http://localhost').pathname.slice(1);
    if(!['studio.html','sample-furniture.js','studio.js','broker.js','zone-assist.js'].includes(name)){res.writeHead(404);res.end();return}
    res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8');
    res.end(await readFile(path.join(__dirname,name)));
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser;
  try {
    browser=await chromium.launch({channel:'msedge',headless:true});
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    const page=await context.newPage(),errors=[];
    let allowDecisionReplacement=false,decisionReplacementPrompts=0;
    page.on('pageerror',error=>errors.push(error.message));
    page.on('dialog',dialog=>{if(dialog.type()==='confirm'&&dialog.message().includes('replace the current locally saved project')){decisionReplacementPrompts++;return allowDecisionReplacement?dialog.accept():dialog.dismiss()}return dialog.dismiss()});
    const url=`http://127.0.0.1:${server.address().port}/studio.html`;
    await page.goto(url);
    assert.match(await page.locator('#welcomeModal').innerText(),/1\. Describe.*2\. Compare.*3\. Open/s);
    assert.match(await page.locator('#startProject').innerText(),/Start with client needs/);
    assert.equal(await page.locator('#startProject').evaluate(el=>el.classList.contains('primary')),true);
    assert.equal(await page.locator('#useExample b').evaluate(el=>getComputedStyle(el).display),'block');
    assert.equal(await page.locator('#startProject small').evaluate(el=>getComputedStyle(el).display),'block');
    await page.setViewportSize({width:1440,height:900});
    await page.locator('#useExample').click();
    assert.match(await page.locator('#simulationModal').innerText(),/Step 2 of 3 · Compare spaces/i);
    assert.match(await page.locator('#simulationResults [data-simulation]').first().innerText(),/View 3 layouts in this space/);
    assert.equal(await page.locator('[data-simulation]').count(),3);
    assert.equal(await page.locator('#simulationResults svg').count(),3);
    assert.equal(await page.locator('#simulationResults details[open]').count(),0,'sample-layout evidence should start folded');
    assert.equal(await page.locator('#simulationNeedsDetails').evaluate(el=>el.open),false,'example needs start folded on desktop');
    assert.equal(await page.locator('#decisionComposerDetails').evaluate(el=>el.open),false,'optional comparison report starts folded on desktop');
    await page.locator('#decisionComposerDetails summary').click();
    assert.equal(await page.locator('#decisionCreate').isVisible(),true);
    await page.setViewportSize({width:1440,height:1000});
    assert.match(await page.locator('#simulationResults').innerText(),/Two columns/);
    await page.locator('#decisionSite').selectOption('spacious');
    await page.locator('#decisionReason').fill('Investigate access and the exact measured plan before any commitment.');
    await page.locator('#decisionCreate').click();
    assert.equal(await page.locator('#decisionModal').isVisible(),true);
    assert.match(await page.locator('#decisionContent').innerText(),/Step 2 complete.*three layouts for that same space/s);
    assert.match(await page.locator('#decisionContinue').innerText(),/View 3 layouts for selected space/);
    assert.equal(await page.locator('#decisionContent details').count(),3);
    assert.match(await page.locator('#decisionContent').innerText(),/Continue investigating: Large office with fixed core/);
    assert.match(await page.locator('#decisionContent').innerText(),/does not mean it fits, is code-compliant/);
    assert.match(await page.locator('#decisionContent').innerText(),/concept placements to verify/);
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('office-planner-decision-v1')).sites.length),3);
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.testDecisionURL=value}}));
    await page.locator('#decisionShare').click();
    const decisionURL=await page.evaluate(()=>window.testDecisionURL);
    assert.ok(decisionURL?.includes('#decision='));
    const cleanContext=await browser.newContext({viewport:{width:1100,height:850}}),decisionClient=await cleanContext.newPage();
    await decisionClient.goto(decisionURL);
    assert.equal(await decisionClient.locator('#decisionModal').isVisible(),true);
    assert.equal(await decisionClient.locator('#decisionClose').isVisible(),false);
    assert.equal(await decisionClient.locator('#decisionContinue').isVisible(),false);
    assert.equal(await decisionClient.locator('.app').isVisible(),false);
    assert.match(await decisionClient.locator('#decisionContent').innerText(),/Investigate access and the exact measured plan/);
    await cleanContext.close();
    const mobileContext=await browser.newContext({viewport:{width:390,height:844}}),mobilePage=await mobileContext.newPage();
    await mobilePage.goto(url);
    await mobilePage.locator('#useExample').click();
    assert.equal(await mobilePage.locator('[data-simulation]').count(),3);
    assert.equal(await mobilePage.locator('#simulationNeedsDetails').evaluate(el=>el.open),false,'phone starts with editable needs folded to a short summary');
    assert.ok((await mobilePage.locator('#simulationResults .simulation-card').first().boundingBox()).y<350,'first sample should appear near the top on a phone');
    await mobilePage.locator('#simulationNeedsDetails summary').click();
    assert.equal(await mobilePage.locator('#simPeople').isVisible(),true,'customer can reopen the needs form');
    await mobilePage.locator('#simulationNeedsDetails summary').click();
    assert.equal(await mobilePage.locator('#simulationModal .dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
    assert.equal(await mobilePage.locator('#decisionComposerDetails').evaluate(el=>el.open),false,'optional shortlist form starts folded on a phone');
    await mobilePage.locator('#decisionComposerDetails summary').click();
    assert.notEqual(await mobilePage.locator('#decisionComposerDetails summary').evaluate(el=>getComputedStyle(el).display),'none','open shortlist form remains closable on a phone');
    await mobilePage.locator('#decisionComposerDetails summary').click();
    assert.equal(await mobilePage.locator('#decisionComposerDetails').evaluate(el=>el.open),false,'optional shortlist form can be closed again');
    await mobilePage.locator('#decisionComposerDetails summary').click();
    await mobilePage.locator('#decisionSite').selectOption('compact');
    await mobilePage.locator('#decisionReason').fill('Check the measured plan first.');
    await mobilePage.locator('#decisionCreate').click();
    assert.equal(await mobilePage.locator('#decisionModal').isVisible(),true);
    const mobileReview=await mobileContext.newPage();
    await mobileReview.goto(url);
    await mobileReview.locator('#startProject').click();
    await mobileReview.locator('#naturalBriefText').fill('We need 24 workstations and two 6-person meeting rooms for our office team.');
    await mobileReview.locator('#naturalBriefExtract').click();
    assert.equal(await mobileReview.locator('#extractedAnswers .review-needs').evaluate(el=>el.open),false,'phone review starts with a short need summary');
    assert.equal(await mobileReview.locator('#extractedAnswers .review-suggestions').evaluate(el=>el.open),false,'optional areas start folded on a phone');
    await mobileReview.locator('#extractedAnswers .review-needs summary').click();
    assert.equal(await mobileReview.locator('#extractedAnswers [data-answer="offices"]').isVisible(),true,'all recorded needs remain available to edit');
    await mobileReview.close();
    const mobileMissing=await mobileContext.newPage();
    await mobileMissing.goto(url);
    await mobileMissing.locator('#startProject').click();
    await mobileMissing.locator('#naturalBriefText').fill('We need meeting rooms.');
    await mobileMissing.locator('#naturalBriefExtract').click();
    assert.equal(await mobileMissing.locator('#extractedAnswers .review-needs').evaluate(el=>el.open),true,'missing required numbers should open the editable needs table');
    assert.equal(await mobileMissing.locator('#brokerForm button.primary').isDisabled(),true);
    await mobileMissing.close();
    await mobileContext.close();
    const reviewedPage=await context.newPage();
    await reviewedPage.goto(url);
    await reviewedPage.locator('#startProject').click();
    await reviewedPage.locator('#naturalBriefText').fill('Client needs 40 workstations, two 6-person meeting rooms, 3 private offices, 2 phone booths, no dining seats and a pantry.');
    await reviewedPage.locator('#naturalBriefExtract').click();
    await reviewedPage.setViewportSize({width:1440,height:900});
    assert.equal(await reviewedPage.locator('#extractedAnswers .review-suggestions').evaluate(el=>el.open),false,'secondary suggestions start folded on desktop');
    assert.ok((await reviewedPage.locator('#brokerForm button.primary').boundingBox()).y<860,'desktop review action stays in the first viewport');
    await reviewedPage.setViewportSize({width:1440,height:1000});
    assert.equal(await reviewedPage.locator('#extractedAnswers [data-answer="people"]').inputValue(),'requested','recognized needs have an editable state');
    assert.equal(await reviewedPage.locator('#extractedAnswers [data-answer-count="people"]').inputValue(),'40','recognized counts are prefilled');
    await reviewedPage.locator('#extractedAnswers [data-answer-count="people"]').fill('32');
    await reviewedPage.locator('#extractedAnswers [data-answer-count="meetingRooms"]').fill('2');
    await reviewedPage.locator('#extractedAnswers [data-answer-seats="roomSeats"]').fill('8');
    await reviewedPage.locator('#extractedAnswers [data-answer="offices"]').selectOption('not-needed');
    await reviewedPage.locator('#extractedAnswers [data-answer="phones"]').selectOption('uncertain');
    assert.equal(await reviewedPage.locator('#extractedAnswers [data-answer="diningSeats"]').inputValue(),'not-needed');
    assert.equal(await reviewedPage.locator('#extractedAnswers [data-answer="loungeSeats"]').inputValue(),'unknown');
    await reviewedPage.locator('#brokerForm button.primary').click();
    assert.deepEqual(await reviewedPage.evaluate(()=>({people:simulationDraft.people,roomSeats:simulationDraft.roomSeats,offices:simulationDraft.offices,phones:simulationDraft.phones,officeState:simulationDraft.intakeAnswers.offices,phoneState:simulationDraft.intakeAnswers.phones,diningState:simulationDraft.intakeAnswers.diningSeats,loungeState:simulationDraft.intakeAnswers.loungeSeats})),{people:32,roomSeats:8,offices:0,phones:0,officeState:'not-needed',phoneState:'uncertain',diningState:'not-needed',loungeState:'unknown'});
    assert.equal(await reviewedPage.locator('#simulationConfirmed').isVisible(),true);
    assert.equal(await reviewedPage.locator('#simulationBriefSummary').isVisible(),true);
    assert.equal(await reviewedPage.locator('#simulationNeedsDetails').isVisible(),false,'confirmed needs do not show the four-field example form');
    await reviewedPage.locator('#simulationEditNeeds').click();
    assert.equal(await reviewedPage.locator('#brokerForm').evaluate(el=>el.classList.contains('extracted-review')),false,'full needs editor opens directly');
    assert.equal(await reviewedPage.locator('#addExtraSpace').isVisible(),true);
    await reviewedPage.locator('#broker-offices').fill('2');
    assert.equal(await reviewedPage.locator('#answerEdit [data-answer="offices"]').inputValue(),'requested');
    await reviewedPage.locator('#brokerForm button.primary').click();
    assert.equal(await reviewedPage.evaluate(()=>simulationDraft.offices),2);
    assert.equal(await reviewedPage.evaluate(()=>simulationDraft.intakeAnswers.offices),'requested');
    await reviewedPage.close();
    await page.locator('#decisionClose').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true);
    const savedPage=await context.newPage();
    await savedPage.goto(url);
    assert.equal(await savedPage.locator('#decisionOpen').isVisible(),false,'background header stays hidden while welcome is open');
    assert.equal(await savedPage.locator('#decisionWelcome').isVisible(),true);
    await savedPage.locator('#decisionWelcome').click();
    assert.match(await savedPage.locator('#decisionContent').innerText(),/40 requested workstations/);
    assert.match(await savedPage.locator('#decisionContent').innerText(),/Investigate access and the exact measured plan/);
    await savedPage.locator('#decisionClose').click();
    assert.equal(await savedPage.locator('#welcomeModal').isVisible(),true);
    await savedPage.close();
    await page.locator('#simulationNeedsDetails summary').click();
    await page.locator('#simPeople').fill('80');
    await page.locator('#simulationRefresh').click();
    assert.equal(await page.locator('#simulationResults .fit-status').count(),3);
    assert.match(await page.locator('#simulationResults').innerText(),/hard requirement gap/);
    await page.locator('#simulationResults .simulation-card').nth(1).locator('summary').click();
    assert.match(await page.locator('#simulationResults .simulation-card').nth(1).locator('details').innerText(),/Best concept:/);
    assert.match(await page.locator('#simulationResults .simulation-card').nth(1).locator('details').innerText(),/18\.0 × 12\.0 m/);
    const sampleChecks=await page.evaluate(()=>simulationPreviews(simulationBrief())[1].rows.filter(row=>['Shortfall','Not assessed','Needs review'].includes(row.status)).map(row=>row.name));
    const sampleDetails=await page.locator('#simulationResults .simulation-card').nth(1).locator('details').innerText();
    for(const name of sampleChecks)assert.ok(sampleDetails.includes(name),`expanded sample should list ${name}`);
    await page.locator('#simPeople').fill('40');
    await page.locator('[data-simulation=balanced]').click();
    assert.match(await page.locator('#comparisonPanel').innerText(),/Step 3 of 3 · Compare layouts A \/ B \/ C/);
    assert.match(await page.locator('#projectTitle').innerText(),/Mid-size office with columns/);
    assert.equal(await page.locator('#catalog [data-kind]').count(),14);
    assert.equal(await page.evaluate(()=>SAMPLE_FURNITURE.every(item=>item.sku.startsWith('DEMO-')&&item.modelParts.length>0&&item.width>0&&item.depth>0&&item.height>0)),true);
    assert.equal(await page.evaluate(()=>P.furniture.every(item=>item.sku&&item.catalogVersion===SAMPLE_CATALOG_VERSION&&item.priceStatus==='illustrative')),true);
    assert.match(await page.locator('#bom').innerText(),/DEMO-/);
    await page.locator('[data-view="3d"]').click();
    assert.equal(await page.evaluate(()=>view),'3d');
    await page.locator('[data-view="2d"]').click();
    assert.equal(await page.evaluate(()=>P.source.kind),'simulated');
    assert.equal(await page.evaluate(()=>P.source.fixtureId),'balanced');
    assert.deepEqual(await page.evaluate(()=>[P.w,P.h]),[18000,12000]);
    assert.equal(await page.locator('.plans-panel').isVisible(),false);
    assert.equal(await page.evaluate(()=>P.objects.filter(o=>o.type==='column').length),2);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.match(await page.locator('#projectTitle').innerText(),/Mid-size office with columns/);
    assert.match(await page.locator('#quickAssessment small').innerText(),/CURRENT SELECTED PLAN/);
    assert.equal(await page.locator('#quickViewResult').count(),0,'top result link is the single report entry');
    await page.locator('#newProject').click();
    await page.locator('#startProject').click();
    assert.equal(await page.locator('#naturalBrief').isVisible(),true);
    let extractionCalls=0;
    await page.route('**/api/extract-brief',route=>{extractionCalls++;return route.abort()});
    assert.equal(await page.locator('#naturalBriefPin').isVisible(),false);
    assert.match(await page.locator('#naturalBrief').innerText(),/Mock requirement extraction/i);
    await page.locator('#naturalBriefText').fill('Forty staff need office space and meeting rooms.');
    await page.locator('#naturalBriefExtract').click();
    await page.locator('#brokerForm').waitFor({state:'visible'});
    assert.equal(await page.locator('#brokerForm').isVisible(),true);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),true);
    await page.locator('#extractedAnswers [data-answer="people"]').selectOption('requested');
    await page.locator('#extractedAnswers [data-answer-count="people"]').fill('24');
    await page.locator('#extractedAnswers [data-answer="meetingRooms"]').selectOption('requested');
    await page.locator('#extractedAnswers [data-answer-count="meetingRooms"]').fill('2');
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),true,'meeting capacity cannot be guessed');
    await page.locator('#extractedAnswers [data-answer-seats="roomSeats"]').fill('6');
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),false);
    await page.locator('#reviewRefine').click();
    await page.locator('#naturalBriefText').fill('Client needs 40 workstations, 3 private offices, two 6-person meeting rooms, 2 phone booths and a pantry at Los Angeles · Test suite.');
    await page.locator('#naturalBriefExtract').click();
    await page.locator('#brokerForm').waitFor({state:'visible'});
    assert.match(await page.locator('#extractedSummary').innerText(),/40 workstations/);
    assert.match(await page.locator('#extractedAnswers').innerText(),/Not mentioned/);
    await page.locator('#extractedAnswers .review-suggestions summary').click();
    await page.locator('#extractedAnswers [data-suggested-zone="reception"]').selectOption('removed');
    assert.equal(extractionCalls,0);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),false);
    await page.locator('#brokerForm button[type=submit], #brokerForm button.primary').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true);
    assert.match(await page.locator('#simulationBriefSummary').innerText(),/40 workstations/);
    assert.equal(await page.locator('[data-simulation]').count(),3);
    await page.locator('#simulationManual').click();
    await page.locator('#siteWidth').fill('20');
    await page.locator('#siteHeight').fill('15');
    await page.locator('#brokerLengthUnit').selectOption('ft');
    assert.ok(Math.abs(Number(await page.locator('#siteWidth').inputValue())-65.6168)<.001);
    await page.locator('#brokerLengthUnit').selectOption('m');
    await page.locator('#createProjectSubmit').click();
    assert.equal(await page.evaluate(()=>P.w),20000);
    assert.equal(await page.evaluate(()=>P.broker.people),40);
    assert.equal(await page.evaluate(()=>P.broker.extractionMode),'mock');
    assert.equal(await page.evaluate(()=>P.broker.intakeAnswers.reception),'not-needed');
    assert.equal(await page.evaluate(()=>P.broker.intakeAnswers.diningSeats),'unknown');
    assert.equal(await page.evaluate(()=>P.broker.intakeConfirmed),true);
    assert.equal(await page.evaluate(()=>JSON.stringify(P).includes('Client needs 40 workstations')),false);
    assert.equal(await page.locator('#briefMeeting').getAttribute('readonly'),'');
    assert.match(await page.locator('#quickAssessment').innerText(),/Site review in progress/);
    assert.equal(await page.locator('#advancedToggle').isVisible(),false,'plan editor stays hidden before layouts exist');
    assert.doesNotMatch(await page.locator('#quickAssessment').innerText(),/Add a property to begin/);
    // Place entrance and exit through canvas UI using the current displayed transform.
    const canvas=await page.locator('#canvas').boundingBox();
    const positions=await page.evaluate(()=>({left:screen(0,P.h/2),right:screen(P.w,P.h/2)}));
    await page.locator('[data-setup-tool=door]').click();
    assert.equal(await page.locator('[data-setup-tool=door]').getAttribute('aria-pressed'),'true');
    assert.equal(await page.locator('#hint').isVisible(),true);
    assert.match(await page.locator('#hint').innerText(),/click the correct exterior wall/i);
    await page.mouse.click(canvas.x+positions.left[0],canvas.y+positions.left[1]);
    assert.equal(await page.locator('[data-setup-tool=exit]').getAttribute('aria-pressed'),'true');
    await page.mouse.click(canvas.x+positions.right[0],canvas.y+positions.right[1]);
    assert.match(await page.locator('#quickAssessment').innerText(),/Site ready for confirmation/);
    await page.locator('#openBrief').click();
    const briefSummary=await page.locator('#briefSiteSummary').innerText();
    assert.equal((briefSummary.match(/20\.0 × 15\.0 m/g)||[]).length,1);
    assert.match(await page.locator('#briefCapabilityNote').innerText(),/shared-use zones/);
    assert.match(await page.locator('#briefCapabilityNote').innerText(),/professional review/);
    await page.locator('#briefForm button.primary').click();
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.locator('#advancedToggle').isVisible(),true);
    assert.match(await page.locator('#advancedToggle').innerText(),/Edit current plan layout/);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Private offices/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Unconfirmed · Dining seats/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Confirmed not needed: Reception/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Placed · concept|Shortfall/);
    await page.locator('#brokerNext').selectOption('Ask a designer to verify rooms and access');
    await page.locator('#brokerReportClose').click();
    assert.equal(await page.locator('.left').isVisible(),false);
    await page.locator('#advancedToggle').click();
    assert.equal(await page.locator('.left').isVisible(),true);
    await page.locator('#briefMode').selectOption('private');
    await page.reload();
    assert.equal(await page.locator('#briefMode').inputValue(),'private');
    assert.equal(await page.evaluate(()=>P.draftsStale),true);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Assessment out of date/);
    const blockedShare=page.waitForEvent('dialog');
    await page.locator('#brokerShare').click();
    assert.match((await blockedShare).message(),/not current/);
    await page.locator('#brokerReportClose').click();
    await page.locator('#quickUpdatePlans').click();
    await page.locator('#advancedToggle').click();
    // Export and re-import the actual downloaded project.
    const downloadPromise=page.waitForEvent('download');
    await page.evaluate(()=>document.querySelector('#exportBtn').click());
    const download=await downloadPromise;
    await page.locator('#fileInput').setInputFiles(await download.path());
    await page.waitForTimeout(150);
    assert.equal(await page.evaluate(()=>P.broker.next),'Ask a designer to verify rooms and access');
    // Capture the real share handler without touching the system clipboard.
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>window.testSharedURL=value}}));
    await page.locator('#shareBtn').click();
    const sharedURL=await page.evaluate(()=>window.testSharedURL);
    assert.ok(sharedURL?.includes('#project='));
    const client=await context.newPage();
    client.on('pageerror',error=>errors.push(error.message));
    await client.goto(sharedURL);
    assert.equal(await client.locator('#brokerReport').isVisible(),true);
    assert.equal(await client.locator('#brokerNext').isDisabled(),true);
    await client.locator('#brokerReportClose').click();
    assert.equal(await client.locator('#brokerEdit').isDisabled(),true);
    assert.equal(await client.locator('#undoBtn').isDisabled(),true);
    await client.setViewportSize({width:390,height:844});
    await client.locator('#brokerResult').click();
    assert.equal(await client.locator('#brokerReport').isVisible(),true);
    await page.locator('#newProject').click();
    await page.locator('#useExample').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true);
    await page.locator('#simulationNeedsDetails summary').click();
    await page.locator('#simPeople').fill('100');
    await page.locator('[data-simulation=compact]').click();
    assert.deepEqual(await page.evaluate(()=>[P.w,P.h,P.objects.filter(o=>o.type==='column').length]),[12000,9000,0]);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.broker.people),100);
    assert.match(await page.locator('#quickAssessment').innerText(),/Not a fit yet/);
    await page.locator('#newProject').click();
    await page.locator('#useExample').click();
    await page.locator('#simulationNeedsDetails summary').click();
    await page.locator('#simPeople').fill('16');
    await page.locator('[data-simulation=spacious]').click();
    assert.deepEqual(await page.evaluate(()=>[P.w,P.h,P.objects.filter(o=>o.type==='exit').length]),[24000,16000,2]);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    await page.locator('#openBrief').click();
    assert.equal(await page.locator('#brokerIntake').isVisible(),true,'Edit needs opens full needs directly from a generated plan');
    assert.equal(await page.locator('#briefModal').isVisible(),false);
    await page.locator('#broker-assignedStaff').fill('48');
    await page.locator('#broker-peakOnsite').fill('30');
    await page.locator('#broker-workstationPolicy').selectOption('shared');
    await page.locator('#broker-sourceUrl').fill('https://example.org/public-brief');
    await page.locator('#addExtraSpace').click();
    await page.locator('#extraSpaceRows [data-extra="kind"]').selectOption('meeting');
    await page.locator('#extraSpaceRows [data-extra="seats"]').fill('20');
    await page.locator('#addRelation').click();
    await page.locator('#relationRows [data-relation="from"]').fill('coffee bar');
    await page.locator('#relationRows [data-relation="rule"]').selectOption('away');
    await page.locator('#relationRows [data-relation="to"]').fill('workstations');
    await page.locator('#addDepartment').click();
    await page.locator('#departmentRows [data-department="name"]').fill('Sales');
    await page.locator('#departmentRows [data-department="assigned"]').fill('8');
    await page.locator('#departmentRows [data-department="peakOnsite"]').fill('5');
    await page.locator('#departmentRows [data-department="activity"]').selectOption('calls');
    await page.locator('#workAreaDetails summary').click();
    await page.locator('#addWorkArea').click();
    await page.locator('#workAreaRows [data-work-area="name"]').fill('Sales team');
    await page.locator('#workAreaRows [data-work-area="activity"]').selectOption('calls');
    await page.locator('#workAreaRows [data-work-area="targetDesks"]').fill('100');
    assert.match(await page.locator('#workAreaError').innerText(),/exceed the total/);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),true,'work-area desk targets cannot silently expand the customer total');
    await page.locator('#workAreaRows [data-work-area="targetDesks"]').fill('8');
    await page.locator('#workAreaRows [data-work-area="minimumDesks"]').fill('6');
    assert.match(await page.locator('#workAreaTotal').innerText(),/8 of 16 requested/);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),false);
    await page.locator('#addWorkArea').click();
    await page.locator('#workAreaRows [data-work-area="name"]').nth(1).fill('Design team');
    await page.locator('#workAreaRows [data-work-area="targetDesks"]').nth(1).fill('4');
    const salesAreaId=await page.locator('#workAreaRows [data-work-area-id]').first().getAttribute('data-work-area-id');
    const designAreaId=await page.locator('#workAreaRows [data-work-area-id]').nth(1).getAttribute('data-work-area-id');
    await page.locator('#addTeamRelation').click();
    await page.locator('#teamRelationRows [data-team-relation="fromId"]').selectOption(salesAreaId);
    await page.locator('#teamRelationRows [data-team-relation="toId"]').selectOption(salesAreaId);
    assert.match(await page.locator('#teamRelationError').innerText(),/cannot be near or away from itself/);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),true);
    await page.locator('#teamRelationRows [data-team-relation="toId"]').selectOption(designAreaId);
    assert.equal(await page.locator('#brokerForm button.primary').isDisabled(),false);
    await page.locator('#addTradeoff').click();
    await page.locator('#tradeoffRows [data-tradeoff="target"]').selectOption('meeting');
    await page.locator('#tradeoffRows [data-tradeoff="action"]').selectOption('reduce');
    await page.locator('#tradeoffRows [data-tradeoff="minimum"]').fill('1');
    await page.locator('#brokerForm button.primary').click();
    assert.equal(await page.evaluate(()=>P.broker.requirements.version),3);
    assert.equal(await page.evaluate(()=>P.broker.requirements.staffing.peakOnsite),30);
    assert.equal(await page.evaluate(()=>P.broker.requirements.spaces.find(s=>s.origin==='extra').seats),20);
    assert.equal(await page.evaluate(()=>P.broker.requirements.relations.length),2);
    assert.deepEqual(await page.evaluate(()=>P.broker.requirements.relations.find(r=>r.fromId&&r.toId)&&[P.broker.requirements.relations.find(r=>r.fromId&&r.toId).fromId,P.broker.requirements.relations.find(r=>r.fromId&&r.toId).toId]),[salesAreaId,designAreaId]);
    assert.equal(await page.evaluate(()=>P.broker.requirements.departments[0].activity),'calls');
    assert.deepEqual(await page.evaluate(()=>({people:P.broker.people,area:P.broker.requirements.workAreas[0]})),{people:16,area:{id:salesAreaId,name:'Sales team',activity:'calls',targetDesks:8,minimumDesks:6,priority:'must'}});
    assert.equal(await page.evaluate(()=>P.broker.requirements.tradeoffs[0].minimum),1);
    assert.equal(await page.evaluate(()=>P.draftsStale),true);
    await page.locator('#quickUpdatePlans').click();
    assert.match(await page.locator('#quickAssessment').innerText(),/Not a fit yet/);
    await page.locator('.comparison-details summary').first().click();
    assert.match(await page.locator('.comparison-details').first().innerText(),/Additional meeting room/);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Not assessed/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Department · Sales/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Team work area · Sales team/);
    assert.match(await page.locator('#brokerReportContent').innerText(),/Tradeoff · Meeting rooms/);
    assert.match(await page.locator('#matchingSuggestions').innerText(),/Sales · Calls \/ video meetings/);
    assert.match(await page.locator('#matchingSuggestions').innerText(),/DEMO-BOOTH-1/);
    assert.match(await page.locator('#matchingSuggestions').innerText(),/Candidate only/);
    await page.locator('#brokerReportClose').click();
    await page.reload();
    assert.equal(await page.evaluate(()=>P.broker.requirements.staffing.policy),'shared');
    assert.equal(await page.evaluate(()=>P.broker.requirements.source.url),'https://example.org/public-brief');
    assert.equal(await page.evaluate(()=>P.broker.requirements.workAreas[0].targetDesks),8);
    assert.equal(await page.evaluate(()=>P.broker.requirements.relations.find(r=>r.fromId)?.toId),designAreaId);
    await page.locator('#openBrief').click();
    assert.equal(await page.locator('#brokerIntake').isVisible(),true);
    assert.equal(await page.locator('#extraSpaceRows [data-extra-id]').count(),1);
    assert.equal(await page.locator('#relationRows [data-relation-id]').count(),1);
    assert.equal(await page.locator('#teamRelationRows [data-team-relation-id]').count(),1);
    assert.equal(await page.locator('#departmentRows [data-department-id]').count(),1);
    assert.equal(await page.locator('#workAreaRows [data-work-area-id]').count(),2);
    assert.equal(await page.locator('#tradeoffRows [data-tradeoff-id]').count(),1);
    assert.equal(await page.locator('#broker-peakOnsite').inputValue(),'30');
    await page.locator('#brokerCancel').click();
    await page.locator('#newProject').click();
    await page.locator('#startProject').click();
    await page.locator('#naturalBriefText').fill('Client needs 24 workstations, two 6-person meeting rooms, 3 private offices, 2 phone booths and one training room.');
    await page.locator('#naturalBriefExtract').click();
    await page.locator('#brokerForm button.primary').click();
    assert.equal(await page.locator('#simulationQuickFields').isVisible(),false);
    assert.match(await page.locator('#simulationBriefSummary').innerText(),/1 additional space types/);
    const compactPreview=await page.evaluate(()=>simulationPreviews(simulationBrief())[0]);
    await page.locator('[data-simulation="compact"]').click();
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    assert.equal(await page.evaluate(()=>P.broker.meetingRooms),2);
    assert.equal(await page.evaluate(()=>P.broker.extraSpaces[0].kind),'training');
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.drafts[0].label),compactPreview.best);
    assert.equal(await page.evaluate(()=>brokerAssessment(P).rows.filter(row=>row.status==='Shortfall').length),compactPreview.gaps.length);
    await page.locator('#brokerResult').click();
    assert.match(await page.locator('#brokerReportContent').innerText(),/Training room.*Shortfall/s);
    await page.locator('#brokerTrySpace').click();
    assert.match(await page.locator('#simulationBriefSummary').innerText(),/24 workstations/);
    assert.equal(await page.locator('[data-simulation]').count(),3);
    const spaciousPreview=await page.evaluate(()=>simulationPreviews(simulationBrief())[2]);
    await page.locator('[data-simulation="spacious"]').click();
    assert.equal(await page.evaluate(()=>P.source.fixtureId),'spacious');
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    assert.equal(await page.evaluate(()=>P.broker.extraSpaces[0].kind),'training');
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.drafts[0].label),spaciousPreview.best);
    assert.equal(await page.evaluate(()=>brokerAssessment(P).rows.filter(row=>row.status==='Shortfall').length),spaciousPreview.gaps.length);
    await page.locator('#decisionOpen').click();
    assert.match(await page.locator('#decisionContent').innerText(),/40 requested workstations/);
    await page.evaluate(()=>{savedDecision.sites.find(site=>site.fixtureId==='spacious').fixtureVersion=99});
    await page.locator('#decisionContinue').click();
    assert.match(await page.locator('#decisionContinueError').innerText(),/sample space has changed/);
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    await page.evaluate(()=>{savedDecision.sites.find(site=>site.fixtureId==='spacious').fixtureVersion=1;savedDecision.plannerVersion='old-layout-version'});
    await page.locator('#decisionContinue').click();
    assert.match(await page.locator('#decisionContinueError').innerText(),/layout engine has changed/);
    await page.evaluate(()=>{savedDecision.plannerVersion=DECISION_PLANNER_VERSION;savedDecision.brief.requirements.version=2});
    await page.locator('#decisionContinue').click();
    assert.match(await page.locator('#decisionContinueError').innerText(),/customer needs format has changed/);
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    await page.evaluate(()=>{savedDecision.brief.requirements.version=3});
    await page.locator('#decisionContinue').click();
    assert.equal(await page.locator('#decisionModal').isVisible(),true);
    assert.equal(await page.evaluate(()=>P.broker.people),24);
    allowDecisionReplacement=true;
    await page.locator('#decisionContinue').click();
    assert.equal(decisionReplacementPrompts,2);
    assert.equal(await page.locator('#decisionModal').isVisible(),false);
    assert.equal(await page.evaluate(()=>P.source.fixtureId),'spacious');
    assert.equal(await page.evaluate(()=>P.source.fixtureVersion),1);
    assert.equal(await page.evaluate(()=>P.broker.people),40);
    assert.equal(await page.evaluate(()=>P.drafts.length),3);
    assert.equal(await page.evaluate(()=>P.draftsStale),false);
    await page.locator('#decisionOpen').click();
    assert.match(await page.locator('#decisionContent').innerText(),/40 requested workstations/);
    assert.match(await page.locator('#decisionContent').innerText(),/Investigate access and the exact measured plan/);
    await page.locator('#decisionClose').click();
    await page.locator('#brokerResult').click();
    await page.locator('#brokerTrySpace').click();
    await page.locator('#simulationEditNeeds').click();
    assert.equal(await page.locator('#brokerForm').isVisible(),true,'full needs editor opens from an existing comparison');
    await page.locator('#brokerCancel').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true,'cancel returns to the same space comparison');
    await page.locator('#simulationEditNeeds').click();
    await page.locator('#broker-people').fill('41');
    await page.locator('#brokerForm button.primary').click();
    assert.equal(await page.locator('#simulationModal').isVisible(),true,'saving needs returns to compare spaces');
    assert.match(await page.locator('#simulationBriefSummary').innerText(),/41 workstations/);
    assert.equal(await page.evaluate(()=>P.draftsStale),true,'old layouts are marked stale after needs change');
    assert.deepEqual(errors,[]);
    console.log('PASS: intake, generation, assessment, reload, export/import, share and saved-decision continuation');
  } finally {if(browser)await browser.close();await new Promise(resolve=>server.close(resolve))}
})().catch(error=>{console.error(error);process.exitCode=1});
