/* Broker intake and client-facing assessment. Geometry remains in millimetres. */
const brokerDefaults = () => ({address:'',client:'',area:0,areaUnit:'sqm',people:36,meetingRooms:2,roomSeats:6,offices:0,phones:2,pantry:false,reception:false,notes:'',next:'Arrange a site visit'});
let pendingBroker = null;
const brokerStyle = document.createElement('style');
brokerStyle.textContent = '.dialog{max-height:90vh;overflow:auto}.broker-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.broker-table{width:100%;border-collapse:collapse}.broker-table td,.broker-table th{text-align:left;padding:9px;border-bottom:1px solid #dfe3e8}.broker-table th{font-size:12px;color:#667085}.broker-summary{white-space:pre-wrap}.field textarea{width:100%;min-height:65px;font:inherit}#brokerReport .dialog{width:min(850px,100%)}@media(max-width:620px){.broker-grid{grid-template-columns:1fr}.top{height:auto;min-height:58px;flex-wrap:wrap;padding:10px}.top button{font-size:12px}}@media print{body>*{display:none!important}body>#brokerReport{display:block!important;position:static;background:white;padding:0}#brokerReport .dialog{box-shadow:none;max-height:none;width:100%}#brokerReport .actions{display:none}}';
document.head.append(brokerStyle);
function brokerField(label,key,type='text',extra='') {return `<div class="field"><label for="broker-${key}">${label}</label><input id="broker-${key}" name="${key}" type="${type}" ${extra}></div>`}
document.body.insertAdjacentHTML('beforeend', `<div class="modal" id="brokerIntake" hidden><form class="dialog wide" id="brokerForm"><div class="eyebrow">1 · Property and client</div><h1>Can this office work for your client?</h1><p>Record the listing and required spaces, then review the floor plan.</p><div class="broker-grid">
${brokerField('Property address / suite','address','text','required maxlength="200"')}${brokerField('Client / team name','client','text','required maxlength="120"')}
${brokerField('Advertised rental area (optional)','area','number','min="0" step="any"')}<div class="field"><label for="broker-areaUnit">Area unit</label><select name="areaUnit" id="broker-areaUnit"><option value="sqm">Square metres</option><option value="sqft">Square feet</option></select></div>
${brokerField('Required workstations (excluding private offices)','people','number','required min="4" max="300"')}${brokerField('Private offices','offices','number','required min="0" max="30"')}
${brokerField('Meeting rooms','meetingRooms','number','required min="0" max="10"')}${brokerField('Seats in each meeting room','roomSeats','number','required min="1" max="30"')}
${brokerField('Phone booths','phones','number','required min="0" max="20"')}<div class="field"><label><input type="checkbox" name="pantry"> Pantry required</label><label><input type="checkbox" name="reception"> Reception required</label></div></div>
<div class="field"><label for="broker-notes">Other requirements / different room sizes</label><textarea name="notes" id="broker-notes" maxlength="1500"></textarea></div><p class="empty">Rental area is kept separately from the usable dimensions used for layout.</p><div class="actions"><button type="button" class="btn" id="brokerCancel">Back</button><button class="btn primary">Continue to floor plan</button></div></form></div>
<div class="modal" id="brokerReport" hidden><div class="dialog wide"><div id="brokerReportContent"></div><div class="actions"><button class="btn" id="brokerReportClose">Close</button><button class="btn" id="brokerPrint">Print / save PDF</button><button class="btn primary" id="brokerShare">Copy client link</button></div></div></div>`);
$('#exportBtn').insertAdjacentHTML('beforebegin','<button id="brokerEdit">Property & client</button><button id="brokerResult">Client summary</button>');
$('#welcomeModal h1').textContent='Check a property against your client’s needs';
$('#welcomeModal p').textContent='Add the property and client brief, review usable dimensions and fixed conditions, then compare layouts and share a needs assessment.';
$('#startProject').textContent='Assess a property';
const oldStartProject = $('#startProject').onclick;
function showBrokerIntake(edit=false){if(readOnly)return;const b=edit?(P.broker||brokerDefaults()):brokerDefaults();const form=$('#brokerForm');form.dataset.edit=String(edit);for(const [key,value] of Object.entries(b)){const input=form.elements.namedItem(key);if(input){if(input.type==='checkbox')input.checked=value;else input.value=value}}$('#welcomeModal').hidden=true;$('#brokerIntake').hidden=false}
$('#startProject').onclick=()=>showBrokerIntake();
$('#brokerEdit').onclick=()=>showBrokerIntake(true);
$('#brokerCancel').onclick=()=>{$('#brokerIntake').hidden=true;if($('#brokerForm').dataset.edit!=='true')$('#welcomeModal').hidden=false};
function syncBrokerBrief(){if(!P.broker)return;const b=P.broker;$('#briefPeople').value=b.people;$('#briefMeeting').value=b.meetingRooms*b.roomSeats;$('#briefPhone').value=b.phones;$('#briefMode').value=b.mode||'hybrid'}
const originalNormalizeProject=normalizeProject;
normalizeProject=function(project){const result=originalNormalizeProject(project);queueMicrotask(()=>{if(P===result){syncBrokerBrief();render()}});return result};
$('#brokerForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,b={...(P.broker||brokerDefaults())};for(const key of Object.keys(b)){const input=form.elements.namedItem(key);if(input)b[key]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value.trim()}$('#brokerIntake').hidden=true;if(form.dataset.edit==='true'){snapshot();P.broker=b;if(P.drafts.length)P.draftsStale=true;syncBrokerBrief();save();return}pendingBroker=b;oldStartProject();$('#projectName').value=`${b.client} · ${b.address}`;setBrokerUnits('m',false)};
$('#siteWidth').closest('.row').insertAdjacentHTML('beforebegin','<div class="field"><label for="brokerLengthUnit">Usable internal dimensions — not rental area</label><select id="brokerLengthUnit"><option value="m">Metres</option><option value="ft">Feet (decimal)</option></select></div>');
let brokerLengthUnit='mm';
function setBrokerUnits(unit,convert=true){const factors={mm:1,m:1000,ft:304.8};for(const selector of ['#siteWidth','#siteHeight']){const input=$(selector);const mm=convert?Number(input.value)*factors[brokerLengthUnit]:Number(input.value);input.value=+(mm/factors[unit]).toFixed(4);input.min=+(3000/factors[unit]).toFixed(4);input.step='any'}brokerLengthUnit=unit;$('#brokerLengthUnit').value=unit;$('#widthLabel').textContent=`Usable width (${unit})`;$('#depthLabel').textContent=`Usable depth (${unit})`}
$('#brokerLengthUnit').onchange=e=>setBrokerUnits(e.target.value);
document.querySelectorAll('[name="sourceMode"]').forEach(input=>input.addEventListener('change',()=>setBrokerUnits(brokerLengthUnit)));
const oldProjectSubmit=$('#projectForm').onsubmit;
$('#projectForm').onsubmit=async e=>{const factor=brokerLengthUnit==='ft'?304.8:brokerLengthUnit==='m'?1000:1;const values=[$('#siteWidth').value,$('#siteHeight').value],before=P;$('#siteWidth').value=Number(values[0])*factor;$('#siteHeight').value=Number(values[1])*factor;try{await oldProjectSubmit(e);if(P!==before){P.broker=pendingBroker||brokerDefaults();pendingBroker=null;syncBrokerBrief();save()}}finally{$('#siteWidth').value=values[0];$('#siteHeight').value=values[1]}};
const originalRender=render;
render=function(){originalRender();$('#briefMeeting').readOnly=!!P.broker;$('#wizardMeeting').readOnly=!!P.broker;if(!readOnly&&P.broker){$('#setupTitle').textContent=P.drafts.length?(P.draftsStale?'Needs changed · update layouts':'Layouts ready · open Client summary'):'2 · Review usable space and mark entrance / exit'}if(readOnly){document.querySelectorAll('#inspector input,#inspector button,#undoBtn,#mainClear,#minorClear,#brokerEdit,#briefPeople,#briefMeeting,#briefPhone,#briefMode').forEach(el=>el.disabled=true)}};
const originalSave=save;
save=function(){if(readOnly){render();return}originalSave()};
const originalGenerate=generateDrafts;
generateDrafts=function(){if(readOnly)return;if(P.broker){P.broker.people=Number($('#briefPeople').value);P.broker.phones=Number($('#briefPhone').value);P.broker.mode=$('#briefMode').value;$('#briefMeeting').value=P.broker.meetingRooms*P.broker.roomSeats}originalGenerate()};
$('#generateDrafts').onclick=generateDrafts;
// Room counts live in the client brief; a total seat field cannot replace them.
$('#briefMeeting').readOnly=!!P.broker;$('#wizardMeeting').readOnly=!!P.broker;
for(const selector of ['#briefPeople','#briefPhone','#briefMode'])$(selector).addEventListener('change',()=>{if(readOnly)return;if(P.broker){P.broker.people=Number($('#briefPeople').value);P.broker.phones=Number($('#briefPhone').value);P.broker.mode=$('#briefMode').value}if(P.drafts.length)P.draftsStale=true;save()});
function brokerAssessment(project){const b=project.broker||brokerDefaults(),items=project.furniture||[],count=kind=>items.filter(f=>f.kind===kind).length,workstations=count('desk')+count('cubicle')+2*count('bench2');const rows=[{name:'Open workstations',required:b.people,actual:workstations,status:workstations>=b.people?'Met':'Shortfall'},{name:'Phone booths',required:b.phones,actual:count('phone'),status:count('phone')>=b.phones?'Met':'Shortfall'}];if(b.meetingRooms)rows.push({name:`Meeting rooms · ${b.roomSeats} seats each`,required:b.meetingRooms,actual:`${count('meeting')} six-seat tables; enclosure and room sizes unverified`,status:'Needs review'});for(const [key,name] of [['offices','Private offices'],['pantry','Pantry'],['reception','Reception']])if(b[key])rows.push({name,required:Number(b[key]),actual:'Not verified by this layout',status:'Needs review'});if(b.notes)rows.push({name:'Other requirements',required:b.notes,actual:'Review with client',status:'Needs review'});const stale=project.draftsStale||!project.site?.confirmed;const title=!project.drafts?.length?'Complete site review and generate layouts':stale?'Assessment out of date':rows.some(r=>r.status==='Shortfall')?'Current layout has shortfalls':'Potential candidate · room and access review needed';return {rows,title,stale}}
function showBrokerReport(){const b=P.broker||brokerDefaults(),a=brokerAssessment(P);const issues=checks();$('#brokerReportContent').innerHTML=`<div class="eyebrow">Property fit · preliminary assessment</div><h1>${esc(a.title)}</h1><p>${esc(b.client||P.name)} · ${esc(b.address||'Property details not entered')}</p><p>Advertised rental area: ${b.area?esc(b.area)+' '+esc(b.areaUnit):'Not provided'} · Layout rectangle: ${(P.w*P.h/1e6).toFixed(1)} m² / ${(P.w*P.h/92903.04).toFixed(0)} sq ft (before fixed obstructions).</p><table class="broker-table"><thead><tr><th>Client requirement</th><th>Requested</th><th>Current layout</th><th>Result</th></tr></thead><tbody>${a.rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.required)}</td><td>${esc(r.actual)}</td><td>${a.stale||!P.drafts.length?'Not assessed':esc(r.status)}</td></tr>`).join('')}</tbody></table><p>${issues.length?`${issues.length} basic layout issue(s) require review.`:'No basic furniture conflicts detected.'} Door clearance, enclosed room layouts and continuous exit routes still require review.</p><div class="field"><label for="brokerNext">Next step</label><select id="brokerNext" ${readOnly?'disabled':''}><option>Arrange a site visit</option><option>Request a measured floor plan</option><option>Ask a designer to verify rooms and access</option><option>Find another property</option></select></div><p class="empty">This assessment records the selected concept and client requirements. Furniture counts alone do not confirm that the property meets all requirements.</p>`;$('#brokerNext').value=b.next;$('#brokerNext').onchange=e=>{if(readOnly)return;P.broker=P.broker||brokerDefaults();P.broker.next=e.target.value;save()};$('#brokerShare').hidden=readOnly;$('#brokerReport').hidden=false}
$('#brokerResult').onclick=showBrokerReport;$('#brokerReportClose').onclick=()=>$('#brokerReport').hidden=true;$('#brokerPrint').onclick=()=>window.print();
async function shareBrokerReport(){if(P.draftsStale||!P.site?.confirmed||!P.drafts.length){$('#hint').textContent='Review the site and regenerate layouts before sharing.';return}const shared=JSON.parse(JSON.stringify(P));if(shared.source?.preview)delete shared.source.preview;const bytes=new TextEncoder().encode(JSON.stringify(shared));let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);const url=new URL('studio.html',location.href);url.hash='project='+encodeURIComponent(btoa(binary));try{await navigator.clipboard.writeText(url.href);alert('Client link copied. It includes the client brief and assessment. Anyone with the link can view it; this snapshot does not update automatically.')}catch{window.prompt('Copy this client link:',url.href)}}
$('#shareBtn').onclick=shareBrokerReport;$('#brokerShare').onclick=shareBrokerReport;
// Keep blocked-share feedback visible above the modal, not behind it on the canvas.
for(const selector of ['#shareBtn','#brokerShare'])$(selector).addEventListener('click',event=>{
  if(!P.draftsStale&&P.site?.confirmed&&P.drafts.length)return;
  event.stopImmediatePropagation();
  alert('This assessment is not current. Close the summary, review the site and regenerate layouts before sharing.');
},true);
syncBrokerBrief();render();if(readOnly&&P.broker)showBrokerReport();
