const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('broker.js','utf8');
const context=vm.createContext({});
vm.runInContext(source.slice(source.indexOf('const brokerDefaults'),source.indexOf('let pendingBroker'))+source.slice(source.indexOf('const mvpSpaces ='),source.indexOf('function simulationBrief('))+source.slice(source.indexOf('function validRoomForAssessment('),source.indexOf('function showBrokerReport(')),context);
function assess(overrides={}){context.project={broker:{people:4,phones:0,meetingRooms:2,roomSeats:6,offices:3,pantry:true},furniture:[{kind:'bench2'},{kind:'bench2'},{kind:'meeting'},{kind:'meeting'}],drafts:[{}],site:{confirmed:true},...overrides};return vm.runInContext('brokerAssessment(project)',context)}
test('meeting tables never count as planned rooms',()=>{const a=assess();assert.equal(a.rows.find(r=>r.name.startsWith('Meeting rooms')).status,'Shortfall');assert.equal(a.rows.find(r=>r.name==='Private offices').status,'Shortfall');assert.match(a.title,/shortfalls/)});
test('a correctly sized room with a corridor door is only a concept placement',()=>{const room={id:'room1',type:'room',kind:'meeting',x:500,y:500,x2:3800,y2:3500,plannedSeats:6,door:{side:'south',width:900}};const a=assess({w:10000,h:8000,broker:{people:4,phones:0,meetingRooms:1,roomSeats:6,offices:0,pantry:false},objects:[room,{id:'corridor',type:'corridor',x:0,y:3500,x2:10000,y2:4700}]});assert.equal(a.rows.find(r=>r.name.startsWith('Meeting rooms')).status,'Placed · concept')});
test('a room without corridor access remains a shortfall',()=>{const room={id:'room1',type:'room',kind:'meeting',x:500,y:500,x2:3800,y2:3500,plannedSeats:6,door:{side:'north',width:900}};const a=assess({w:10000,h:8000,broker:{people:4,phones:0,meetingRooms:1,roomSeats:6,offices:0,pantry:false},objects:[room,{id:'corridor',type:'corridor',x:0,y:3500,x2:10000,y2:4700}]});assert.equal(a.rows.find(r=>r.name.startsWith('Meeting rooms')).status,'Shortfall')});
test('a room with an east door on a vertical corridor is a concept placement',()=>{const room={id:'room1',type:'room',kind:'meeting',x:500,y:500,x2:3800,y2:3500,plannedSeats:6,door:{side:'east',width:900}};const a=assess({w:10000,h:8000,broker:{people:4,phones:0,meetingRooms:1,roomSeats:6,offices:0,pantry:false},objects:[room,{id:'corridor',type:'corridor',x:3800,y:0,x2:5000,y2:8000}]});assert.equal(a.rows.find(r=>r.name.startsWith('Meeting rooms')).status,'Placed · concept')});
test('a corridor-adjacent dining zone with linked furniture counts only while geometry is valid',()=>{
  const zone={id:'dining1',type:'zone',kind:'dining',x:500,y:500,x2:3500,y2:3300},corridor={id:'corridor',type:'corridor',x:0,y:3300,x2:10000,y2:4500},item={id:'table1',type:'furniture',kind:'dining4',zoneId:'dining1',x:2000,y:1900,w:2400,h:2200};
  const base={w:10000,h:8000,broker:{people:0,phones:0,meetingRooms:0,offices:0,pantry:false,diningSeats:4},objects:[zone,corridor],furniture:[item]};
  assert.equal(assess(base).rows.find(r=>r.name==='Dining seats').status,'Placed · concept');
  assert.equal(assess({...base,furniture:[{...item,x:4500}]}).rows.find(r=>r.name==='Dining seats').status,'Shortfall');
  assert.equal(assess({...base,objects:[zone,{...corridor,y:5000,y2:6200}]}).rows.find(r=>r.name==='Dining seats').status,'Shortfall');
});
test('an explicit reception-to-entrance rule screens valid concepts and blocks hard misses',()=>{
  const zone={id:'reception1',type:'zone',kind:'reception',x:500,y:500,x2:3700,y2:3300},corridor={id:'corridor',type:'corridor',x:0,y:3300,x2:10000,y2:4500},item={id:'counter',kind:'reception',zoneId:'reception1',x:2100,y:1900,w:1800,h:800};
  const broker={people:0,phones:0,meetingRooms:0,reception:true,relations:[{from:'reception',rule:'entrance',priority:'must'}]},base={w:12000,h:9000,broker,objects:[zone,corridor,{id:'entry',type:'door',x:0,y:1600}],furniture:[item]};
  assert.equal(assess(base).placement[0].status,'pass');
  assert.equal(assess({...base,objects:[zone,corridor,{id:'entry',type:'door',x:11500,y:8000}]}).rows.find(r=>r.name.startsWith('Spatial relation')).status,'Shortfall');
  assert.equal(assess({...base,objects:[zone,corridor]}).rows.find(r=>r.name.startsWith('Spatial relation')).status,'Not assessed');
  assert.equal(assess({...base,objects:[corridor,{id:'entry',type:'door',x:0,y:1600}]}).title,'Current layout has shortfalls');
  assert.equal(assess({...base,draftsStale:true}).placement[0].status,'unknown');
});
test('office-window rules apply to the named role and remain review-only when preferred',()=>{
  const room={id:'office1',type:'room',kind:'office',role:'executive',x:500,y:500,x2:3500,y2:3500,door:{side:'south',width:900}},corridor={id:'corridor',type:'corridor',x:0,y:3500,x2:12000,y2:4700},window={id:'window1',type:'window',x:2000,y:0};
  const broker={people:0,phones:0,meetingRooms:0,offices:1,officeRoles:{executive:1},relations:[{from:'executive office',rule:'window',priority:'must'}]},base={w:12000,h:9000,broker,objects:[room,corridor,window],furniture:[]};
  assert.equal(assess(base).placement[0].status,'pass');
  assert.equal(assess({...base,objects:[room,corridor,{...window,x:11000,y:8500}]}).rows.find(r=>r.name.startsWith('Spatial relation')).status,'Shortfall');
  assert.equal(assess({...base,broker:{...broker,relations:[{from:'executive office',rule:'window',priority:'preferred'}]},objects:[room,corridor,{...window,x:11000,y:8500}]}).rows.find(r=>r.name.startsWith('Spatial relation')).status,'Needs review');
  assert.equal(assess({...base,objects:[room,corridor]}).placement[0].status,'unknown');
});
test('insufficient workstations produce shortfall',()=>assert.match(assess({furniture:[]}).title,/shortfalls/));
test('changed site invalidates previous assessment',()=>assert.equal(assess({draftsStale:true}).title,'Assessment out of date'));
test('no plans cannot be presented as an assessment',()=>assert.match(assess({drafts:[]}).title,/generate layouts/));
test('brief and next step survive JSON export',()=>{const p={broker:{client:'Client A',address:'LA suite 2',meetingRooms:2,roomSeats:8,next:'Arrange a site visit'}};assert.deepEqual(JSON.parse(JSON.stringify(p)),p)});
test('MVP sample geometry stays fixed when the brief changes',()=>{const first=vm.runInContext('simulatedCandidates({people:12})',context),second=vm.runInContext('simulatedCandidates({people:100})',context);assert.equal(first.length,3);assert.deepEqual(Array.from(first,c=>[c.width,c.height,c.area]),[[12000,9000,108],[18000,12000,216],[24000,16000,384]]);assert.deepEqual(JSON.parse(JSON.stringify(first)),JSON.parse(JSON.stringify(second)));assert.deepEqual(Array.from(first,c=>[c.columns.length,c.blocked.length,c.openings.filter(o=>o.type==='exit').length]),[[0,0,1],[2,1,1],[4,1,2]])});
test('legacy briefs migrate to versioned staffing and space requirements',()=>{const b=vm.runInContext('normalizeBrokerBrief({people:16,meetingRooms:2,roomSeats:6,diningSeats:5})',context);assert.equal(b.requirements.version,3);assert.equal(b.requirements.staffing.workstations,16);assert.equal(b.requirements.spaces.find(s=>s.kind==='meeting').count,2);assert.equal(b.requirements.spaces.find(s=>s.kind==='dining').count,2)});
test('mixed spaces are counted while unsupported relationships stay unassessed',()=>{const b=vm.runInContext("normalizeBrokerBrief({people:4,phones:0,meetingRooms:0,extraSpaces:[{id:'large',kind:'meeting',count:1,seats:20,priority:'must'},{id:'quiet',kind:'focus',count:2,priority:'preferred'}],relations:[{from:'coffee bar',rule:'away',to:'workstations',priority:'must'}]})",context);assert.equal(b.requirements.spaces.find(s=>s.id==='large').seats,20);assert.equal(b.requirements.relations.length,1);const a=assess({broker:b});assert.equal(a.rows.filter(r=>r.status==='Not assessed').length,1);assert.equal(a.rows.find(r=>r.name.startsWith('Meeting room (additional size)')).status,'Shortfall');assert.equal(a.rows.find(r=>r.name.startsWith('Focus room')).status,'Needs review');assert.equal(a.title,'Current layout has shortfalls')});
test('version 2-only briefs keep their spaces, staffing and provenance on import',()=>{const b=vm.runInContext("normalizeBrokerBrief({requirements:{version:2,staffing:{assigned:40,peakOnsite:25,workstations:24,policy:'shared'},spaces:[{id:'base-workstation',origin:'base',kind:'workstation',count:24},{id:'base-dining',origin:'base',kind:'dining',count:2,seats:4,requestedSeats:5},{id:'focus1',origin:'extra',kind:'focus',count:2,priority:'must'}],relations:[{id:'r1',from:'pantry',rule:'away',to:'desks',priority:'must'}],source:{url:'https://example.org/brief'}}})",context);assert.equal(b.people,24);assert.equal(b.meetingRooms,0);assert.equal(b.diningSeats,5);assert.equal(b.requirements.staffing.peakOnsite,25);assert.equal(b.requirements.spaces.find(s=>s.id==='focus1').count,2);assert.equal(b.requirements.source.url,'https://example.org/brief')});
test('department activities suggest candidate types and tradeoffs remain unapplied',()=>{const b=vm.runInContext("normalizeBrokerBrief({people:4,phones:0,meetingRooms:0,departments:[{name:'Sales',assigned:8,peakOnsite:5,activity:'calls'}],tradeoffs:[{target:'meeting',action:'reduce',minimum:1,alternative:'Share with training'}]})",context);assert.equal(b.requirements.version,3);assert.equal(b.requirements.departments[0].activity,'calls');assert.equal(b.requirements.tradeoffs[0].minimum,1);const rows=assess({broker:b}).rows;assert.match(rows.find(r=>r.name==='Department · Sales').actual,/Phone booths/);assert.equal(rows.find(r=>r.name==='Tradeoff · Meeting rooms').status,'Not assessed')});
test('size flexibility is separate from quantity tradeoffs and old briefs remain compatible',()=>{const b=vm.runInContext("normalizeBrokerBrief({people:12,offices:1,pantry:true,spaceSizing:{'base-office':{mode:'fixed'}},tradeoffs:[{target:'pantry',action:'reduce',minimum:1}]})",context);assert.equal(b.requirements.spaceSizing['base-office'].mode,'fixed');assert.equal(b.requirements.spaceSizing['base-pantry'].mode,'suggest');assert.equal(b.requirements.spaceSizing['base-workstation'].mode,'fixed');assert.equal(b.requirements.tradeoffs[0].minimum,1);const imported=vm.runInContext("normalizeBrokerBrief({requirements:{version:3,staffing:{workstations:12},spaces:[{id:'base-office',kind:'office',origin:'base',count:1}],spaceSizing:{'base-office':{mode:'fixed'}}}})",context);assert.equal(imported.requirements.spaceSizing['base-office'].mode,'fixed')});
test('version 3-only briefs preserve departments and tradeoffs on import',()=>{const b=vm.runInContext("normalizeBrokerBrief({requirements:{version:3,staffing:{workstations:4},spaces:[],departments:[{id:'d1',name:'Sales',assigned:8,peakOnsite:5,activity:'calls'}],relations:[],tradeoffs:[{id:'t1',target:'meeting',action:'share',minimum:0,alternative:'Training'}]}})",context);assert.equal(b.requirements.departments[0].name,'Sales');assert.equal(b.requirements.tradeoffs[0].action,'share')});
test('matcher ranks eligible spaces and connects only capacity-compatible sample furniture',()=>{const result=vm.runInContext("matchBriefNeeds({spaces:[{id:'meeting8',kind:'meeting',count:1,seats:8}],departments:[{id:'sales',name:'Sales',activity:'calls'}]}, {w:18000,h:12000}, [{kind:'meeting',sku:'TABLE-6'},{kind:'phone',sku:'BOOTH-1'}])",context);assert.equal(result[0].candidates[0].status,'candidate');assert.equal(result[0].candidates[0].sku,null);assert.equal(result[1].candidates[0].kind,'phone');assert.equal(result[1].candidates[0].sku,'BOOTH-1')});
test('matcher rejects obvious capacity and envelope failures without claiming layout fit',()=>{const result=vm.runInContext("matchBriefNeeds({spaces:[{id:'too-many',kind:'workstation',count:100},{id:'too-big',kind:'meeting',count:1,seats:30},{id:'it',kind:'it',count:1}]},{w:12000,h:9000})",context);assert.equal(result[0].candidates[0].status,'ruled-out');assert.match(result[0].candidates[0].reason,/gross site area/);assert.equal(result[1].candidates[0].status,'ruled-out');assert.match(result[1].candidates[0].reason,/envelope/);assert.equal(result[2].candidates[0].status,'candidate')});
test('space substitutes require explicit client permission',()=>{const no=vm.runInContext("matchBriefNeeds({spaces:[{id:'training',kind:'training',count:1,seats:8}]},{w:18000,h:12000})",context),yes=vm.runInContext("matchBriefNeeds({spaces:[{id:'training',kind:'training',count:1,seats:8}],tradeoffs:[{target:'training',action:'substitute'}]},{w:18000,h:12000})",context);assert.equal(no[0].candidates.length,1);assert.equal(no[0].candidates[0].status,'candidate');assert.equal(yes[0].candidates.find(c=>c.kind==='meeting').status,'candidate')});
test('extracted prose draft does not turn unstated staff into desks or invent room capacity',()=>{const b=vm.runInContext("briefFromExtraction({assignedStaff:40,people:null,meetingRooms:2,roomSeats:null,extraSpaces:[],relations:[],departments:[],tradeoffs:[],questions:[]})",context);assert.equal(b.people,0);assert.equal(b.assignedStaff,40);assert.equal(b.roomSeats,0);assert.equal(b.phones,0);assert.equal(b.requirements.spaces.find(s=>s.kind==='meeting')?.seats,0);assert.equal(b.extractionQuestions.length,2)});
test('mock parser extracts explicit Chinese office needs without inferring desks from staff',()=>{const data=vm.runInContext("mockExtractBrief('40名员工，高峰到岗28人，需要24个共享工位、两间6人会议室、4个电话亭、3间独立办公室和茶水间。销售团队经常打电话。')",context);assert.equal(data.assignedStaff,40);assert.equal(data.peakOnsite,28);assert.equal(data.people,24);assert.equal(data.workstationPolicy,'shared');assert.equal(data.meetingRooms,2);assert.equal(data.roomSeats,6);assert.equal(data.phones,4);assert.equal(data.offices,3);assert.equal(data.pantry,true);assert.equal(data.departments[0].activity,'calls')});
test('mock parser asks for missing headcount and capacity instead of supplying defaults',()=>{const data=vm.runInContext("mockExtractBrief('Forty staff need office space and two meeting rooms.')",context),brief=vm.runInContext("briefFromExtraction(mockExtractBrief('Forty staff need office space and two meeting rooms.'),'mock')",context);assert.equal(data.assignedStaff,40);assert.equal(data.people,null);assert.equal(data.meetingRooms,2);assert.equal(data.roomSeats,null);assert.equal(brief.people,0);assert.equal(brief.roomSeats,0);assert.equal(brief.extractionMode,'mock');assert.equal(brief.extractionQuestions.length,2)});
test('mock parser extracts English counts and never sends unsupported text to a model',()=>{const data=vm.runInContext("mockExtractBrief('Client needs 40 workstations, 3 private offices, two 6-person meeting rooms, 2 phone booths and a pantry.')",context);assert.equal(data.people,40);assert.equal(data.offices,3);assert.equal(data.meetingRooms,2);assert.equal(data.roomSeats,6);assert.equal(data.phones,2);assert.equal(data.pantry,true)});
test('mock parser records video, display and locker spaces explicitly',()=>{const data=vm.runInContext("mockExtractBrief('需要20个工位、1间视频会议室、1个展示区和1个储物柜区。')",context);assert.deepEqual(Array.from(data.extraSpaces,s=>s.kind).sort(),['display','lockers','video'])});
test('extraction keeps unmentioned needs distinct from explicit zero and no',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('We need 24 workstations, no meeting rooms and no pantry.'))",context);assert.equal(b.people,24);assert.equal(b.meetingRooms,0);assert.equal(b.pantry,false);assert.equal(b.intakeAnswers.meetingRooms,'not-needed');assert.equal(b.intakeAnswers.pantry,'not-needed');assert.equal(b.intakeAnswers.offices,'unknown');assert.equal(b.intakeAnswers.phones,'unknown');assert.equal(b.requirements.inputStates.offices,'unknown');assert.equal(b.extractionQuestions.length,0);const rows=assess({broker:b}).rows;assert.equal(rows.some(r=>r.name==='Unconfirmed · Private offices'&&r.status==='Needs review'),true);assert.equal(rows.some(r=>r.name==='Phone booths'&&r.status==='Met'),false)});
test('Chinese mock negation records explicit no rather than a positive need',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('需要24个工位，不需要电话亭，也不需要茶水间。'))",context);assert.equal(b.intakeAnswers.phones,'not-needed');assert.equal(b.intakeAnswers.pantry,'not-needed');assert.equal(b.intakeAnswers.meetingRooms,'unknown')});
test('review confirmation preserves unknowns and clears resolved questions',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('Forty staff need office space and two meeting rooms.'))",context);const edited={...b,people:24,roomSeats:6};const done=vm.runInContext('finalizeIntakeAnswers(edited, baseline, {phones:"not-needed"})',vm.createContext({baseline:b,edited,finalizeIntakeAnswers:vm.runInContext('finalizeIntakeAnswers',context)}));assert.equal(done.intakeConfirmed,true);assert.equal(done.intakeAnswers.people,'requested');assert.equal(done.intakeAnswers.roomSeats,'requested');assert.equal(done.intakeAnswers.phones,'not-needed');assert.equal(done.intakeAnswers.offices,'unknown');assert.equal(done.extractionQuestions.length,0);assert.equal(vm.runInContext('normalizeBrokerBrief(done).requirements.inputStates.offices',vm.createContext({done,normalizeBrokerBrief:vm.runInContext('normalizeBrokerBrief',context)})),'unknown')});
test('six synthetic client briefs keep requested, refused and unmentioned needs separate',()=>{
  const cases=[
    ['24 workstations, two 6-person meeting rooms and 3 private offices.','meetingRooms','requested'],
    ['24 workstations, no meeting rooms and no phone booths.','meetingRooms','not-needed'],
    ['需要18个工位、2个电话亭和茶水间。','phones','requested'],
    ['20 workstations and one training room.','pantry','unknown'],
    ['15 workstations, reception and 4 dining seats.','diningSeats','requested'],
    ['Forty staff need office space.','people','needs-clarification']
  ];
  for(const [prose,key,expected] of cases){context.prose=prose;const b=vm.runInContext('briefFromExtraction(mockExtractBrief(prose))',context);assert.equal(b.intakeAnswers[key],expected,prose);assert.equal(b.requirements.inputStates[key],expected,prose)}
  context.prose='20 workstations and one training room.';const training=vm.runInContext('briefFromExtraction(mockExtractBrief(prose))',context);assert.equal(training.extraSpaces[0].kind,'training');assert.equal(assess({broker:training}).rows.some(r=>r.name.startsWith('Training room')&&r.status==='Shortfall'),true);
});
test('role-specific offices are included in, not added to, the private-office total',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('需要24个工位、1间总经理室和2间总监办公室。'),'mock')",context);assert.equal(b.offices,3);assert.equal(b.officeRoles.executive,1);assert.equal(b.officeRoles.director,2);assert.equal(b.requirements.spaces.find(s=>s.kind==='office').count,3);assert.equal(b.requirements.officeRoles.director,2);assert.equal(b.intakeAnswers.offices,'requested');const rows=assess({broker:b}).rows;assert.equal(rows.find(r=>r.name==='Director offices').status,'Needs review')});
test('unmentioned private offices remain unknown instead of being defaulted to a requirement',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('需要24个工位和2间6人会议室。'),'mock')",context);assert.equal(b.offices,0);assert.equal(b.intakeAnswers.offices,'unknown');assert.equal(b.requirements.spaces.some(s=>s.kind==='office'),false)});
test('suggested areas begin pending and cannot silently become client requirements',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('We need 24 workstations and two 6-person meeting rooms.'))",context);assert.equal(b.suggestedZones.pantry,'pending');assert.equal(b.suggestedZones.reception,'pending');assert.equal(b.suggestedZones.quietWork,'pending');assert.equal(b.suggestedZones.waiting,'pending');assert.equal(b.pantry,false);assert.equal(b.reception,false);assert.equal(b.requirements.spaces.some(s=>['pantry','reception','focus','waiting'].includes(s.kind)),false);assert.equal(assess({broker:b}).rows.find(r=>r.name==='System suggestions · undecided').status,'Needs review')});
test('explicit and refused needs are not replaced by system suggestions',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('We need 24 workstations, one 6-person meeting room and a pantry, but no reception.'))",context);assert.equal(b.suggestedZones.pantry,undefined);assert.equal(b.suggestedZones.reception,undefined);assert.equal(b.intakeAnswers.pantry,'requested');assert.equal(b.intakeAnswers.reception,'not-needed')});
test('overlooked needs survive normalization without inventing quantities or placement',()=>{const b=vm.runInContext("normalizeBrokerBrief({people:24,meetingRooms:0,phones:0,completeness:{teamZones:{state:'requested',note:'Sales 8 together'},quietWork:{state:'uncertain'},storage:{state:'not-needed'},budget:{state:'requested',note:'Ask for budget'}}})",context);assert.equal(b.completeness.teamZones.state,'requested');assert.equal(b.requirements.completeness.teamZones.note,'Sales 8 together');assert.equal(b.requirements.spaces.some(s=>s.kind==='storage'),false);const rows=assess({broker:b}).rows;assert.equal(rows.find(r=>r.name==='Additional need · Teams need distinct work areas').status,'Not assessed');assert.equal(rows.some(r=>r.name==='Additional need · Storage / supplies area'),false);assert.match(rows.find(r=>r.name==='Needs checklist · still to confirm').required,/Quiet \/ focus work area/)});
test('customer uncertainty remains distinct from silence and an explicit no',()=>{const previous=vm.runInContext("briefFromExtraction(mockExtractBrief('We need 24 workstations and two 6-person meeting rooms.'))",context),edited={...previous};context.previous=previous;context.edited=edited;const b=vm.runInContext("normalizeBrokerBrief(finalizeIntakeAnswers(edited,previous,{reception:'uncertain',pantry:'not-needed'}))",context);assert.equal(b.intakeAnswers.reception,'uncertain');assert.equal(b.intakeAnswers.pantry,'not-needed');assert.equal(b.reception,false);const row=assess({broker:b}).rows.find(r=>r.name==='Unconfirmed · Reception');assert.equal(row.required,'Customer unsure')});
test('extracted specialty spaces are shown as already recorded, not duplicated checklist requirements',()=>{const b=vm.runInContext("briefFromExtraction(mockExtractBrief('需要24个工位和1间6人会议室、1间培训室。'),'mock')",context);assert.equal(b.completeness.training.state,'requested');const rows=assess({broker:b}).rows;assert.equal(rows.filter(r=>r.name.startsWith('Additional need · Training')).length,0);assert.equal(rows.filter(r=>r.name.startsWith('Training room')).length,1)});
