// End-to-end acceptance for the three fictional rectangular sites.
const { chromium } = require('playwright');
const { createServer } = require('node:http');
const { readFile } = require('node:fs/promises');
const assert = require('node:assert/strict');
const path = require('node:path');

const fixtures = {compact:[12000,9000,0],balanced:[18000,12000,2],spacious:[24000,16000,4]};
const server = createServer(async(req,res)=>{
  const name=new URL(req.url,'http://localhost').pathname.slice(1);
  if(!['studio.html','sample-furniture.js','studio.js','broker.js','zone-assist.js'].includes(name)){res.writeHead(404);res.end();return}
  res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8');
  res.end(await readFile(path.join(__dirname,name)));
});

function validateLayout(project){
  const box=f=>{const swapped=Math.abs(Math.round((f.rot||0)/90))%2,w=swapped?f.h:f.w,h=swapped?f.w:f.h;return {x:f.x-w/2,y:f.y-h/2,w,h}};
  const objectBox=o=>({x:Math.min(o.x,o.x2),y:Math.min(o.y,o.y2),w:Math.abs(o.x2-o.x),h:Math.abs(o.y2-o.y)});
  const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
  for(const draft of project.drafts){
    const furniture=draft.furniture,blocks=draft.objects.filter(o=>['column','blocked','corridor','room'].includes(o.type)).map(objectBox);
    const rooms=draft.objects.filter(o=>o.type==='room'),zones=draft.objects.filter(o=>o.type==='zone'),corridors=draft.objects.filter(o=>o.type==='corridor');
    for(let i=0;i<rooms.length;i++){
      const room=rooms[i],r=objectBox(room),side=room.door?.side,doorY=side==='north'?r.y:side==='south'?r.y+r.h:r.y+r.h/2,doorX=side==='west'?r.x:side==='east'?r.x+r.w:r.x+r.w/2;
      assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=project.w&&r.y+r.h<=project.h,`${draft.label}: room outside site`);
      assert.ok(corridors.some(c=>{const q=objectBox(c);return side==='north'?doorX>=q.x&&doorX<=q.x+q.w&&Math.abs(doorY-(q.y+q.h))<=50:side==='south'?doorX>=q.x&&doorX<=q.x+q.w&&Math.abs(doorY-q.y)<=50:side==='west'?doorY>=q.y&&doorY<=q.y+q.h&&Math.abs(doorX-(q.x+q.w))<=50:side==='east'&&doorY>=q.y&&doorY<=q.y+q.h&&Math.abs(doorX-q.x)<=50}),`${draft.label}: room door not on corridor`);
      for(let j=i+1;j<rooms.length;j++)assert.ok(!overlap(r,objectBox(rooms[j])),`${draft.label}: room collision`);
      for(const fixed of draft.objects.filter(o=>['column','blocked','corridor'].includes(o.type)))assert.ok(!overlap(r,objectBox(fixed)),`${draft.label}: room overlaps fixed area`);
    }
    for(let i=0;i<zones.length;i++){
      const zone=zones[i],z=objectBox(zone),linked=furniture.filter(f=>f.zoneId===zone.id);
      assert.ok(z.x>=0&&z.y>=0&&z.x+z.w<=project.w&&z.y+z.h<=project.h,`${draft.label}: shared zone outside site`);
      assert.equal(linked.length,1,`${draft.label}: shared zone needs one demo furniture item`);
      assert.ok(corridors.some(c=>{const q=objectBox(c);return ((Math.abs(z.y-(q.y+q.h))<=50||Math.abs(z.y+z.h-q.y)<=50)&&z.x<q.x+q.w&&z.x+z.w>q.x)||((Math.abs(z.x-(q.x+q.w))<=50||Math.abs(z.x+z.w-q.x)<=50)&&z.y<q.y+q.h&&z.y+z.h>q.y)}),`${draft.label}: shared zone lacks corridor access`);
      for(const other of draft.objects.filter(o=>['column','blocked','corridor','room'].includes(o.type)))assert.ok(!overlap(z,objectBox(other)),`${draft.label}: shared zone overlaps fixed area or room`);
      for(let j=i+1;j<zones.length;j++)assert.ok(!overlap(z,objectBox(zones[j])),`${draft.label}: shared zones overlap`);
      for(const f of furniture){const b=box(f);if(f.zoneId===zone.id)assert.ok(b.x>=z.x&&b.y>=z.y&&b.x+b.w<=z.x+z.w&&b.y+b.h<=z.y+z.h,`${draft.label}: linked furniture outside zone`);else assert.ok(!overlap(z,b),`${draft.label}: unrelated furniture occupies shared zone`)}
    }
    for(let i=0;i<furniture.length;i++){
      const f=furniture[i],b=box(f);
      assert.ok(f.sku?.startsWith('DEMO-'),`${draft.label}: missing demo SKU`);
      assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=project.w&&b.y+b.h<=project.h,`${draft.label}: ${f.sku} outside site`);
      assert.ok(!blocks.some(x=>overlap(b,x)),`${draft.label}: ${f.sku} overlaps fixed zone or corridor`);
      for(let j=i+1;j<furniture.length;j++)assert.ok(!overlap(b,box(furniture[j])),`${draft.label}: furniture collision`);
    }
  }
}

(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser;
  try{
    browser=await chromium.launch({channel:process.env.MVP_BROWSER_CHANNEL||'msedge',headless:true});
    const patternsSeen=new Set();let shiftedAisleSeen=false;
    for(const [fixture,expected] of Object.entries(fixtures)){
      const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
      page.on('pageerror',e=>errors.push(e.message));
      await page.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
      await page.locator('#useExample').click();
      await page.locator('#simulationNeedsDetails summary').click();
      await page.locator('#simPeople').fill('40');
      await page.locator(`[data-simulation="${fixture}"]`).click();
      const original=await page.evaluate(()=>structuredClone(P));
      if(fixture==='compact'){
        const proposal=original.spaceProposals?.find(p=>p.kind==='office');
        assert.ok(proposal,'a constrained sample should offer a validated office-size adjustment');
        assert.ok(proposal.shortfallAfter<proposal.shortfallBefore&&proposal.savedArea>0);
        assert.equal(proposal.contract.mode,'suggest');
        assert.ok(proposal.to.capacity>=proposal.contract.minimumCapacity,'compact space must retain its minimum capacity');
        assert.equal(await page.evaluate(()=>{const old=P.broker;P.broker=normalizeBrokerBrief({...old,spaceSizing:{...old.spaceSizing,'base-office':{mode:'fixed'}}});const offers=buildSpaceProposals(P.drafts.find(d=>d.id===P.activeDraft));P.broker=old;return offers.some(p=>p.kind==='office')}),false,'a fixed-size requirement must not receive an adjustment proposal');
        assert.equal(await page.locator('#spaceProposals .space-proposal').count(),1);
        assert.equal(await page.evaluate(()=>document.querySelector('#spaceProposals').compareDocumentPosition(document.querySelector('#comparisonGrid'))&Node.DOCUMENT_POSITION_FOLLOWING?true:false),true,'adjustment choices should appear before the dense A/B/C cards');
        assert.match(await page.locator('.space-proposal-outcome').innerText(),/^\+\d+ /,'the default suggestion should lead with the gain');
        assert.match(await page.locator('#spaceProposals .space-proposal').innerText(),/Still needed:/);
        assert.equal(await page.locator('#spaceProposals .space-proposal details').evaluate(el=>el.open),false,'size and validation details start folded');
        await page.locator('#spaceProposals .space-proposal summary').click();
        const remainingNames=await page.evaluate(()=>{const proposal=P.spaceProposals.find(item=>item.status==='pending');return comparisonMeasures(proposal.draft.objects,proposal.draft.furniture,proposal.draft.meta).filter(row=>row.shortfall).map(shortfallPhrase)});
        const proposalDetails=await page.locator('#spaceProposals .space-proposal details').innerText();
        for(const need of remainingNames)assert.ok(proposalDetails.toLowerCase().includes(need.toLowerCase()),`expanded suggestion should list remaining ${need}`);
        await page.locator('#comparisonToggle').click();
        assert.equal(await page.locator('#spaceProposals').isVisible(),true,'adjustment choices stay visible while A/B/C details are folded');
        await page.locator('#comparisonToggle').click();
        await page.locator('[data-preview-proposal]').click();
        assert.equal(await page.locator('#spaceProposals .space-proposal details').evaluate(el=>el.open),true,'opening a preview should not close adjustment details');
        assert.equal(await page.locator('.space-proposal-preview svg').count(),2,'preview should compare both layouts');
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'preview must not apply the candidate');
        await page.locator('[data-dismiss-proposal]').click();
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'keeping the original must not change the plan');
        assert.equal(await page.evaluate(()=>P.spaceProposals[0].status),'dismissed');
        await page.evaluate(()=>undo());
        await page.locator('[data-accept-proposal]').click();
        assert.equal(await page.evaluate(()=>P.acceptedAdjustment?.requirementId),'base-office');
        assert.deepEqual(await page.evaluate(()=>P.broker.requirements.spaces),original.broker.requirements.spaces,'accepting a suggestion must not lower customer needs');
        assert.ok(await page.evaluate(()=>P.objects.some(o=>o.kind==='office'&&o.sizeVariant==='compact')));
        assert.equal(await page.locator('#checks .status.bad').count(),0);
        assert.ok(await page.evaluate(()=>comparisonMeasures(P.objects,P.furniture,P.drafts[0].meta).reduce((n,r)=>n+r.shortfall,0))<proposal.shortfallBefore);
        const adjustmentDownload=page.waitForEvent('download');
        await page.evaluate(()=>document.querySelector('#exportBtn').click());
        const adjustmentFile=await adjustmentDownload,imported=await browser.newPage();
        await imported.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
        await imported.locator('#fileInput').setInputFiles(await adjustmentFile.path());
        await imported.waitForFunction(()=>P?.acceptedAdjustment?.requirementId==='base-office');
        assert.equal(await imported.locator('#undoSpaceAdjustment').count(),1,'accepted choice must survive JSON export/import');
        await imported.close();
        await page.reload();
        assert.equal(await page.evaluate(()=>P.acceptedAdjustment?.requirementId),'base-office','accepted choice must survive local save and reload');
        assert.equal(await page.locator('#undoSpaceAdjustment').count(),1);
        page.once('dialog',dialog=>dialog.accept());
        await page.locator('#undoSpaceAdjustment').click();
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'restoring original must recover the A/B/C snapshot after reload');
        assert.equal(await page.evaluate(()=>P.acceptedAdjustment),null);
        const manualTarget=await page.evaluate(()=>{const proposal=P.spaceProposals.find(item=>item.status==='pending'&&item.kind==='office'),space=P.objects.find(item=>item.spaceKey===proposal?.spaceKey);return {spaceKey:proposal?.spaceKey,id:space?.id,width:proposal?.to.size.w,depth:proposal?.to.size.h}});
        assert.ok(manualTarget.spaceKey&&manualTarget.id,'the manual guide needs a stable proposal target');
        await page.locator(`[data-manual-proposal]`).first().click();
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'opening the manual guide must not apply a candidate layout');
        assert.deepEqual(await page.evaluate(()=>P.furniture),original.furniture,'opening the manual guide must not move furniture');
        assert.deepEqual(await page.evaluate(()=>P.broker),original.broker,'opening the manual guide must not change client needs');
        assert.equal(await page.evaluate(()=>selected),manualTarget.id,'the manual guide should select the proposed functional area');
        assert.equal(await page.locator('#manualSpaceGuide').isVisible(),true,'manual editing guidance should be visible beside the plan');
        assert.equal(await page.locator('#inspector [data-prop="x"]').count(),1,'the selected functional area should be open in the editor');
        await page.locator('#manualSpaceWidth').fill(String(manualTarget.width));
        await page.locator('#manualSpaceDepth').fill(String(manualTarget.depth));
        await page.locator('#manualSpaceApply').click();
        assert.equal(await page.evaluate(()=>currentPlanEdited()),true,'manually changing a space should mark the current plan as edited');
        assert.notDeepEqual(await page.evaluate(()=>P.objects),original.objects,'manual Apply should change the current plan, not the saved A/B/C snapshot');
        assert.deepEqual(await page.evaluate(()=>P.broker),original.broker,'manual edits must not lower the client brief');
        assert.equal(await page.locator('#comparisonCurrent').isVisible(),true,'an edited plan needs visible reassessment feedback');
        assert.equal(await page.locator('#undoBtn').isEnabled(),true,'the manual space edit must be undoable');
        await page.locator('#undoBtn').click();
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'Undo should restore the original functional-area geometry');
        assert.deepEqual(await page.evaluate(()=>P.furniture),original.furniture,'Undo should restore original furniture');
        await page.locator('#zoneAssistDetails > summary').click();
        await page.locator('#zoneAssistText').fill('缩小办公室，多排工位');
        await page.locator('#zoneAssistAsk').click();
        assert.equal(await page.locator('#zoneAssistResults .zone-assist-card').count()>0,true,'the demo conversation should produce a checked layout candidate');
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'asking for a layout idea must not alter current geometry');
        assert.deepEqual(await page.evaluate(()=>P.broker),original.broker,'a layout idea must not alter confirmed client needs');
        await page.locator('[data-zone-preview]').first().click();
        assert.equal(await page.locator('.zone-assist-preview svg').count(),2,'the option should preview before and after plans');
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'previewing an AI-style intention must not apply it');
        await page.locator('[data-zone-manual]').first().click();
        assert.equal(await page.evaluate(()=>selected===P.objects.find(item=>item.spaceKey===P.zoneAssist?.ideas?.[0]?.intent?.targetKey)?.id),true,'manual adjustment should focus the proposed area');
        await page.locator('[data-zone-apply]').first().click();
        assert.equal(await page.evaluate(()=>currentPlanEdited()),true,'only explicit Use should apply the checked candidate');
        assert.deepEqual(await page.evaluate(()=>P.broker),original.broker,'applying the candidate must preserve customer needs');
        assert.equal(await page.locator('#zoneAssistRestore').count(),1,'applied candidate should offer an original-plan restore');
        await page.locator('#undoBtn').click();
        assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'Undo should restore geometry after applying the assistant candidate');
        const noWindow=await page.evaluate(()=>mockZoneIntent('办公室靠窗',zoneAssistTargets(P.drafts.find(d=>d.id===P.activeDraft)),{entrance:true,window:false}));
        assert.match(noWindow.reply,/窗户/,'without a marked window, the assistant must ask for site information');
        assert.equal(noWindow.intents.length,0,'missing markers must not generate an adoptable intent');
        const followUp=await page.evaluate(()=>mockZoneIntent('再把它缩小一点',zoneAssistTargets(P.drafts.find(d=>d.id===P.activeDraft)),zoneAssistMarkers(),P.zoneAssistHistory.at(-1).targetKey));
        assert.equal(followUp.intents[0]?.targetKey,await page.evaluate(()=>P.zoneAssistHistory.at(-1).targetKey),'a follow-up should resolve the previously discussed zone');
        await page.locator('#zoneAssistSource').selectOption('api');
        assert.equal(await page.locator('#zoneAssistPin').isVisible(),true,'AI mode should show the server access code field');
        await page.locator('#zoneAssistSource').selectOption('mock');
        assert.equal(await page.locator('#zoneAssistPin').isVisible(),false,'demo mode must not pretend to call AI');
        await page.locator('#zoneAssistDetails > summary').click();
      }
      console.log(`${fixture} concept: ${original.objects.filter(o=>o.type==='room'&&o.kind==='meeting').length} meeting, ${original.objects.filter(o=>o.type==='room'&&o.kind==='office').length} office, ${original.objects.filter(o=>o.type==='room'&&o.kind==='pantry').length} pantry, ${original.drafts.find(d=>d.id===original.activeDraft)?.meta.seats||0} workstations`);
      console.log(`${fixture} alternatives: ${original.drafts.map(d=>`${d.layoutPattern} ${d.meta.seats}/${d.meta.requested} seats, ${d.meta.meetings} meeting, ${d.meta.offices} office, ${d.meta.pantries} pantry`).join(' | ')}`);
      console.log(`${fixture} aisle shifts: ${original.drafts.map(d=>`${d.layoutPattern} (${d.corridorShift?.x||0},${d.corridorShift?.y||0})`).join(' | ')}`);
      console.log(`${fixture} sampled routes: ${original.drafts.map(d=>`${d.layoutPattern} exit=${d.access?.exitConnected} rooms=${d.access?.unreachableRooms.length} zones=${d.access?.unreachableZones.length} islands=${d.access?.unreachableIslands.length}`).join(' | ')}`);
      shiftedAisleSeen ||= original.drafts.some(d=>d.corridorShift?.x||d.corridorShift?.y);
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>{const expected=layoutSkeleton(d.layoutPattern,d.corridorShift).corridors[0],actual=d.objects.find(o=>o.generated&&o.type==='corridor'&&o.kind==='main');return ['x','y','x2','y2'].every(key=>expected[key]===actual?.[key])})),true,'saved corridor geometry must match the selected adaptive offset');
      assert.deepEqual([original.w,original.h,original.objects.filter(o=>o.type==='column').length],expected);
      assert.equal(original.source.fixtureId,fixture);
      assert.equal(original.drafts.length,3);
      assert.equal(new Set(original.drafts.map(d=>d.layoutPattern)).size,3,'A/B/C should use different spatial patterns');
      original.drafts.forEach(d=>patternsSeen.add(d.layoutPattern));
      assert.equal(await page.locator('#comparisonPanel').isVisible(),true);
      assert.equal(await page.locator('.comparison-card').count(),3);
      assert.equal(await page.locator('.comparison-card svg').count(),3);
      assert.match(await page.locator('.comparison-card').first().innerText(),/Workstations/);
      if(fixture==='compact')assert.match(await page.locator('.comparison-card').first().innerText(),/Also short: 1 meeting room/,'the card should name a concrete gap, not only count unmet categories');
      assert.equal(await page.locator('.comparison-details').first().evaluate(el=>el.open),false,'detailed counts should start folded');
      await page.locator('.comparison-details summary').first().click();
      await page.evaluate(()=>render());
      assert.equal(await page.locator('.comparison-details').first().evaluate(el=>el.open),true,'open checks should survive a redraw');
      assert.match(await page.locator('.comparison-details').first().innerText(),/Compared with B:/);
      assert.match(await page.locator('.comparison-details').first().innerText(),/sampled/);
      if(fixture==='compact')assert.deepEqual(await page.evaluate(()=>{const sample={w:10000,h:6000,objects:[{type:'door',x:0,y:3000},{type:'exit',x:10000,y:3000}],furniture:[]},open=accessReview(sample).exitConnected;sample.objects.push({type:'blocked',x:4800,y:0,x2:5200,y2:6000});return {open,blocked:accessReview(sample).exitConnected}}),{open:true,blocked:false},'concept route screen must detect a full-width obstruction');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const sample={w:10000,h:6000,objects:[{id:'entrance',type:'door',x:0,y:3000},{id:'exit',type:'exit',x:10000,y:3000},{id:'barrier',type:'blocked',x:4800,y:0,x2:5200,y2:6000},{id:'room-east',type:'room',kind:'office',name:'East office',x:7000,y:700,x2:9200,y2:2200,door:{side:'north'}},{id:'zone-east',type:'zone',kind:'lounge',name:'East lounge',x:7000,y:2400,x2:9200,y2:3300}],furniture:workstationIsland('desk',2,8000,4700,'island-east')},result=accessReview(sample);return result.unreachableRoomIds.includes('room-east')&&result.unreachableZoneIds.includes('zone-east')&&result.unreachableIslands.includes('island-east')}),true,'disconnected rooms, zones and islands should retain target IDs for locating');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const desk=makeFurniture('desk',4000,2600),sample={w:8000,h:6000,rules:{main:1200,minor:900},objects:[{id:'test-main',type:'corridor',kind:'main',x:0,y:2000,x2:8000,y2:3200}],furniture:[]},clear=corridorBottlenecks(sample).length===0;sample.furniture.push(desk);const narrow=corridorBottlenecks(sample)[0];desk.y=4800;return clear&&narrow?.sourceIds.includes(desk.id)&&narrow.clearance<1200&&narrow.point.x>0&&corridorBottlenecks(sample).length===0}),true,'a desk in the marked aisle should cause a locatable planning-width warning that clears when moved');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const altered=structuredClone(P),x=altered.w/2;altered.objects.push({id:'test-route-barrier',type:'blocked',x:x-200,y:0,x2:x+200,y2:altered.h});return brokerAssessment(altered).rows.some(row=>row.name==='Concept walking route'&&row.status==='Shortfall')}),true,'a broken route should surface in the client assessment');
      const visibleCanvas=await page.locator('#canvas').boundingBox();
      assert.ok(visibleCanvas.y+visibleCanvas.height<=1001,'comparison should leave the editing canvas within the viewport');
      validateLayout(original);
      const roomRows=await page.evaluate(()=>brokerAssessment(P).rows.filter(r=>['Private offices','Pantry'].includes(r.name)||r.name.startsWith('Meeting rooms')));
      assert.equal(roomRows.length,3);
      if(fixture==='spacious')assert.ok(roomRows.every(r=>r.status==='Placed · concept'));
      assert.match(await page.locator('#drafts').innerText(),/Meeting rooms \d\/2/);
      assert.equal(await page.locator('#bom .item').count(),await page.evaluate(()=>new Set(allDisplayFurniture(P.furniture).map(f=>f.sku)).size));
      assert.equal(Number(await page.locator('#stats .metric').nth(4).locator('b').innerText()),await page.evaluate(()=>allDisplayFurniture(P.furniture).length));
      assert.match(await page.locator('#bom').innerText(),/DEMO-TASK-CHAIR/);
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.furniture.filter(f=>['bench2','cubicle','desk'].includes(f.kind)).every(f=>furnitureHasClearance(f,{...P,objects:d.objects,furniture:d.furniture})))),true,'generated workstations need usable chair space');
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.furniture.filter(f=>['desk','cubicle'].includes(f.kind)).every(f=>f.islandId&&[2,4,6,8].includes(f.islandSeats)&&islandSpacingValid(f,{...P,objects:d.objects,furniture:d.furniture})))),true,'generated workstations should belong to valid spaced islands');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>[4,6,8].every(size=>[0,90].every(turn=>{const members=workstationIsland('desk',size,6000,4500,`test-${size}-${turn}`,turn);return members.length===size&&new Set(members.map(f=>f.islandId)).size===1&&canPlaceIsland(members,{x0:0,y0:0,x1:P.w,y1:P.h},[],[])}))),true,'4/6/8-person island templates should fit in both directions on an empty compact site');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>[4,6,8].every(size=>[0,90].every(turn=>{const members=workstationIsland('cubicle',size,6000,4500,`private-${size}-${turn}`,turn);return canPlaceIsland(members,{x0:0,y0:0,x1:P.w,y1:P.h},[],[])}))),true,'private cubicle islands should retain outward access in both directions');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const first=P.furniture.find(f=>f.islandId),members=P.furniture.filter(f=>f.islandId===first.islandId),before=members.map(f=>({x:f.x,y:f.y})),box=islandEnvelope(members),shift=box.x+box.w+100<=P.w?100:-100;moveIslandMember(first,first.x+shift,first.y);const deltas=members.map((f,i)=>f.x-before[i].x),moved=deltas.every(dx=>dx===deltas[0])&&deltas[0]===shift;members.forEach((f,i)=>{f.x=before[i].x;f.y=before[i].y});return moved}),true,'moving one desk should move its whole island');
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.objects.filter(o=>o.type==='room'&&o.kind==='meeting').every(room=>meetingRoomFurniture(room).length===room.plannedSeats+1&&meetingRoomFurnitureValid(room,{...P,objects:d.objects,furniture:d.furniture})))),true,'each counted meeting room needs its table, chairs and clear entrance');
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.objects.filter(o=>o.type==='room'&&['office','pantry'].includes(o.kind)).every(room=>roomFurnitureValid(room,{...P,objects:d.objects,furniture:d.furniture})&&roomFurniture(room).length===(room.kind==='office'?2:4)))),true,'office and pantry concepts need their furnishings and clear entrances');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>['office','pantry'].every(kind=>['north','south','east','west'].every(side=>{const size=roomSpec(kind,0,side),room={id:`test-${kind}-${side}`,type:'room',kind,door:{side,width:900},x:1000,y:1000,x2:1000+size.w,y2:1000+size.h};return roomFurnitureValid(room,{w:30000,h:30000,objects:[],furniture:[]})}))),true,'office and pantry furniture should fit for each door side');
      if(fixture==='compact'){const compactFailures=await page.evaluate(()=>['meeting','office','pantry'].flatMap(kind=>['north','south','east','west'].filter(side=>{const seats=kind==='meeting'?6:0,size=roomSpec(kind,seats,side,'compact'),room={id:`compact-${kind}-${side}`,type:'room',kind,plannedSeats:seats,sizeVariant:'compact',door:{side,width:900},x:1000,y:1000,x2:1000+size.w,y2:1000+size.h};return !roomFurnitureValid(room,{w:30000,h:30000,objects:[],furniture:[]})}).map(side=>`${kind}/${side}`)));assert.deepEqual(compactFailures,[],'meeting, office and pantry compact templates should retain fitted furniture in each orientation')}
      if(fixture==='compact')assert.equal(await page.evaluate(()=>Object.entries(extraRoomSpecs).every(([kind,spec])=>['north','south','east','west'].every(side=>{const seats=kind==='meeting'?6:kind==='huddle'?4:kind==='training'?8:spec.capacity,size=roomSpec(kind,seats,side),room={id:`extra-${kind}-${side}`,type:'room',kind,extraKind:kind,plannedSeats:seats,door:{side,width:900},x:1000,y:1000,x2:1000+size.w,y2:1000+size.h};return roomFurniture(room).length>0&&roomFurnitureValid(room,{w:30000,h:30000,objects:[],furniture:[]})}))),true,'every additional space needs fitted furniture for all four door directions');
      if(original.objects.some(o=>o.type==='room'&&o.kind==='pantry'))assert.match(await page.locator('#bom').innerText(),/Pantry counter.*2-seat pantry table.*Dining chair/s);
      if(original.objects.some(o=>o.type==='room'&&o.kind==='meeting'))assert.match(await page.locator('#bom').innerText(),/Meeting chair/);
      assert.equal(await page.evaluate(()=>allDisplayFurniture(P.furniture).filter(f=>f.kind==='meetingChair').length),original.objects.filter(o=>o.type==='room'&&o.kind==='meeting').reduce((n,room)=>n+room.plannedSeats,0));
      if(fixture==='compact')assert.equal(await page.evaluate(()=>[6,8,12].every(seats=>['north','south','east','west'].every(side=>{const size=roomSpec('meeting',seats,side),room={id:`test-${seats}-${side}`,type:'room',kind:'meeting',plannedSeats:seats,door:{side,width:900},x:1000,y:1000,x2:1000+size.w,y2:1000+size.h},project={w:30000,h:30000,objects:[],furniture:[]};return meetingRoomFurniture(room).length===seats+1&&meetingRoomFurnitureValid(room,project)}))),true,'mixed capacities and door sides should fit the generated table and chairs');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const project=structuredClone(P),room=project.objects.find(o=>o.type==='room'&&o.kind==='meeting');room.x2=room.x+3300;return !meetingRoomFurnitureValid(room,project)&&brokerAssessment(project).rows.find(row=>row.name.startsWith('Meeting rooms')).status==='Shortfall'}),true,'an undersized edited meeting room must not count as furnished capacity');
      assert.equal(await page.evaluate(()=>{const desk=P.furniture.find(f=>['bench2','cubicle','desk'].includes(f.kind)),chair=chairItems(desk)[0];return hit(chair.x,chair.y)?.id===desk.id}),true,'selecting a linked chair should select its desk');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const a=makeFurniture('bench2',5000,5000),b=makeFurniture('bench2',5000,7300),example={w:12000,h:12000,objects:[],furniture:[a,b]};return !overlap(furnitureRect(a),furnitureRect(b))&&!furnitureHasClearance(a,example)}),true,'chair-use conflict must fail even when desks do not collide');
      assert.equal(await page.locator('#checks .status.bad').count(),0);
      if(fixture==='compact'){
        await page.evaluate(()=>{window.routeRestore=structuredClone(P);const x=P.w/2;P.objects.push({id:'test-route-barrier',type:'blocked',x:x-200,y:0,x2:x+200,y2:P.h});save()});
        const routeAction=page.locator('#routeAlerts button.issue-action').filter({hasText:'No sampled open-floor route'});
        assert.equal(await routeAction.count(),1,'broken route should offer a location action');
        await routeAction.click();
        assert.equal(await page.evaluate(()=>view==='2d'&&focusedIssue?.key==='route-exit'&&focusedIssue.targetIds.every(targetId=>!!find(targetId))&&issueTargetBoxes(focusedIssue.targetIds).length>=2),true,'route action should locate and highlight the entrance and exit');
        assert.equal(await page.locator('#hint.issue-guidance').isVisible(),true,'the default customer view should explain the highlighted issue');
        await page.evaluate(()=>{P=window.routeRestore;delete window.routeRestore;save();fit()});
        assert.equal(await page.locator('#routeAlerts button.issue-action').filter({hasText:'No sampled open-floor route'}).count(),0,'route warning should clear after the blocking edit is removed');
        assert.equal(await page.evaluate(()=>focusedIssue),null,'resolved issue highlight should clear');
        assert.equal(await page.locator('#hint.issue-guidance').count(),0,'resolved issue guidance should clear');
        await page.evaluate(()=>{window.aisleRestore=structuredClone(P);const aisle=P.objects.find(o=>o.type==='corridor'&&o.kind==='main'),box=rect(aisle),desk=makeFurniture('desk',box.x+box.w/2,box.y+box.h/2);window.aisleTestDesk=desk.id;P.furniture.push(desk);save()});
        const aisleAction=page.locator('#routeAlerts button.issue-action').filter({hasText:'aisle narrows'});
        assert.equal(await aisleAction.count(),1,'a narrowed aisle should be visible in the default customer view');
        await aisleAction.click();
        assert.equal(await page.evaluate(()=>focusedIssue?.key.startsWith('aisle-')&&focusedIssue.targetIds.includes(window.aisleTestDesk)&&!!focusedIssue.point),true,'aisle warning should highlight the intruding desk and pinch point');
        assert.equal(await page.locator('#editGuide').isVisible(),true,'clicking a warning should show guided editing');
        assert.equal(await page.locator('#editGuideUndo').isDisabled(),true,'undo should wait for a guided change');
        await page.locator('#fitBtn').click();
        const dragCanvas=await page.locator('#canvas').boundingBox(),dragPoints=await page.evaluate(()=>{const desk=P.furniture.find(f=>f.id===window.aisleTestDesk);return [screen(desk.x,desk.y),screen(desk.x,desk.y+2300)]});
        await page.mouse.move(dragCanvas.x+dragPoints[0][0],dragCanvas.y+dragPoints[0][1]);await page.mouse.down();
        await page.mouse.move(dragCanvas.x+dragPoints[1][0],dragCanvas.y+dragPoints[1][1],{steps:6});await page.mouse.up();
        assert.equal(await page.locator('#routeAlerts button.issue-action').filter({hasText:'aisle narrows'}).count(),0,'aisle warning should clear after dragging the desk out');
        assert.match(await page.locator('#editGuideTitle').innerText(),/Issue cleared/);
        assert.equal(await page.locator('#editGuideUndo').isEnabled(),true,'guided undo should be available after a move');
        await page.locator('#editGuideUndo').click();
        assert.equal(await aisleAction.count(),1,'undo should restore the prior warning');
        await page.evaluate(()=>{P=window.aisleRestore;selected=null;delete window.aisleRestore;delete window.aisleTestDesk;save();fit()});
        await page.locator('#editGuideClose').click();
        assert.equal(await page.locator('#editGuide').isVisible(),false,'guide should close without changing A / B / C');
      }
      await page.locator('[data-view="3d"]').click();
      await page.locator('[data-view="2d"]').click();
      assert.deepEqual(errors,[]);
      if(fixture==='spacious'){
        await page.locator('#advancedToggle').click();
        await page.locator('[data-tool="officeRoom"]').click();
        const canvas=await page.locator('#canvas').boundingBox();
        const points=await page.evaluate(()=>[screen(1500,1000),screen(4500,4000)]);
        await page.mouse.move(canvas.x+points[0][0],canvas.y+points[0][1]);await page.mouse.down();
        await page.mouse.move(canvas.x+points[1][0],canvas.y+points[1][1],{steps:5});await page.mouse.up();
        assert.equal(await page.evaluate(()=>P.objects.filter(o=>o.type==='room'&&!o.generated).length),1);
        assert.equal(await page.locator('#roomDoorSide').count(),1);
        await page.evaluate(()=>undo());
      }
      if(fixture==='balanced'){
        await page.locator('.comparison-card').nth(1).click();
        assert.equal(await page.evaluate(()=>P.activeDraft===P.drafts[1].id),true,'comparison selection should change the active plan');
        assert.equal(await page.locator('.comparison-card.active').count(),1);
        await page.locator('.comparison-card').first().click();
        await page.locator('#comparisonToggle').click();
        await page.locator('#fitBtn').click();
        const drag=await page.evaluate(()=>{const f=P.furniture.find(item=>['bench2','desk','cubicle'].includes(item.kind));return {from:screen(f.x,f.y),to:screen(f.x,P.h/2),id:f.id,chairY:chairItems(f)[0].y,validSeats:workstationSeatsForAssessment(P)}});
        const canvas=await page.locator('#canvas').boundingBox();
        await page.mouse.move(canvas.x+drag.from[0],canvas.y+drag.from[1]);
        await page.mouse.down();
        await page.mouse.move(canvas.x+drag.to[0],canvas.y+drag.to[1],{steps:5});
        await page.mouse.up();
        await page.locator('#comparisonToggle').click();
        assert.match(await page.locator('#comparisonCurrent').innerText(),/Current edited plan/);
        assert.equal(await page.evaluate(id=>P.furniture.find(f=>f.id===id)?.y!==undefined,drag.id),true);
        assert.notEqual(await page.evaluate(id=>chairItems(P.furniture.find(f=>f.id===id))[0].y,drag.id),drag.chairY,'the linked chair should follow its desk');
        assert.ok(await page.evaluate(()=>workstationSeatsForAssessment(P))<drag.validSeats,'blocked chair clearance should reduce assessed seats');
        assert.ok((await page.evaluate(()=>checks())).some(i=>i.level==='bad'&&/corridor/.test(i.text)),'manual drag should flag a blocked corridor');
        assert.equal(Number(await page.locator('#stats .metric').nth(4).locator('b').innerText()),await page.evaluate(()=>allDisplayFurniture(P.furniture).length));
        await page.evaluate(()=>undo());
        assert.equal(await page.locator('#comparisonCurrent').isVisible(),false);
        assert.deepEqual(await page.evaluate(()=>P.furniture.map(f=>[f.sku,f.x,f.y])),original.furniture.map(f=>[f.sku,f.x,f.y]));
      }
      // Export the selected scheme and import into a new browser tab.
      const downloadPromise=page.waitForEvent('download');
      await page.evaluate(()=>document.querySelector('#exportBtn').click());
      const download=await downloadPromise,second=await browser.newPage();
      second.on('pageerror',e=>errors.push(e.message));
      await second.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
      await second.locator('#fileInput').setInputFiles(await download.path());
      await second.waitForFunction(id=>P?.source?.fixtureId===id,fixture);
      assert.deepEqual(await second.evaluate(()=>({source:P.source,furniture:P.furniture.map(f=>[f.sku,f.x,f.y]),drafts:P.drafts.length})),{source:original.source,furniture:original.furniture.map(f=>[f.sku,f.x,f.y]),drafts:3});
      assert.deepEqual(errors,[]);
      console.log(`PASS ${fixture}: 3 schemes, geometry, BOM, 3D and export/import`);
      await second.close();await page.close();
    }
    assert.deepEqual([...patternsSeen].sort(),['core','neighborhood','perimeter','spine'],'sample spaces should exercise every representative pattern');
    assert.equal(shiftedAisleSeen,true,'at least one sample concept should select a moved aisle');
    const narrow=await browser.newPage({viewport:{width:700,height:900}});
    await narrow.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await narrow.locator('#useExample').click();
    await narrow.locator('[data-simulation="balanced"]').click();
    assert.equal(await narrow.locator('.comparison-card').count(),3,'comparison stays available on a narrow screen');
    assert.ok(await narrow.evaluate(()=>document.body.scrollWidth<=innerWidth+1),'narrow comparison should scroll inside its panel');
    await narrow.close();
    const mobile=await browser.newPage({viewport:{width:390,height:844}});
    await mobile.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await mobile.locator('#useExample').click();
    await mobile.locator('[data-simulation="compact"]').click();
    assert.equal(await mobile.locator('#mobilePlanSelect').isVisible(),true,'phone layout choice should be explicit');
    assert.equal(await mobile.locator('.comparison-item:visible').count(),1,'phone should initially show only the current layout summary');
    assert.ok(await mobile.evaluate(()=>document.body.scrollWidth<=innerWidth+1),'layout choices should fit the phone width');
    const firstFoldCanvas=await mobile.locator('#canvas').boundingBox();
    assert.ok(firstFoldCanvas.y<530&&Math.min(firstFoldCanvas.y+firstFoldCanvas.height,844)-firstFoldCanvas.y>220,'the editing canvas should be clearly visible in the first phone viewport');
    assert.equal(await mobile.locator('#zoneAssistDetails').evaluate(el=>el.open),false,'phone layout assistant should not take over the first viewport');
    await mobile.locator('#zoneAssistDetails > summary').click();
    assert.equal(await mobile.locator('#zoneAssistText').isVisible(),true,'phone users can still open the layout request field');
    assert.ok(await mobile.evaluate(()=>document.body.scrollWidth<=innerWidth+1),'assistant controls should not overflow the phone width');
    await mobile.locator('#zoneAssistDetails > summary').click();
    assert.equal(await mobile.locator('#proposalDisclosure').isVisible(),true,'space adjustment feedback should remain discoverable on a phone');
    assert.equal(await mobile.locator('#proposalDisclosure').evaluate(el=>el.open),false,'space adjustment details should start folded on a phone');
    await mobile.locator('#proposalDisclosure > summary').click();
    assert.equal(await mobile.locator('#spaceProposals .space-proposal').first().isVisible(),true,'phone users should be able to open adjustment feedback');
    assert.equal(await mobile.locator('#spaceProposals [data-manual-proposal]').first().isVisible(),true,'the manual route should be discoverable beside the compact suggestion on a phone');
    const mobileBefore=await mobile.evaluate(()=>({objects:structuredClone(P.objects),furniture:structuredClone(P.furniture)}));
    await mobile.locator('#spaceProposals [data-manual-proposal]').first().click();
    assert.equal(await mobile.locator('#manualSpaceGuide').isVisible(),true,'phone users should be able to open manual functional-area guidance');
    assert.deepEqual(await mobile.evaluate(()=>({objects:P.objects,furniture:P.furniture})),mobileBefore,'entering the phone guide must not alter the plan');
    await mobile.locator('#manualSpaceClose').click();
    await mobile.locator('#proposalDisclosure > summary').click();
    await mobile.locator('#mobilePlanSelect').selectOption({index:1});
    assert.equal(await mobile.evaluate(()=>P.activeDraft===P.drafts[1].id),true,'phone layout choice should switch the plan');
    assert.equal(await mobile.locator('.comparison-item:visible').count(),1);
    await mobile.locator('#mobileCompareToggle').click();
    assert.equal(await mobile.locator('.comparison-item:visible').count(),3,'phone comparison should reveal all three layouts on demand');
    await mobile.locator('#mobileCompareToggle').click();
    await mobile.evaluate(()=>{P.drafts=[];P.activeDraft=null;P.spaceProposals=[];P.objects=P.objects.filter(o=>o.type!=='door'&&o.type!=='exit');render()});
    assert.equal(await mobile.locator('[data-setup-tool="door"]').isVisible(),true,'entrance placement should remain available on a phone');
    assert.equal(await mobile.locator('[data-setup-tool="exit"]').isVisible(),true,'exit placement should remain available on a phone');
    assert.ok(await mobile.locator('#setupBar').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'setup actions should fit the phone width');
    assert.equal(await mobile.locator('#comparisonPanel').evaluate(el=>getComputedStyle(el).maxHeight),'none','phone comparisons should use the page scroll, not a small nested scroll area');
    await mobile.locator('[data-setup-tool="door"]').click();
    assert.equal(await mobile.locator('[data-setup-tool="door"]').getAttribute('aria-pressed'),'true');
    assert.match(await mobile.locator('#hint').innerText(),/Entrance selected/);
    await mobile.close();
    const intakeMobile=await browser.newPage({viewport:{width:390,height:844}});
    await intakeMobile.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await intakeMobile.locator('#startProject').click();
    assert.equal(await intakeMobile.locator('#naturalBrief').isVisible(),true);
    assert.equal(await intakeMobile.locator('.top').evaluate(el=>getComputedStyle(el).visibility),'hidden','Step 1 should not compete with the underlying plan controls');
    assert.equal(await intakeMobile.locator('#setupBar').evaluate(el=>getComputedStyle(el).visibility),'hidden','Step 1 should not show a conflicting background step');
    await intakeMobile.locator('#naturalBriefManual').click();
    assert.equal(await intakeMobile.locator('#brokerIntake').isVisible(),true);
    assert.equal(await intakeMobile.locator('.top').evaluate(el=>getComputedStyle(el).visibility),'hidden','need review should also hide the background controls');
    await intakeMobile.close();
    const shared=await browser.newPage();
    await shared.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await shared.locator('#useExample').click();
    await shared.locator('#simulationNeedsDetails summary').click();
    await shared.locator('#simPeople').fill('16');
    await shared.locator('#simOffices').fill('0');
    await shared.locator('#simMeetingRooms').fill('1');
    await shared.locator('#simPantry').uncheck();
    await shared.locator('#simDiningSeats').fill('4');
    await shared.locator('#simLoungeSeats').fill('2');
    await shared.locator('#simCoffeeBar').check();
    await shared.locator('#simReception').check();
    await shared.locator('[data-simulation="spacious"]').click();
    const sharedProject=await shared.evaluate(()=>structuredClone(P));
    const sharedState={brief:sharedProject.broker,zones:sharedProject.drafts.map(d=>({pattern:d.layoutPattern,zones:d.objects.filter(o=>o.type==='zone').map(z=>z.kind),meta:d.meta})),rows:await shared.evaluate(()=>brokerAssessment(P).rows)};
    console.log('shared-use scenario',sharedState.zones.map(d=>`${d.pattern}: ${d.zones.join(',')}`).join(' | '));
    const sharedVariants=await shared.evaluate(()=>{const base=P.drafts.find(d=>d.id===P.activeDraft);return base.objects.filter(o=>o.type==='zone').map(o=>{const alternate=conceptAtShift(base.layoutPattern,base.meta.requested,P.broker.meetingRooms*P.broker.roomSeats,P.broker.phones,base.stationStyle,base.corridorShift,{compactSpaceKey:o.spaceKey}),changed=alternate.objects.find(z=>z.spaceKey===o.spaceKey),project={...P,objects:alternate.objects,furniture:alternate.furniture,drafts:[alternate]};return {kind:o.kind,compact:changed?.sizeVariant==='compact',smaller:!!changed&&rect(changed).w*rect(changed).h<rect(o).w*rect(o).h,valid:!!changed&&validSharedZone(changed,alternate.objects,alternate.furniture)&&validZoneForAssessment(changed,project),sameCapacity:changed?.capacity===o.capacity}})});
    assert.deepEqual(sharedVariants.map(v=>v.kind).sort(),['coffee','dining','lounge','reception']);
    assert.ok(sharedVariants.every(v=>v.compact&&v.smaller&&v.valid&&v.sameCapacity),'multiple shared-use types must have furnished compact variants without reducing capacity');
    assert.equal(sharedState.brief.diningSeats,4);
    for(const draft of sharedState.zones)assert.deepEqual([...draft.zones].sort(),['coffee','dining','lounge','reception']);
    for(const name of ['Dining seats','Lounge seats','Coffee bar','Reception'])assert.equal(sharedState.rows.find(r=>r.name===name)?.status,'Placed · concept',`${name} should be a valid concept placement`);
    assert.equal(await shared.evaluate(()=>allDisplayFurniture(P.furniture).filter(f=>f.kind==='barStool').length),2,'coffee bar needs its two linked stools');
    validateLayout(sharedProject);
    assert.equal(await shared.locator('#checks .status.bad').count(),0);
    await shared.locator('.comparison-details summary').first().click();
    assert.match(await shared.locator('.comparison-details').first().innerText(),/Dining seats/);
    assert.match(await shared.locator('#roomSchedule').innerText(),/Coffee bar/);
    const extras=await shared.evaluate(()=>{const previous=P.broker,results=[];for(const [kind,spec] of Object.entries(extraRoomSpecs)){const seats=kind==='meeting'?6:kind==='huddle'||kind==='video'?4:kind==='training'?8:spec.capacity;P.broker=normalizeBrokerBrief({...brokerDefaults(),people:0,meetingRooms:0,offices:0,pantry:false,extraSpaces:[{id:`extra-${kind}`,kind,count:1,seats,priority:'must'}]});const draft=concept('spine',0,0,0,'hybrid'),project={...P,objects:draft.objects,furniture:draft.furniture,drafts:[draft],broker:P.broker},room=draft.objects.find(o=>o.requirementId===`extra-${kind}`),row=brokerAssessment(project).rows.find(r=>r.name.startsWith(extraSpaceKinds[kind]));results.push({kind,placed:!!room,furnished:!!room&&roomFurniture(room).length>0&&roomFurnitureValid(room,project),status:row?.status})}P.broker=previous;return results});
    assert.equal(extras.length,15);
    for(const result of extras)assert.deepEqual(result,{kind:result.kind,placed:true,furnished:true,status:'Placed · concept'},`${result.kind} should be furnished, placed and assessed`);
    assert.equal(await shared.evaluate(()=>{const previous=P.broker;P.broker=normalizeBrokerBrief({...brokerDefaults(),people:0,meetingRooms:0,offices:0,pantry:false,extraSpaces:[{id:'oversize',kind:'huddle',count:1,seats:7,priority:'must'}]});const draft=concept('spine',0,0,0,'hybrid'),row=brokerAssessment({...P,objects:draft.objects,furniture:draft.furniture,drafts:[draft],broker:P.broker}).rows.find(r=>r.name.startsWith('Huddle room'));P.broker=previous;return row.status==='Shortfall'&&!draft.objects.some(o=>o.requirementId==='oversize')}),true,'over-capacity spaces must not be reported as placed');
    await shared.close();
    const cramped=await browser.newPage();
    await cramped.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await cramped.locator('#useExample').click();
    await cramped.locator('#simulationNeedsDetails summary').click();
    await cramped.locator('#simDiningSeats').fill('40');
    await cramped.locator('#simLoungeSeats').fill('20');
    await cramped.locator('#simCoffeeBar').check();
    await cramped.locator('#simReception').check();
    await cramped.locator('[data-simulation="compact"]').click();
    const amenityRows=await cramped.evaluate(()=>brokerAssessment(P).rows.filter(r=>['Dining seats','Lounge seats','Coffee bar','Reception'].includes(r.name)));
    assert.ok(amenityRows.some(r=>r.status==='Shortfall'),'over-demanded shared uses must show a shortfall');
    assert.match(await cramped.locator('#quickAssessment').innerText(),/Not a fit yet/);
    await cramped.close();
    const overflow=await browser.newPage();
    await overflow.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await overflow.locator('#useExample').click();
    await overflow.locator('#simulationNeedsDetails summary').click();
    await overflow.locator('#simPeople').fill('120');
    await overflow.locator('[data-simulation="compact"]').click();
    assert.deepEqual(await overflow.evaluate(()=>[P.w,P.h]),[12000,9000]);
    assert.ok(await overflow.evaluate(()=>P.drafts.every(d=>d.meta.seats<d.meta.requested)),'oversubscribed site must report a workstation gap');
    assert.match(await overflow.locator('#quickAssessment').innerText(),/Not a fit yet/);
    console.log('PASS compact over-demand: fixed geometry and visible capacity shortfall');
    await overflow.close();
    const regenerate=await browser.newPage();
    await regenerate.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await regenerate.locator('#useExample').click();
    await regenerate.locator('[data-simulation="spacious"]').click();
    const counts=await regenerate.evaluate(()=>{const result=()=>P.drafts.map(d=>({pattern:d.layoutPattern,rooms:d.objects.filter(o=>o.type==='room').length,corridors:d.objects.filter(o=>o.type==='corridor').length}));const first=result();generateDrafts();const second=result();generateDrafts();return [first,second,result()]});
    assert.deepEqual(counts[1],counts[0],'regenerating must not duplicate generated rooms or corridors');
    assert.deepEqual(counts[2],counts[0],'repeated regeneration must remain stable');
    console.log('PASS regenerate: conceptual rooms are not duplicated');
    await regenerate.close();
    const roles=await browser.newPage();
    await roles.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await roles.locator('#startProject').click();
    await roles.locator('#naturalBriefText').fill('需要24个工位、1间总经理室和2间总监办公室、2间6人会议室、前台。总经理室优先靠窗。');
    await roles.locator('#naturalBriefExtract').click();
    assert.equal(await roles.locator('#officeExecutive').inputValue(),'1');
    assert.equal(await roles.locator('#officeDirector').inputValue(),'2');
    await roles.locator('#reviewEdit').click();
    await roles.locator('#broker-offices').fill('2');
    await roles.locator('#brokerForm button.primary').click();
    assert.match(await roles.locator('#officeRoleError').innerText(),/must fit within the total/);
    await roles.locator('#broker-offices').fill('3');
    await roles.locator('#brokerForm button.primary').click();
    await roles.locator('[data-simulation="spacious"]').click();
    const roleProject=await roles.evaluate(()=>structuredClone(P));
    assert.equal(roleProject.broker.offices,3);
    assert.equal(roleProject.broker.officeRoles.executive,1);
    assert.equal(roleProject.broker.relations[0].rule,'window');
    assert.ok(roleProject.objects.some(o=>o.type==='room'&&o.role==='executive'&&o.name==='Executive office'));
    assert.equal(roleProject.objects.filter(o=>o.type==='room'&&o.role==='director').length,2);
    assert.ok(await roles.evaluate(()=>placementScore('reception',{x:1200,y:8000})>placementScore('reception',{x:22000,y:8000})),'reception candidates should prefer the marked entrance');
    assert.ok(await roles.evaluate(()=>placementScore('office',{x:4500,y:1200},'executive')>placementScore('office',{x:4500,y:14500},'executive')),'stated executive-office window preference should affect placement ranking');
    await roles.locator('.comparison-details summary').first().click();
    assert.match(await roles.locator('.comparison-details').first().innerText(),/Executive office near windows/);
    assert.match(await roles.locator('.comparison-details').first().innerText(),/Within MVP distance|Misses MVP distance/);
    validateLayout(roleProject);
    await roles.locator('#brokerResult').click();
    assert.match(await roles.locator('#brokerReportContent').innerText(),/Executive offices/);
    assert.match(await roles.locator('#brokerReportContent').innerText(),/MVP straight-line concept screens/);
    assert.ok(await roles.evaluate(()=>brokerAssessment(P).rows.some(r=>r.name.startsWith('Spatial relation · executive office')&&r.actual.includes('straight-line')&&r.status!=='Not assessed')));
    assert.match(await roles.locator('#brokerReportContent').innerText(),/System suggestion · reception near entrance/);
    assert.match(await roles.locator('#brokerReportContent').innerText(),/workstations toward daylight/);
    await roles.locator('#brokerReportClose').click();
    await roles.evaluate(()=>{const room=P.objects.find(o=>o.type==='room'&&o.role==='executive');room.x+=6000;room.x2+=6000;save()});
    assert.equal(await roles.evaluate(()=>currentPlanEdited(P)),true);
    assert.equal(await roles.evaluate(()=>P.draftsStale),false,'editing a concept room should recheck the working plan without invalidating the site');
    await roles.locator('#comparisonCurrent summary').click();
    assert.match(await roles.locator('#comparisonCurrent').innerText(),/Current edited plan[\s\S]*Location checks:.*Executive office near windows/);
    assert.match(await roles.locator('#comparisonGrid .comparison-card.active').innerText(),/Original snapshot/);
    roles.once('dialog',dialog=>dialog.dismiss());
    await roles.locator('#comparisonGrid .comparison-card.active').click();
    assert.equal(await roles.evaluate(()=>currentPlanEdited(P)),true,'canceling snapshot replacement must keep the edited plan');
    await roles.locator('#brokerResult').click();
    assert.match(await roles.locator('#brokerReportContent').innerText(),/Assessment of the current edited plan/);
    assert.equal(await roles.evaluate(()=>brokerAssessment(P).placement[0].status),'fail');
    await roles.locator('#brokerReportClose').click();
    await roles.locator('#advancedToggle').click();
    await roles.evaluate(()=>{selected=P.objects.find(o=>o.type==='window').id;render()});
    const windowX=Number(await roles.locator('#inspector [data-prop="x"]').inputValue());
    await roles.locator('#comparisonToggle').click();
    await roles.locator('#inspector [data-prop="x"]').fill(String(windowX+100));
    await roles.locator('#inspector [data-prop="x"]').dispatchEvent('change');
    assert.equal(await roles.evaluate(()=>P.draftsStale),true,'moving a site window must invalidate generated snapshots');
    assert.equal(await roles.locator('#comparisonGrid .comparison-card').count(),0,'outdated A/B/C results must be hidden');
    assert.equal(await roles.locator('#comparisonCurrent').isVisible(),true,'stale warning must remain visible when the comparison is folded');
    assert.equal(await roles.locator('#drafts [data-draft]').count(),0,'outdated sidebar summaries must be hidden');
    assert.match(await roles.locator('#comparisonCurrent').innerText(),/out of date/);
    await roles.evaluate(()=>generateDrafts());
    assert.equal(await roles.evaluate(()=>P.draftsStale),false);
    assert.equal(await roles.locator('#comparisonGrid .comparison-card').count(),3,'regeneration should restore current A/B/C comparisons');
    await roles.close();
    const checklist=await browser.newPage();
    await checklist.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await checklist.locator('#startProject').click();
    await checklist.locator('#naturalBriefText').fill('We need 24 workstations and two 6-person meeting rooms for our office team.');
    await checklist.locator('#naturalBriefExtract').click();
    assert.equal(await checklist.locator('#extractedAnswers [data-suggested-zone]').count(),4);
    assert.equal(await checklist.evaluate(()=>simulationDraft),null);
    await checklist.locator('#extractedAnswers .review-suggestions summary').click();
    await checklist.locator('#extractedAnswers .review-checklist > summary').click();
    await checklist.locator('#extractedAnswers [data-suggested-zone="reception"]').selectOption('accepted');
    await checklist.locator('#extractedAnswers [data-suggested-zone="pantry"]').selectOption('uncertain');
    await checklist.locator('#extractedAnswers [data-suggested-zone="waiting"]').selectOption('removed');
    await checklist.locator('#extractedAnswers [data-answer="diningSeats"]').selectOption('requested');
    await checklist.locator('#extractedAnswers [data-answer-count="diningSeats"]').fill('6');
    await checklist.locator('#extractedAnswers [data-checklist="teamZones"]').selectOption('requested');
    await checklist.locator('#extractedAnswers [data-checklist-note="teamZones"]').fill('Sales 8 together');
    await checklist.locator('#extractedAnswers [data-suggested-zone="quietWork"]').selectOption('uncertain');
    await checklist.locator('#extractedAnswers .checklist-block details summary').click();
    await checklist.locator('#extractedAnswers [data-checklist="budget"]').selectOption('requested');
    await checklist.locator('#extractedAnswers [data-checklist-note="budget"]').fill('Budget to be confirmed');
    assert.equal(await checklist.locator('#brokerForm button.primary').isDisabled(),false);
    await checklist.locator('#brokerForm button.primary').click();
    assert.equal(await checklist.evaluate(()=>simulationDraft.reception),true);
    assert.equal(await checklist.evaluate(()=>simulationDraft.intakeAnswers.pantry),'uncertain');
    assert.equal(await checklist.evaluate(()=>simulationDraft.suggestedZones.waiting),'removed');
    assert.equal(await checklist.evaluate(()=>simulationDraft.completeness.waiting.state),'not-needed');
    assert.equal(await checklist.evaluate(()=>simulationDraft.requirements.spaces.some(space=>space.kind==='waiting')),false);
    assert.equal(await checklist.evaluate(()=>simulationDraft.diningSeats),6);
    assert.equal(await checklist.evaluate(()=>simulationDraft.completeness.teamZones.note),'Sales 8 together');
    assert.equal(await checklist.evaluate(()=>simulationDraft.completeness.quietWork.state),'uncertain');
    assert.equal(await checklist.evaluate(()=>simulationDraft.requirements.completeness.budget.state),'requested');
    await checklist.locator('[data-simulation="spacious"]').click();
    assert.equal(await checklist.evaluate(()=>P.broker.completeness.teamZones.state),'requested');
    await checklist.locator('#brokerResult').click();
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/Additional need · Teams need distinct work areas/);
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/Customer is not sure yet: Pantry/);
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/System suggestions accepted: Reception · Removed: Visitor waiting area/);
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/Recorded only · not auto-placed or verified/);
    await checklist.close();
    const areas=await browser.newPage();
    await areas.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await areas.locator('#useExample').click();
    await areas.locator('[data-simulation="spacious"]').click();
    const areaResult=await areas.evaluate(()=>{
      P.broker=normalizeBrokerBrief({...P.broker,workAreas:[{id:'research',name:'Research',activity:'focus',targetDesks:6,minimumDesks:2,priority:'must'},{id:'sales',name:'Sales',activity:'calls',targetDesks:4,minimumDesks:2,priority:'must'}],relations:[{id:'research-sales',fromId:'research',toId:'sales',rule:'near',priority:'must'}]});
      generateDrafts();
      const draft=P.drafts[0],project={...P,objects:draft.objects,furniture:draft.furniture,workAreas:draft.workAreas},rows=comparisonMeasures(draft.objects,draft.furniture,draft.meta,draft.workAreas);
      const named=draft.workAreas.filter(area=>!area.generic),deskItems=draft.furniture.filter(f=>['desk','cubicle','bench2'].includes(f.kind)),before=workAreaSeatsForAssessment(project,'research'),shifted=structuredClone(project);
      shifted.workAreas.find(area=>area.id==='research').x2=shifted.workAreas.find(area=>area.id==='research').x+100;
      return {named:named.map(area=>({id:area.id,geometry:[area.x,area.y,area.x2,area.y2].every(Number.isFinite),actual:workAreaSeatsForAssessment(project,area.id)})),generic:draft.workAreas.some(area=>area.generic),allTagged:deskItems.every(f=>f.islandId&&draft.workAreas.some(area=>area.id===f.workAreaId)),groupRows:rows.filter(row=>row.key?.startsWith('work-area:')).map(row=>row.name),outOfAreaCount:workAreaSeatsForAssessment(shifted,'research'),before,total:workstationSeatsForAssessment(project),areaTypesInBlocks:plannerBlocks(draft.objects).length===plannerBlocks([...draft.objects,...draft.workAreas]).length,relation:evaluatePlacementRules(project,P.broker)[0],shiftedRelation:evaluatePlacementRules(shifted,P.broker)[0],staleRelation:evaluatePlacementRules({...project,draftsStale:true},P.broker)[0]};
    });
    assert.deepEqual(areaResult.named.map(area=>area.id),['research','sales']);
    assert.ok(areaResult.named.every(area=>area.geometry&&area.actual>=2),'named work areas need viable two-seat island sectors');
    assert.equal(areaResult.generic,true,'remaining workstations should stay in a general area');
    assert.equal(areaResult.allTagged,true,'every generated desk must belong to one work-area island');
    assert.deepEqual(areaResult.groupRows,['Work area · Research','Work area · Sales']);
    assert.equal(areaResult.outOfAreaCount,0,'desks outside their labelled area must not count for that team');
    assert.ok(areaResult.before>0&&areaResult.total>=areaResult.before);
    assert.equal(areaResult.areaTypesInBlocks,true,'work-area overlays must not block room and furniture placement');
    assert.match(areaResult.relation.reason,/Boundary gap/,'current named-area relation should use concept boundaries');
    assert.ok(['pass','fail'].includes(areaResult.relation.status));
    assert.equal(areaResult.shiftedRelation.status,'fail','a team area without valid desks cannot satisfy a location relation');
    assert.equal(areaResult.staleRelation.status,'unknown','stale plans cannot validate a team-area relation');
    assert.equal(await areas.locator('.comparison-card svg text').count()>0,true,'A/B/C thumbnails should label work areas');
    const teamBefore=await areas.evaluate(()=>({workAreas:structuredClone(P.workAreas),broker:structuredClone(P.broker),seats:workAreaSeatsForAssessment(P,'research'),row:brokerAssessment(P).rows.find(row=>row.name==='Team work area · Research')}));
    assert.ok(teamBefore.seats>0,'the Research area needs placed desks before testing an invalid manual boundary');
    await areas.locator('#advancedToggle').click();
    assert.equal(await areas.locator('#teamAreaPicker').isVisible(),true,'opening the current-plan editor should reveal named team areas');
    await areas.locator('#teamAreaPicker [data-focus-work-area="research"]').click();
    assert.equal(await areas.evaluate(()=>selected),'research','the team picker should select the Research boundary');
    await areas.locator('#inspector [data-size="w"]').fill('1000');
    await areas.locator('#inspector [data-size="w"]').dispatchEvent('change');
    const teamAfter=await areas.evaluate(()=>({edited:currentPlanEdited(),seats:workAreaSeatsForAssessment(P,'research'),row:brokerAssessment(P).rows.find(row=>row.name==='Team work area · Research'),broker:P.broker}));
    assert.equal(teamAfter.edited,true,'resizing a named boundary should mark the current plan as edited');
    assert.ok(teamAfter.seats<teamBefore.seats,'desks outside a resized team boundary must stop counting');
    assert.notDeepEqual(teamAfter.row,teamBefore.row,'the fit report should recalculate the team-area shortfall');
    assert.deepEqual(teamAfter.broker,teamBefore.broker,'resizing a team boundary must not change the customer request');
    assert.equal(await areas.locator('#comparisonCurrent').isVisible(),true,'current edited-plan feedback should appear after the boundary change');
    await areas.locator('#comparisonCurrent summary').click();
    assert.match(await areas.locator('#comparisonCurrent').innerText(),/Work area · Research/,'the comparison feedback should expose the updated team-area count');
    await areas.locator('#undoBtn').click();
    assert.deepEqual(await areas.evaluate(()=>P.workAreas),teamBefore.workAreas,'Undo should restore the original team boundary');
    assert.equal(await areas.evaluate(()=>currentPlanEdited()),false,'Undo should restore the selected A/B/C snapshot state');
    assert.equal(await areas.evaluate(()=>workAreaSeatsForAssessment(P,'research')),teamBefore.seats,'Undo should restore the assessed Research seats');
    await areas.reload();
    assert.deepEqual(await areas.evaluate(()=>P.workAreas.filter(area=>!area.generic).map(area=>area.id)),['research','sales'],'work-area overlays should survive project reload');
    await areas.evaluate(()=>selectDraftWithProposals(P.drafts[1].id));
    assert.equal(await areas.evaluate(()=>JSON.stringify(P.workAreas)===JSON.stringify(P.drafts.find(d=>d.id===P.activeDraft).workAreas)),true,'changing concepts should restore that concept’s work-area layer');
    assert.deepEqual(await areas.evaluate(()=>normalizeProject({version:1,drafts:[{id:'old',objects:[],furniture:[]}]}).workAreas),[],'old projects without work areas should load');
    await areas.close();
  }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve))}
})().catch(e=>{console.error(e);process.exitCode=1});
