// End-to-end acceptance for the three fictional rectangular sites.
const { chromium } = require('playwright');
const { createServer } = require('node:http');
const { readFile } = require('node:fs/promises');
const assert = require('node:assert/strict');
const path = require('node:path');

const fixtures = {compact:[12000,9000,0],balanced:[18000,12000,2],spacious:[24000,16000,4]};
const server = createServer(async(req,res)=>{
  const name=new URL(req.url,'http://localhost').pathname.slice(1);
  if(!['studio.html','sample-furniture.js','studio.js','broker.js'].includes(name)){res.writeHead(404);res.end();return}
  res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8');
  res.end(await readFile(path.join(__dirname,name)));
});

function validateLayout(project){
  const box=f=>{const swapped=Math.abs(Math.round((f.rot||0)/90))%2,w=swapped?f.h:f.w,h=swapped?f.w:f.h;return {x:f.x-w/2,y:f.y-h/2,w,h}};
  const objectBox=o=>({x:Math.min(o.x,o.x2),y:Math.min(o.y,o.y2),w:Math.abs(o.x2-o.x),h:Math.abs(o.y2-o.y)});
  const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
  for(const draft of project.drafts){
    const furniture=draft.furniture,blocks=draft.objects.filter(o=>['column','blocked','corridor','room'].includes(o.type)).map(objectBox);
    const rooms=draft.objects.filter(o=>o.type==='room'),zones=draft.objects.filter(o=>o.type==='zone'),corridors=draft.objects.filter(o=>o.type==='corridor');
    for(let i=0;i<rooms.length;i++){
      const room=rooms[i],r=objectBox(room),side=room.door?.side,doorY=side==='north'?r.y:side==='south'?r.y+r.h:r.y+r.h/2,doorX=side==='west'?r.x:side==='east'?r.x+r.w:r.x+r.w/2;
      assert.ok(r.x>=0&&r.y>=0&&r.x+r.w<=project.w&&r.y+r.h<=project.h,`${draft.label}: room outside site`);
      assert.ok(corridors.some(c=>{const q=objectBox(c);return side==='north'?doorX>=q.x&&doorX<=q.x+q.w&&Math.abs(doorY-(q.y+q.h))<=50:side==='south'?doorX>=q.x&&doorX<=q.x+q.w&&Math.abs(doorY-q.y)<=50:side==='west'?doorY>=q.y&&doorY<=q.y+q.h&&Math.abs(doorX-(q.x+q.w))<=50:side==='east'&&doorY>=q.y&&doorY<=q.y+q.h&&Math.abs(doorX-q.x)<=50}),`${draft.label}: room door not on corridor`);
      for(let j=i+1;j<rooms.length;j++)assert.ok(!overlap(r,objectBox(rooms[j])),`${draft.label}: room collision`);
      for(const fixed of draft.objects.filter(o=>['column','blocked','corridor'].includes(o.type)))assert.ok(!overlap(r,objectBox(fixed)),`${draft.label}: room overlaps fixed area`);
    }
    for(let i=0;i<zones.length;i++){
      const zone=zones[i],z=objectBox(zone),linked=furniture.filter(f=>f.zoneId===zone.id);
      assert.ok(z.x>=0&&z.y>=0&&z.x+z.w<=project.w&&z.y+z.h<=project.h,`${draft.label}: shared zone outside site`);
      assert.equal(linked.length,1,`${draft.label}: shared zone needs one demo furniture item`);
      assert.ok(corridors.some(c=>{const q=objectBox(c);return ((Math.abs(z.y-(q.y+q.h))<=50||Math.abs(z.y+z.h-q.y)<=50)&&z.x<q.x+q.w&&z.x+z.w>q.x)||((Math.abs(z.x-(q.x+q.w))<=50||Math.abs(z.x+z.w-q.x)<=50)&&z.y<q.y+q.h&&z.y+z.h>q.y)}),`${draft.label}: shared zone lacks corridor access`);
      for(const other of draft.objects.filter(o=>['column','blocked','corridor','room'].includes(o.type)))assert.ok(!overlap(z,objectBox(other)),`${draft.label}: shared zone overlaps fixed area or room`);
      for(let j=i+1;j<zones.length;j++)assert.ok(!overlap(z,objectBox(zones[j])),`${draft.label}: shared zones overlap`);
      for(const f of furniture){const b=box(f);if(f.zoneId===zone.id)assert.ok(b.x>=z.x&&b.y>=z.y&&b.x+b.w<=z.x+z.w&&b.y+b.h<=z.y+z.h,`${draft.label}: linked furniture outside zone`);else assert.ok(!overlap(z,b),`${draft.label}: unrelated furniture occupies shared zone`)}
    }
    for(let i=0;i<furniture.length;i++){
      const f=furniture[i],b=box(f);
      assert.ok(f.sku?.startsWith('DEMO-'),`${draft.label}: missing demo SKU`);
      assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=project.w&&b.y+b.h<=project.h,`${draft.label}: ${f.sku} outside site`);
      assert.ok(!blocks.some(x=>overlap(b,x)),`${draft.label}: ${f.sku} overlaps fixed zone or corridor`);
      for(let j=i+1;j<furniture.length;j++)assert.ok(!overlap(b,box(furniture[j])),`${draft.label}: furniture collision`);
    }
  }
}

(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  let browser;
  try{
    browser=await chromium.launch({channel:'msedge',headless:true});
    const patternsSeen=new Set();let shiftedAisleSeen=false;
    for(const [fixture,expected] of Object.entries(fixtures)){
      const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
      page.on('pageerror',e=>errors.push(e.message));
      await page.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
      await page.locator('#useExample').click();
      await page.locator('#simPeople').fill('40');
      await page.locator(`[data-simulation="${fixture}"]`).click();
      const original=await page.evaluate(()=>structuredClone(P));
      console.log(`${fixture} concept: ${original.objects.filter(o=>o.type==='room'&&o.kind==='meeting').length} meeting, ${original.objects.filter(o=>o.type==='room'&&o.kind==='office').length} office, ${original.objects.filter(o=>o.type==='room'&&o.kind==='pantry').length} pantry, ${original.drafts.find(d=>d.id===original.activeDraft)?.meta.seats||0} workstations`);
      console.log(`${fixture} alternatives: ${original.drafts.map(d=>`${d.layoutPattern} ${d.meta.seats}/${d.meta.requested} seats, ${d.meta.meetings} meeting, ${d.meta.offices} office, ${d.meta.pantries} pantry`).join(' | ')}`);
      console.log(`${fixture} aisle shifts: ${original.drafts.map(d=>`${d.layoutPattern} (${d.corridorShift?.x||0},${d.corridorShift?.y||0})`).join(' | ')}`);
      shiftedAisleSeen ||= original.drafts.some(d=>d.corridorShift?.x||d.corridorShift?.y);
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>{const expected=layoutSkeleton(d.layoutPattern,d.corridorShift).corridors[0],actual=d.objects.find(o=>o.generated&&o.type==='corridor'&&o.kind==='main');return ['x','y','x2','y2'].every(key=>expected[key]===actual?.[key])})),true,'saved corridor geometry must match the selected adaptive offset');
      assert.deepEqual([original.w,original.h,original.objects.filter(o=>o.type==='column').length],expected);
      assert.equal(original.source.fixtureId,fixture);
      assert.equal(original.drafts.length,3);
      assert.equal(new Set(original.drafts.map(d=>d.layoutPattern)).size,3,'A/B/C should use different spatial patterns');
      original.drafts.forEach(d=>patternsSeen.add(d.layoutPattern));
      assert.equal(await page.locator('#comparisonPanel').isVisible(),true);
      assert.equal(await page.locator('.comparison-card').count(),3);
      assert.equal(await page.locator('.comparison-card svg').count(),3);
      assert.match(await page.locator('.comparison-card').first().innerText(),/Workstations/);
      const visibleCanvas=await page.locator('#canvas').boundingBox();
      assert.ok(visibleCanvas.y+visibleCanvas.height<=1001,'comparison should leave the editing canvas within the viewport');
      validateLayout(original);
      const roomRows=await page.evaluate(()=>brokerAssessment(P).rows.filter(r=>['Private offices','Pantry'].includes(r.name)||r.name.startsWith('Meeting rooms')));
      assert.equal(roomRows.length,3);
      if(fixture==='spacious')assert.ok(roomRows.every(r=>r.status==='Placed · concept'));
      assert.match(await page.locator('#drafts').innerText(),/Meeting rooms \d\/2/);
      assert.equal(await page.locator('#bom .item').count(),await page.evaluate(()=>new Set(allDisplayFurniture(P.furniture).map(f=>f.sku)).size));
      assert.equal(Number(await page.locator('#stats .metric').nth(4).locator('b').innerText()),await page.evaluate(()=>allDisplayFurniture(P.furniture).length));
      assert.match(await page.locator('#bom').innerText(),/DEMO-TASK-CHAIR/);
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.furniture.filter(f=>['bench2','cubicle','desk'].includes(f.kind)).every(f=>furnitureHasClearance(f,{...P,objects:d.objects,furniture:d.furniture})))),true,'generated workstations need usable chair space');
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.furniture.filter(f=>['desk','cubicle'].includes(f.kind)).every(f=>f.islandId&&[2,4,6,8].includes(f.islandSeats)&&islandSpacingValid(f,{...P,objects:d.objects,furniture:d.furniture})))),true,'generated workstations should belong to valid spaced islands');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>[4,6,8].every(size=>[0,90].every(turn=>{const members=workstationIsland('desk',size,6000,4500,`test-${size}-${turn}`,turn);return members.length===size&&new Set(members.map(f=>f.islandId)).size===1&&canPlaceIsland(members,{x0:0,y0:0,x1:P.w,y1:P.h},[],[])}))),true,'4/6/8-person island templates should fit in both directions on an empty compact site');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>[4,6,8].every(size=>[0,90].every(turn=>{const members=workstationIsland('cubicle',size,6000,4500,`private-${size}-${turn}`,turn);return canPlaceIsland(members,{x0:0,y0:0,x1:P.w,y1:P.h},[],[])}))),true,'private cubicle islands should retain outward access in both directions');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const first=P.furniture.find(f=>f.islandId),members=P.furniture.filter(f=>f.islandId===first.islandId),before=members.map(f=>({x:f.x,y:f.y})),box=islandEnvelope(members),shift=box.x+box.w+100<=P.w?100:-100;moveIslandMember(first,first.x+shift,first.y);const deltas=members.map((f,i)=>f.x-before[i].x),moved=deltas.every(dx=>dx===deltas[0])&&deltas[0]===shift;members.forEach((f,i)=>{f.x=before[i].x;f.y=before[i].y});return moved}),true,'moving one desk should move its whole island');
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.objects.filter(o=>o.type==='room'&&o.kind==='meeting').every(room=>meetingRoomFurniture(room).length===room.plannedSeats+1&&meetingRoomFurnitureValid(room,{...P,objects:d.objects,furniture:d.furniture})))),true,'each counted meeting room needs its table, chairs and clear entrance');
      assert.equal(await page.evaluate(()=>P.drafts.every(d=>d.objects.filter(o=>o.type==='room'&&['office','pantry'].includes(o.kind)).every(room=>roomFurnitureValid(room,{...P,objects:d.objects,furniture:d.furniture})&&roomFurniture(room).length===(room.kind==='office'?2:4)))),true,'office and pantry concepts need their furnishings and clear entrances');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>['office','pantry'].every(kind=>['north','south','east','west'].every(side=>{const size=roomSpec(kind,0,side),room={id:`test-${kind}-${side}`,type:'room',kind,door:{side,width:900},x:1000,y:1000,x2:1000+size.w,y2:1000+size.h};return roomFurnitureValid(room,{w:30000,h:30000,objects:[],furniture:[]})}))),true,'office and pantry furniture should fit for each door side');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>Object.entries(extraRoomSpecs).every(([kind,spec])=>['north','south','east','west'].every(side=>{const seats=kind==='meeting'?6:kind==='huddle'?4:kind==='training'?8:spec.capacity,size=roomSpec(kind,seats,side),room={id:`extra-${kind}-${side}`,type:'room',kind,extraKind:kind,plannedSeats:seats,door:{side,width:900},x:1000,y:1000,x2:1000+size.w,y2:1000+size.h};return roomFurniture(room).length>0&&roomFurnitureValid(room,{w:30000,h:30000,objects:[],furniture:[]})}))),true,'every additional space needs fitted furniture for all four door directions');
      if(original.objects.some(o=>o.type==='room'&&o.kind==='pantry'))assert.match(await page.locator('#bom').innerText(),/Pantry counter.*2-seat pantry table.*Dining chair/s);
      if(original.objects.some(o=>o.type==='room'&&o.kind==='meeting'))assert.match(await page.locator('#bom').innerText(),/Meeting chair/);
      assert.equal(await page.evaluate(()=>allDisplayFurniture(P.furniture).filter(f=>f.kind==='meetingChair').length),original.objects.filter(o=>o.type==='room'&&o.kind==='meeting').reduce((n,room)=>n+room.plannedSeats,0));
      if(fixture==='compact')assert.equal(await page.evaluate(()=>[6,8,12].every(seats=>['north','south','east','west'].every(side=>{const size=roomSpec('meeting',seats,side),room={id:`test-${seats}-${side}`,type:'room',kind:'meeting',plannedSeats:seats,door:{side,width:900},x:1000,y:1000,x2:1000+size.w,y2:1000+size.h},project={w:30000,h:30000,objects:[],furniture:[]};return meetingRoomFurniture(room).length===seats+1&&meetingRoomFurnitureValid(room,project)}))),true,'mixed capacities and door sides should fit the generated table and chairs');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const project=structuredClone(P),room=project.objects.find(o=>o.type==='room'&&o.kind==='meeting');room.x2=room.x+3300;return !meetingRoomFurnitureValid(room,project)&&brokerAssessment(project).rows.find(row=>row.name.startsWith('Meeting rooms')).status==='Shortfall'}),true,'an undersized edited meeting room must not count as furnished capacity');
      assert.equal(await page.evaluate(()=>{const desk=P.furniture.find(f=>['bench2','cubicle','desk'].includes(f.kind)),chair=chairItems(desk)[0];return hit(chair.x,chair.y)?.id===desk.id}),true,'selecting a linked chair should select its desk');
      if(fixture==='compact')assert.equal(await page.evaluate(()=>{const a=makeFurniture('bench2',5000,5000),b=makeFurniture('bench2',5000,7300),example={w:12000,h:12000,objects:[],furniture:[a,b]};return !overlap(furnitureRect(a),furnitureRect(b))&&!furnitureHasClearance(a,example)}),true,'chair-use conflict must fail even when desks do not collide');
      assert.equal(await page.locator('#checks .status.bad').count(),0);
      await page.locator('[data-view="3d"]').click();
      await page.locator('[data-view="2d"]').click();
      assert.deepEqual(errors,[]);
      if(fixture==='spacious'){
        await page.locator('#advancedToggle').click();
        await page.locator('[data-tool="officeRoom"]').click();
        const canvas=await page.locator('#canvas').boundingBox();
        const points=await page.evaluate(()=>[screen(1500,1000),screen(4500,4000)]);
        await page.mouse.move(canvas.x+points[0][0],canvas.y+points[0][1]);await page.mouse.down();
        await page.mouse.move(canvas.x+points[1][0],canvas.y+points[1][1],{steps:5});await page.mouse.up();
        assert.equal(await page.evaluate(()=>P.objects.filter(o=>o.type==='room'&&!o.generated).length),1);
        assert.equal(await page.locator('#roomDoorSide').count(),1);
        await page.evaluate(()=>undo());
      }
      if(fixture==='balanced'){
        await page.locator('.comparison-card').nth(1).click();
        assert.equal(await page.evaluate(()=>P.activeDraft===P.drafts[1].id),true,'comparison selection should change the active plan');
        assert.equal(await page.locator('.comparison-card.active').count(),1);
        await page.locator('.comparison-card').first().click();
        await page.locator('#comparisonToggle').click();
        await page.locator('#fitBtn').click();
        const drag=await page.evaluate(()=>{const f=P.furniture.find(item=>['bench2','desk','cubicle'].includes(item.kind));return {from:screen(f.x,f.y),to:screen(f.x,P.h/2),id:f.id,chairY:chairItems(f)[0].y,validSeats:workstationSeatsForAssessment(P)}});
        const canvas=await page.locator('#canvas').boundingBox();
        await page.mouse.move(canvas.x+drag.from[0],canvas.y+drag.from[1]);
        await page.mouse.down();
        await page.mouse.move(canvas.x+drag.to[0],canvas.y+drag.to[1],{steps:5});
        await page.mouse.up();
        await page.locator('#comparisonToggle').click();
        assert.match(await page.locator('#comparisonCurrent').innerText(),/Current edited plan/);
        assert.equal(await page.evaluate(id=>P.furniture.find(f=>f.id===id)?.y!==undefined,drag.id),true);
        assert.notEqual(await page.evaluate(id=>chairItems(P.furniture.find(f=>f.id===id))[0].y,drag.id),drag.chairY,'the linked chair should follow its desk');
        assert.ok(await page.evaluate(()=>workstationSeatsForAssessment(P))<drag.validSeats,'blocked chair clearance should reduce assessed seats');
        assert.ok((await page.evaluate(()=>checks())).some(i=>i.level==='bad'&&/corridor/.test(i.text)),'manual drag should flag a blocked corridor');
        assert.equal(Number(await page.locator('#stats .metric').nth(4).locator('b').innerText()),await page.evaluate(()=>allDisplayFurniture(P.furniture).length));
        await page.evaluate(()=>undo());
        assert.equal(await page.locator('#comparisonCurrent').isVisible(),false);
        assert.deepEqual(await page.evaluate(()=>P.furniture.map(f=>[f.sku,f.x,f.y])),original.furniture.map(f=>[f.sku,f.x,f.y]));
      }
      // Export the selected scheme and import into a new browser tab.
      const downloadPromise=page.waitForEvent('download');
      await page.evaluate(()=>document.querySelector('#exportBtn').click());
      const download=await downloadPromise,second=await browser.newPage();
      second.on('pageerror',e=>errors.push(e.message));
      await second.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
      await second.locator('#fileInput').setInputFiles(await download.path());
      await second.waitForFunction(id=>P?.source?.fixtureId===id,fixture);
      assert.deepEqual(await second.evaluate(()=>({source:P.source,furniture:P.furniture.map(f=>[f.sku,f.x,f.y]),drafts:P.drafts.length})),{source:original.source,furniture:original.furniture.map(f=>[f.sku,f.x,f.y]),drafts:3});
      assert.deepEqual(errors,[]);
      console.log(`PASS ${fixture}: 3 schemes, geometry, BOM, 3D and export/import`);
      await second.close();await page.close();
    }
    assert.deepEqual([...patternsSeen].sort(),['core','neighborhood','perimeter','spine'],'sample spaces should exercise every representative pattern');
    assert.equal(shiftedAisleSeen,true,'at least one sample concept should select a moved aisle');
    const narrow=await browser.newPage({viewport:{width:700,height:900}});
    await narrow.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await narrow.locator('#useExample').click();
    await narrow.locator('[data-simulation="balanced"]').click();
    assert.equal(await narrow.locator('.comparison-card').count(),3,'comparison stays available on a narrow screen');
    assert.ok(await narrow.evaluate(()=>document.body.scrollWidth<=innerWidth+1),'narrow comparison should scroll inside its panel');
    await narrow.close();
    const shared=await browser.newPage();
    await shared.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await shared.locator('#useExample').click();
    await shared.locator('#simPeople').fill('16');
    await shared.locator('#simOffices').fill('0');
    await shared.locator('#simMeetingRooms').fill('1');
    await shared.locator('#simPantry').uncheck();
    await shared.locator('#simDiningSeats').fill('4');
    await shared.locator('#simLoungeSeats').fill('2');
    await shared.locator('#simCoffeeBar').check();
    await shared.locator('#simReception').check();
    await shared.locator('[data-simulation="spacious"]').click();
    const sharedProject=await shared.evaluate(()=>structuredClone(P));
    const sharedState={brief:sharedProject.broker,zones:sharedProject.drafts.map(d=>({pattern:d.layoutPattern,zones:d.objects.filter(o=>o.type==='zone').map(z=>z.kind),meta:d.meta})),rows:await shared.evaluate(()=>brokerAssessment(P).rows)};
    console.log('shared-use scenario',sharedState.zones.map(d=>`${d.pattern}: ${d.zones.join(',')}`).join(' | '));
    assert.equal(sharedState.brief.diningSeats,4);
    for(const draft of sharedState.zones)assert.deepEqual([...draft.zones].sort(),['coffee','dining','lounge','reception']);
    for(const name of ['Dining seats','Lounge seats','Coffee bar','Reception'])assert.equal(sharedState.rows.find(r=>r.name===name)?.status,'Placed · concept',`${name} should be a valid concept placement`);
    assert.equal(await shared.evaluate(()=>allDisplayFurniture(P.furniture).filter(f=>f.kind==='barStool').length),2,'coffee bar needs its two linked stools');
    validateLayout(sharedProject);
    assert.equal(await shared.locator('#checks .status.bad').count(),0);
    assert.match(await shared.locator('#comparisonGrid').innerText(),/Dining seats/);
    assert.match(await shared.locator('#roomSchedule').innerText(),/Coffee bar/);
    const extras=await shared.evaluate(()=>{const previous=P.broker,results=[];for(const [kind,spec] of Object.entries(extraRoomSpecs)){const seats=kind==='meeting'?6:kind==='huddle'||kind==='video'?4:kind==='training'?8:spec.capacity;P.broker=normalizeBrokerBrief({...brokerDefaults(),people:0,meetingRooms:0,offices:0,pantry:false,extraSpaces:[{id:`extra-${kind}`,kind,count:1,seats,priority:'must'}]});const draft=concept('spine',0,0,0,'hybrid'),project={...P,objects:draft.objects,furniture:draft.furniture,drafts:[draft],broker:P.broker},room=draft.objects.find(o=>o.requirementId===`extra-${kind}`),row=brokerAssessment(project).rows.find(r=>r.name.startsWith(extraSpaceKinds[kind]));results.push({kind,placed:!!room,furnished:!!room&&roomFurniture(room).length>0&&roomFurnitureValid(room,project),status:row?.status})}P.broker=previous;return results});
    assert.equal(extras.length,15);
    for(const result of extras)assert.deepEqual(result,{kind:result.kind,placed:true,furnished:true,status:'Placed · concept'},`${result.kind} should be furnished, placed and assessed`);
    assert.equal(await shared.evaluate(()=>{const previous=P.broker;P.broker=normalizeBrokerBrief({...brokerDefaults(),people:0,meetingRooms:0,offices:0,pantry:false,extraSpaces:[{id:'oversize',kind:'huddle',count:1,seats:7,priority:'must'}]});const draft=concept('spine',0,0,0,'hybrid'),row=brokerAssessment({...P,objects:draft.objects,furniture:draft.furniture,drafts:[draft],broker:P.broker}).rows.find(r=>r.name.startsWith('Huddle room'));P.broker=previous;return row.status==='Shortfall'&&!draft.objects.some(o=>o.requirementId==='oversize')}),true,'over-capacity spaces must not be reported as placed');
    await shared.close();
    const cramped=await browser.newPage();
    await cramped.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await cramped.locator('#useExample').click();
    await cramped.locator('#simDiningSeats').fill('40');
    await cramped.locator('#simLoungeSeats').fill('20');
    await cramped.locator('#simCoffeeBar').check();
    await cramped.locator('#simReception').check();
    await cramped.locator('[data-simulation="compact"]').click();
    const amenityRows=await cramped.evaluate(()=>brokerAssessment(P).rows.filter(r=>['Dining seats','Lounge seats','Coffee bar','Reception'].includes(r.name)));
    assert.ok(amenityRows.some(r=>r.status==='Shortfall'),'over-demanded shared uses must show a shortfall');
    assert.match(await cramped.locator('#quickAssessment').innerText(),/Not a fit yet/);
    await cramped.close();
    const overflow=await browser.newPage();
    await overflow.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await overflow.locator('#useExample').click();
    await overflow.locator('#simPeople').fill('120');
    await overflow.locator('[data-simulation="compact"]').click();
    assert.deepEqual(await overflow.evaluate(()=>[P.w,P.h]),[12000,9000]);
    assert.ok(await overflow.evaluate(()=>P.drafts.every(d=>d.meta.seats<d.meta.requested)),'oversubscribed site must report a workstation gap');
    assert.match(await overflow.locator('#quickAssessment').innerText(),/Not a fit yet/);
    console.log('PASS compact over-demand: fixed geometry and visible capacity shortfall');
    await overflow.close();
    const regenerate=await browser.newPage();
    await regenerate.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await regenerate.locator('#useExample').click();
    await regenerate.locator('[data-simulation="spacious"]').click();
    const counts=await regenerate.evaluate(()=>{const result=()=>P.drafts.map(d=>({pattern:d.layoutPattern,rooms:d.objects.filter(o=>o.type==='room').length,corridors:d.objects.filter(o=>o.type==='corridor').length}));const first=result();generateDrafts();const second=result();generateDrafts();return [first,second,result()]});
    assert.deepEqual(counts[1],counts[0],'regenerating must not duplicate generated rooms or corridors');
    assert.deepEqual(counts[2],counts[0],'repeated regeneration must remain stable');
    console.log('PASS regenerate: conceptual rooms are not duplicated');
    await regenerate.close();
    const roles=await browser.newPage();
    await roles.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await roles.locator('#startProject').click();
    await roles.locator('#naturalBriefText').fill('需要24个工位、1间总经理室和2间总监办公室、2间6人会议室、前台。总经理室优先靠窗。');
    await roles.locator('#naturalBriefExtract').click();
    assert.equal(await roles.locator('#officeExecutive').inputValue(),'1');
    assert.equal(await roles.locator('#officeDirector').inputValue(),'2');
    await roles.locator('#reviewEdit').click();
    await roles.locator('#broker-offices').fill('2');
    await roles.locator('#brokerForm button.primary').click();
    assert.match(await roles.locator('#officeRoleError').innerText(),/must fit within the total/);
    await roles.locator('#broker-offices').fill('3');
    await roles.locator('#brokerForm button.primary').click();
    await roles.locator('[data-simulation="spacious"]').click();
    const roleProject=await roles.evaluate(()=>structuredClone(P));
    assert.equal(roleProject.broker.offices,3);
    assert.equal(roleProject.broker.officeRoles.executive,1);
    assert.equal(roleProject.broker.relations[0].rule,'window');
    assert.ok(roleProject.objects.some(o=>o.type==='room'&&o.role==='executive'&&o.name==='Executive office'));
    assert.equal(roleProject.objects.filter(o=>o.type==='room'&&o.role==='director').length,2);
    assert.ok(await roles.evaluate(()=>placementScore('reception',{x:1200,y:8000})>placementScore('reception',{x:22000,y:8000})),'reception candidates should prefer the marked entrance');
    assert.ok(await roles.evaluate(()=>placementScore('office',{x:4500,y:1200},'executive')>placementScore('office',{x:4500,y:14500},'executive')),'stated executive-office window preference should affect placement ranking');
    assert.match(await roles.locator('#comparisonGrid').innerText(),/Executive office near windows/);
    assert.match(await roles.locator('#comparisonGrid').innerText(),/Within MVP distance|Misses MVP distance/);
    validateLayout(roleProject);
    await roles.locator('#brokerResult').click();
    assert.match(await roles.locator('#brokerReportContent').innerText(),/Executive offices/);
    assert.match(await roles.locator('#brokerReportContent').innerText(),/MVP straight-line screens/);
    assert.ok(await roles.evaluate(()=>brokerAssessment(P).rows.some(r=>r.name.startsWith('Spatial relation · executive office')&&r.actual.includes('straight-line')&&r.status!=='Not assessed')));
    assert.match(await roles.locator('#brokerReportContent').innerText(),/System suggestion · reception near entrance/);
    assert.match(await roles.locator('#brokerReportContent').innerText(),/workstations toward daylight/);
    await roles.locator('#brokerReportClose').click();
    await roles.evaluate(()=>{const room=P.objects.find(o=>o.type==='room'&&o.role==='executive');room.x+=6000;room.x2+=6000;save()});
    assert.equal(await roles.evaluate(()=>currentPlanEdited(P)),true);
    assert.equal(await roles.evaluate(()=>P.draftsStale),false,'editing a concept room should recheck the working plan without invalidating the site');
    assert.match(await roles.locator('#comparisonCurrent').innerText(),/Current edited plan.*Location checks:.*Executive office near windows/);
    assert.match(await roles.locator('#comparisonGrid .comparison-card.active').innerText(),/Original snapshot/);
    roles.once('dialog',dialog=>dialog.dismiss());
    await roles.locator('#comparisonGrid .comparison-card.active').click();
    assert.equal(await roles.evaluate(()=>currentPlanEdited(P)),true,'canceling snapshot replacement must keep the edited plan');
    await roles.locator('#brokerResult').click();
    assert.match(await roles.locator('#brokerReportContent').innerText(),/Assessment of the current edited plan/);
    assert.equal(await roles.evaluate(()=>brokerAssessment(P).placement[0].status),'fail');
    await roles.locator('#brokerReportClose').click();
    await roles.locator('#advancedToggle').click();
    await roles.evaluate(()=>{selected=P.objects.find(o=>o.type==='window').id;render()});
    const windowX=Number(await roles.locator('#inspector [data-prop="x"]').inputValue());
    await roles.locator('#inspector [data-prop="x"]').fill(String(windowX+100));
    await roles.locator('#inspector [data-prop="x"]').dispatchEvent('change');
    assert.equal(await roles.evaluate(()=>P.draftsStale),true,'moving a site window must invalidate generated snapshots');
    assert.equal(await roles.locator('#comparisonGrid .comparison-card').count(),0,'outdated A/B/C results must be hidden');
    assert.equal(await roles.locator('#drafts [data-draft]').count(),0,'outdated sidebar summaries must be hidden');
    assert.match(await roles.locator('#comparisonCurrent').innerText(),/out of date/);
    await roles.evaluate(()=>generateDrafts());
    assert.equal(await roles.evaluate(()=>P.draftsStale),false);
    assert.equal(await roles.locator('#comparisonGrid .comparison-card').count(),3,'regeneration should restore current A/B/C comparisons');
    await roles.close();
    const checklist=await browser.newPage();
    await checklist.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await checklist.locator('#startProject').click();
    await checklist.locator('#naturalBriefText').fill('We need 24 workstations and two 6-person meeting rooms for our office team.');
    await checklist.locator('#naturalBriefExtract').click();
    assert.equal(await checklist.locator('#extractedAnswers [data-suggested-zone]').count(),4);
    assert.equal(await checklist.evaluate(()=>simulationDraft),null);
    await checklist.locator('#extractedAnswers [data-suggested-zone="reception"]').selectOption('accepted');
    await checklist.locator('#extractedAnswers [data-suggested-zone="pantry"]').selectOption('uncertain');
    await checklist.locator('#extractedAnswers [data-suggested-zone="waiting"]').selectOption('removed');
    await checklist.locator('#extractedAnswers [data-answer="diningSeats"]').selectOption('requested');
    await checklist.locator('#extractedAnswers [data-answer-count="diningSeats"]').fill('6');
    await checklist.locator('#extractedAnswers [data-checklist="teamZones"]').selectOption('requested');
    await checklist.locator('#extractedAnswers [data-checklist-note="teamZones"]').fill('Sales 8 together');
    await checklist.locator('#extractedAnswers [data-suggested-zone="quietWork"]').selectOption('uncertain');
    await checklist.locator('#extractedAnswers details summary').click();
    await checklist.locator('#extractedAnswers [data-checklist="budget"]').selectOption('requested');
    await checklist.locator('#extractedAnswers [data-checklist-note="budget"]').fill('Budget to be confirmed');
    assert.equal(await checklist.locator('#brokerForm button.primary').isDisabled(),false);
    await checklist.locator('#brokerForm button.primary').click();
    assert.equal(await checklist.evaluate(()=>simulationDraft.reception),true);
    assert.equal(await checklist.evaluate(()=>simulationDraft.intakeAnswers.pantry),'uncertain');
    assert.equal(await checklist.evaluate(()=>simulationDraft.suggestedZones.waiting),'removed');
    assert.equal(await checklist.evaluate(()=>simulationDraft.completeness.waiting.state),'not-needed');
    assert.equal(await checklist.evaluate(()=>simulationDraft.requirements.spaces.some(space=>space.kind==='waiting')),false);
    assert.equal(await checklist.evaluate(()=>simulationDraft.diningSeats),6);
    assert.equal(await checklist.evaluate(()=>simulationDraft.completeness.teamZones.note),'Sales 8 together');
    assert.equal(await checklist.evaluate(()=>simulationDraft.completeness.quietWork.state),'uncertain');
    assert.equal(await checklist.evaluate(()=>simulationDraft.requirements.completeness.budget.state),'requested');
    await checklist.locator('[data-simulation="spacious"]').click();
    assert.equal(await checklist.evaluate(()=>P.broker.completeness.teamZones.state),'requested');
    await checklist.locator('#brokerResult').click();
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/Additional need · Teams need distinct work areas/);
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/Customer is not sure yet: Pantry/);
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/System suggestions accepted: Reception · Removed: Visitor waiting area/);
    assert.match(await checklist.locator('#brokerReportContent').innerText(),/Recorded only · not auto-placed or verified/);
    await checklist.close();
  }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve))}
})().catch(e=>{console.error(e);process.exitCode=1});
