/* Generic office planning MVP. Coordinates use millimetres; projects persist in browser localStorage. */
const $ = s => document.querySelector(s), cv = $('#canvas'), ctx = cv.getContext('2d');
const STORE = 'office-planner-mvp-v1';
const hasSavedProject = !!localStorage.getItem(STORE);
const catalog = SAMPLE_FURNITURE;
const visibleCatalog=catalog.filter(item=>!['meetingModular','pantryCounter','pantryTable','diningChair','printer','shelf','serverRack','lactationChair','sideTable','videoScreen','displayPlinth','locker','barStool'].includes(item.kind));
const typeName={wall:'Wall',door:'Door',window:'Window',partition:'Partition',column:'Column',corridor:'Corridor',exit:'Emergency exit',blocked:'No-go zone',room:'Functional room',zone:'Shared-use zone'};
let P, tool='select', selected=null, drag=null, view='2d', history=[], readOnly=false, spaceDown=false;
let comparisonCollapsed=false;
let V={scale:0.04,x:0,y:0};
let underlay={src:null,image:null};
function id(){return Math.random().toString(36).slice(2,10)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function normalizeProject(p){p.source=p.source||{kind:'dimensions'};p.site=p.site||{confirmed:false};p.drafts=p.drafts||[];p.draftsStale=!!p.draftsStale;return p}
function fresh(name='Untitled office',w=18000,h=12000,source={kind:'dimensions'}){return normalizeProject({version:1,name,w,h,source,site:{confirmed:false},rules:{main:1200,minor:900},objects:[{id:id(),type:'wall',x:0,y:0,x2:w,y2:0},{id:id(),type:'wall',x:w,y:0,x2:w,y2:h},{id:id(),type:'wall',x:w,y:h,x2:0,y2:h},{id:id(),type:'wall',x:0,y:h,x2:0,y2:0}],furniture:[],drafts:[]})}
function load(){try{const p=JSON.parse(localStorage.getItem(STORE));if(p?.version===1)return normalizeProject(p)}catch{}return fresh()}
function save(){localStorage.setItem(STORE,JSON.stringify(P));render()}
function snapshot(){history.push(JSON.stringify(P));if(history.length>30)history.shift()}
function undo(){if(!history.length)return;P=JSON.parse(history.pop());selected=null;save()}
function fit(){const r=cv.getBoundingClientRect(), pad=70;V.scale=Math.min((r.width-pad)/P.w,(r.height-pad)/P.h);V.x=(r.width-P.w*V.scale)/2;V.y=(r.height-P.h*V.scale)/2;render()}
function resizeCanvas(){const r=cv.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h}ctx.setTransform(d,0,0,d,0,0)}
function sourceUnderlay(){const src=P.source?.preview;if(!src)return null;if(underlay.src!==src){const image=new Image();underlay={src,image};image.onload=render;image.src=src}return underlay.image}
function screen(x,y){return [V.x+x*V.scale,V.y+y*V.scale]}; function world(x,y){return [(x-V.x)/V.scale,(y-V.y)/V.scale]};
function rect(o){return {x:Math.min(o.x,o.x2),y:Math.min(o.y,o.y2),w:Math.abs(o.x2-o.x),h:Math.abs(o.y2-o.y)}}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function inSite(r){return r.x>=0&&r.y>=0&&r.x+r.w<=P.w&&r.y+r.h<=P.h}
function clamp(n){return Math.round(n/50)*50}
function furnitureRect(f){const quarter=Math.abs(Math.round((f.rot||0)/90))%2,w=quarter?f.h:f.w,h=quarter?f.w:f.h;return {x:f.x-w/2,y:f.y-h/2,w,h}}
function siteReadiness(){const count=t=>P.objects.filter(o=>o.type===t).length,entrances=count('door'),exits=count('exit'),walls=count('wall'),fixed=count('column')+count('blocked'),recognitionPending=P.source?.status==='awaiting_recognition',geometryReady=walls>=3&&entrances>0&&exits>0;return {entrances,exits,walls,fixed,recognitionPending,geometryReady,ready:geometryReady&&!recognitionPending}}
function sourceLabel(){if(P.source?.kind==='upload')return `${P.source.fileName||'Uploaded plan'} · ${P.source.status==='awaiting_recognition'?'assisted import':'tracing reference'}`;if(P.source?.kind==='simulated')return `${P.source.label||'Simulated property'} · fictional`;if(P.source?.kind==='example')return 'Guided example';if(P.source?.originalFile)return `Entered dimensions · ${P.source.originalFile.fileName} intake retained`;return `${(P.w/1000).toFixed(1)} × ${(P.h/1000).toFixed(1)} m · entered dimensions`}
function markSiteChanged(){P.site=P.site||{};P.site.confirmed=false;if(P.drafts?.length)P.draftsStale=true}
function renderSiteStatus(){const r=siteReadiness(),status=P.draftsStale?['warn','Site changed · regenerate concepts']:r.recognitionPending?['warn','Assisted import required']:P.site?.confirmed?['ok','Site confirmed']:r.ready?['warn','Ready for confirmation']:['bad','Entrance and emergency exit required'];$('#siteStatus').innerHTML=`<div class="readiness-row"><span>Source</span><b>${esc(sourceLabel())}</b></div><div class="readiness-row"><span>Envelope</span><b>${(P.w/1000).toFixed(1)} × ${(P.h/1000).toFixed(1)} m</b></div><div class="readiness-row"><span>Entrances / exits</span><b>${r.entrances} / ${r.exits}</b></div><div class="readiness-row"><span>Fixed constraints</span><b>${r.fixed}</b></div><div class="status ${status[0]}">${status[1]}</div>`}
function renderPhaseBar(){const bar=$('#setupBar');if(readOnly){bar.hidden=true;return}const r=siteReadiness(),tools=bar.querySelectorAll('[data-setup-tool]');bar.hidden=false;bar.classList.toggle('warn',!!P.draftsStale||(!r.ready&&!P.drafts.length));if(P.drafts.length){tools.forEach(b=>b.hidden=true);$('#setupTitle').textContent=P.draftsStale?'Site changed · concepts need an update':'Concept plans ready · compare A / B / C';$('#setupText').textContent=P.draftsStale?'Review the brief and regenerate before sharing this revision.':'Compare capacity, workplace mix, checks and estimated furniture value.';$('#openBrief').textContent=P.draftsStale?'Review brief & regenerate':'Update brief';return}if(r.recognitionPending){tools.forEach(b=>b.hidden=true);$('#setupTitle').textContent='PDF / DWG requires assisted import';$('#setupText').textContent='The file details are recorded. Continue with the dimension-based review canvas for this MVP.';$('#openBrief').textContent='Use dimensions for now';return}tools.forEach(b=>b.hidden=false);$('#setupTitle').textContent='Step 3 of 4 · Review and confirm the site';$('#setupText').textContent=r.ready?'Entrance and exit are marked. Review their labels on the plan, add fixed constraints if needed, then continue.':'Choose Place entrance or Place exit, then click the correct exterior wall.';$('#openBrief').textContent='Confirm site & continue'}
function addFurniture(kind){if(readOnly)return;snapshot();const candidate=makeFurniture(kind,P.w/2,P.h/2);let placed=false;for(let y=700;y<P.h&&!placed;y+=700)for(let x=700;x<P.w&&!placed;x+=700){candidate.x=x;candidate.y=y;if(canPlaceFurniture(candidate,P.furniture,P.objects)){placed=true}}if(!placed){history.pop();$('#hint').textContent='No free position found. Move furniture or adjust the clear zones first.';return}P.furniture.push(candidate);selected=candidate.id;tool='select';setTool();save()}
function seatsOfFurniture(f){return f.kind==='bench2'?2:f.kind==='cubicle'||f.kind==='desk'?1:f.kind==='meeting'?6:0}
function makeFurniture(kind,x,y){const c=catalog.find(v=>v.kind===kind);return {id:id(),type:'furniture',kind,sku:c.sku,catalogVersion:SAMPLE_CATALOG_VERSION,name:c.name,w:c.width,h:c.depth,z:c.height,price:c.samplePrice,priceStatus:'illustrative',x,y,rot:0}}
// Chairs are linked views of their parent furniture, so moving or rotating a desk keeps its seats together.
// The extra chair-use depth is an MVP planning allowance, not a code-compliance value.
const CHAIR_USE_DEPTH=1000,CHAIR_SIZE=600;
function chairSeats(f){const w=f.w,h=f.h;if(f.kind==='bench2')return [{x:0,y:-h/2,side:'north'},{x:0,y:h/2,side:'south'}];if(f.kind==='desk'||f.kind==='manager'||f.kind==='reception')return [{x:0,y:h/2,side:'south'}];if(f.kind==='coffeeBar')return [{x:-550,y:h/2,side:'south'},{x:550,y:h/2,side:'south'}];if(f.kind==='cubicle')return [{x:0,y:200,side:'inside'}];if(f.kind==='meeting')return [{x:-w/4,y:-h/2,side:'north'},{x:w/4,y:-h/2,side:'north'},{x:-w/4,y:h/2,side:'south'},{x:w/4,y:h/2,side:'south'},{x:-w/2,y:0,side:'west'},{x:w/2,y:0,side:'east'}];return []}
function rotateLocal(f,x,y){const angle=(f.rot||0)*Math.PI/180;return {x:f.x+x*Math.cos(angle)-y*Math.sin(angle),y:f.y+x*Math.sin(angle)+y*Math.cos(angle)}}
function chairItems(f){const spec=catalog.find(item=>item.kind===(f.kind==='meeting'?'meetingChair':f.kind==='coffeeBar'?'barStool':'chair'));return chairSeats(f).map((seat,index)=>{const outward=seat.side==='north'?{x:0,y:-1}:seat.side==='south'?{x:0,y:1}:seat.side==='west'?{x:-1,y:0}:seat.side==='east'?{x:1,y:0}:{x:0,y:0},offset=seat.side==='inside'?0:CHAIR_SIZE/2+50,p=rotateLocal(f,seat.x+outward.x*offset,seat.y+outward.y*offset);return {id:`${f.id}-chair-${index}`,type:'furniture',kind:spec.kind,sku:spec.sku,catalogVersion:SAMPLE_CATALOG_VERSION,name:spec.name,w:spec.width,h:spec.depth,z:spec.height,price:spec.samplePrice,priceStatus:'illustrative',x:p.x,y:p.y,rot:f.rot||0,linkedTo:f.id}})}
function rotatedLocalBox(f,x,y,w,h){const corners=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]].map(([a,b])=>rotateLocal(f,a,b)),xs=corners.map(p=>p.x),ys=corners.map(p=>p.y);return {x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function chairUseZones(f){return chairSeats(f).filter(seat=>seat.side!=='inside').map(seat=>seat.side==='north'?rotatedLocalBox(f,seat.x-CHAIR_SIZE/2,seat.y-CHAIR_USE_DEPTH,CHAIR_SIZE,CHAIR_USE_DEPTH):seat.side==='south'?rotatedLocalBox(f,seat.x-CHAIR_SIZE/2,seat.y,CHAIR_SIZE,CHAIR_USE_DEPTH):seat.side==='west'?rotatedLocalBox(f,seat.x-CHAIR_USE_DEPTH,seat.y-CHAIR_SIZE/2,CHAIR_USE_DEPTH,CHAIR_SIZE):rotatedLocalBox(f,seat.x,seat.y-CHAIR_SIZE/2,CHAIR_USE_DEPTH,CHAIR_SIZE))}
function occupiedFurnitureRects(f){return [furnitureRect(f),...chairUseZones(f)]}
function allDisplayFurniture(items,objects=P.objects){return [...items.flatMap(f=>[f,...chairItems(f)]),...(objects||[]).filter(o=>o.type==='room').flatMap(roomFurniture)]}
function furnitureHasClearance(f,project){const areas=occupiedFurnitureRects(f),blocks=plannerBlocks((project.objects||[]).filter(o=>o.id!==f.zoneId)),inside=r=>r.x>=0&&r.y>=0&&r.x+r.w<=project.w&&r.y+r.h<=project.h;return areas.every(r=>inside(r)&&!blocks.some(block=>overlap(r,block))&&!(project.furniture||[]).some(other=>other.id!==f.id&&occupiedFurnitureRects(other).some(box=>overlap(r,box))))}
function workstationSeatsForAssessment(project){return (project.furniture||[]).filter(f=>['bench2','cubicle','desk'].includes(f.kind)&&furnitureHasClearance(f,project)&&islandSpacingValid(f,project)).reduce((total,f)=>total+seatsOfFurniture(f),0)}
function plannerBlocks(objects){return objects.filter(o=>['column','blocked','corridor','room','zone'].includes(o.type)).map(rect)}
function canPlaceFurniture(f,placed,objects){const areas=occupiedFurnitureRects(f),blocks=plannerBlocks(objects);return areas.every(r=>inSite(r)&&!blocks.some(b=>overlap(r,b))&&!placed.some(x=>occupiedFurnitureRects(x).some(q=>overlap(r,q))))}
function putIfFree(kind,x,y,placed,objects){const f=makeFurniture(kind,x,y);if(!canPlaceFurniture(f,placed,objects))return false;placed.push(f);return true}
// An island is assembled before testing positions. Opposing rows face outward, leaving the joined desk edges inside.
const ISLAND_GAP=400,ISLAND_SIZES=[8,6,4,2];
function workstationIsland(kind,seats,x,y,islandId=id(),turn=0){
  const unit=catalog.find(v=>v.kind===kind),columns=seats/2,members=[];
  for(let row=0;row<2;row++)for(let column=0;column<columns;column++){
    const localX=(column-(columns-1)/2)*unit.width,localY=(row-.5)*unit.depth,desk=makeFurniture(kind,x+(turn?-localY:localX),y+(turn?localX:localY));
    desk.rot=(row===0?180:0)+turn;desk.islandId=islandId;desk.islandSeats=seats;members.push(desk);
  }
  return members;
}
function islandEnvelope(members){const boxes=members.flatMap(occupiedFurnitureRects),x=Math.min(...boxes.map(b=>b.x)),y=Math.min(...boxes.map(b=>b.y)),right=Math.max(...boxes.map(b=>b.x+b.w)),bottom=Math.max(...boxes.map(b=>b.y+b.h)),privateAccess=members[0]?.kind==='cubicle'?900:0,turn=Math.abs(Math.round((members[0]?.rot||0)/90))%2;return {x:x-(turn?privateAccess:0),y:y-(turn?0:privateAccess),w:right-x+(turn?2*privateAccess:0),h:bottom-y+(turn?0:2*privateAccess)}}
function islandSpacingValid(f,project){if(!f.islandId)return true;const furniture=project.furniture||[],members=furniture.filter(item=>item.islandId===f.islandId);if(members.length!==f.islandSeats)return false;const envelope=islandEnvelope(members);if(envelope.x<0||envelope.y<0||envelope.x+envelope.w>project.w||envelope.y+envelope.h>project.h||plannerBlocks(project.objects||[]).some(block=>overlap(envelope,block))||furniture.some(item=>!item.islandId&&occupiedFurnitureRects(item).some(box=>overlap(envelope,box))))return false;return ![...new Set(furniture.filter(item=>item.islandId&&item.islandId!==f.islandId).map(item=>item.islandId))].some(islandId=>{const other=islandEnvelope(furniture.filter(item=>item.islandId===islandId));return overlap(envelope,{x:other.x-ISLAND_GAP,y:other.y-ISLAND_GAP,w:other.w+2*ISLAND_GAP,h:other.h+2*ISLAND_GAP})})}
function canPlaceIsland(members,zone,placed,objects){
  const envelope=islandEnvelope(members),inside=r=>r.x>=zone.x0&&r.y>=zone.y0&&r.x+r.w<=zone.x1&&r.y+r.h<=zone.y1&&inSite(r),blocks=plannerBlocks(objects);
  if(!inside(envelope)||blocks.some(block=>overlap(envelope,block)))return false;
  const existing=[...new Set(placed.filter(f=>f.islandId).map(f=>f.islandId))].map(islandId=>islandEnvelope(placed.filter(f=>f.islandId===islandId)));
  if(existing.some(other=>overlap(envelope,{x:other.x-ISLAND_GAP,y:other.y-ISLAND_GAP,w:other.w+2*ISLAND_GAP,h:other.h+2*ISLAND_GAP})))return false;
  const loose=placed.filter(f=>!f.islandId);
  if(loose.some(f=>occupiedFurnitureRects(f).some(box=>overlap(envelope,box))))return false;
  return members.every((f,index)=>occupiedFurnitureRects(f).every(area=>inside(area)&&!members.some((other,j)=>j>index&&occupiedFurnitureRects(other).some(box=>overlap(area,box)))));
}
function fillWorkstations(kind,target,zones,placed,objects){
  let total=placed.filter(f=>['bench2','cubicle','desk'].includes(f.kind)).reduce((n,f)=>n+seatsOfFurniture(f),0);
  for(const size of ISLAND_SIZES){
    if(total>=target||size>Math.max(2,target-total+(target-total)%2))continue;
    const points=[];
    for(const turn of [0,90]){const base=workstationIsland(kind,size,0,0,undefined,turn),box=islandEnvelope(base);for(const zone of zones)for(let y=zone.y0-box.y;y<=zone.y1-box.y-box.h;y+=500)for(let x=zone.x0-box.x;x<=zone.x1-box.x-box.w;x+=500)points.push({x,y,zone,turn})}
    points.sort((a,b)=>placementScore('workstation',b)-placementScore('workstation',a)||a.y-b.y||a.x-b.x);
    for(const point of points){if(total>=target||size>Math.max(2,target-total+(target-total)%2))break;const island=workstationIsland(kind,size,point.x,point.y,undefined,point.turn);if(canPlaceIsland(island,point.zone,placed,objects)){placed.push(...island);total+=size}}
  }
  return total;
}
const roomNames={meeting:'Meeting room',office:'Private office',pantry:'Pantry'};
const extraRoomSpecs={meeting:{name:'Additional meeting room',capacity:30},huddle:{name:'Huddle room',capacity:6},focus:{name:'Focus room',capacity:1,w:3000,h:3000},training:{name:'Training room',capacity:12},collaboration:{name:'Open collaboration',capacity:2,w:3200,h:3000},waiting:{name:'Visitor waiting area',capacity:2,w:3200,h:3000},canteen:{name:'Canteen / break room',capacity:4,w:3200,h:3200},kitchenette:{name:'Kitchenette',capacity:2,w:3200,h:3000},print:{name:'Print / copy area',capacity:0,w:3000,h:2500},storage:{name:'Storage room',capacity:0,w:3000,h:2500},it:{name:'IT / server room',capacity:0,w:3000,h:2500},lactation:{name:'Lactation room',capacity:1,w:3000,h:2700},video:{name:'Video meeting room',capacity:4},display:{name:'Visitor display / showroom',capacity:0,w:3200,h:3000},lockers:{name:'Lockers / mail area',capacity:0,w:3000,h:2500}};
function meetingSeatingPlan(seats,doorSide='south'){
  const count=Math.max(1,Math.min(30,Math.trunc(Number(seats)||1))),ends=Math.min(2,count),remaining=count-ends,nearCount=2*Math.floor(remaining/4),farCount=remaining-nearCount;
  const positions=(amount,clearCenter)=>{if(!amount)return [];if(amount%2){const half=(amount-1)/2;return [...Array.from({length:half},(_,i)=>-(i+1)*800),0,...Array.from({length:half},(_,i)=>(i+1)*800)]}const half=amount/2,first=clearCenter?800:400;return [...Array.from({length:half},(_,i)=>-(first+i*800)),...Array.from({length:half},(_,i)=>first+i*800)]};
  const near=positions(nearCount,true),far=positions(farCount,false),furthest=Math.max(0,...near.map(Math.abs),...far.map(Math.abs)),tableLength=Math.max(3600,2*(furthest+450)),turn=doorSide==='north'?180:doorSide==='east'?270:doorSide==='west'?90:0,horizontal=doorSide==='north'||doorSide==='south';
  return {count,ends,near,far,tableLength,turn,w:horizontal?tableLength+2000:3000,h:horizontal?3000:tableLength+2000};
}
function roomSpec(kind,seats=6,doorSide='south'){if(['meeting','huddle','training','video'].includes(kind)){const plan=meetingSeatingPlan(seats,doorSide);return {w:plan.w,h:plan.h}}if(kind==='office'||kind==='focus')return {w:3000,h:3000};const spec=extraRoomSpecs[kind],w=spec?.w||3200,h=spec?.h||3000;return ['east','west'].includes(doorSide)?{w:h,h:w}:{w,h}}
function meetingRoomFurniture(room){
  const bounds=rect(room),plan=meetingSeatingPlan(room.plannedSeats,room.door?.side),chairSpec=catalog.find(item=>item.kind==='meetingChair'),tableSpec=catalog.find(item=>item.kind==='meetingModular'),cx=bounds.x+bounds.w/2,cy=bounds.y+bounds.h/2,table={id:`${room.id}-table`,type:'furniture',kind:'meetingModular',sku:tableSpec.sku,catalogVersion:SAMPLE_CATALOG_VERSION,name:'Meeting table · concept',w:plan.tableLength,h:1000,z:tableSpec.height,price:Math.round(tableSpec.samplePrice*plan.tableLength/tableSpec.width),priceStatus:'illustrative',x:cx,y:cy,rot:plan.turn,roomId:room.id,derived:true};
  const seats=[...plan.far.map(x=>({x,y:-500,side:'north'})),...plan.near.map(x=>({x,y:500,side:'south'})),...(plan.ends? [{x:-plan.tableLength/2,y:0,side:'west'}]:[]),...(plan.ends>1?[{x:plan.tableLength/2,y:0,side:'east'}]:[])];
  const chairs=seats.map((seat,index)=>{const vector=seat.side==='north'?[0,-1]:seat.side==='south'?[0,1]:seat.side==='west'?[-1,0]:[1,0],p=rotateLocal(table,seat.x+vector[0]*350,seat.y+vector[1]*350);return {id:`${room.id}-chair-${index}`,type:'furniture',kind:'meetingChair',sku:chairSpec.sku,catalogVersion:SAMPLE_CATALOG_VERSION,name:chairSpec.name,w:chairSpec.width,h:chairSpec.depth,z:chairSpec.height,price:chairSpec.samplePrice,priceStatus:'illustrative',x:p.x,y:p.y,rot:plan.turn,roomId:room.id,derived:true}});
  const useZones=seats.map(seat=>seat.side==='north'?rotatedLocalBox(table,seat.x-300,seat.y-800,600,800):seat.side==='south'?rotatedLocalBox(table,seat.x-300,seat.y,600,800):seat.side==='west'?rotatedLocalBox(table,seat.x-800,seat.y-300,800,600):rotatedLocalBox(table,seat.x,seat.y-300,800,600));
  table.useZones=useZones;return [table,...chairs];
}
function meetingRoomFurnitureValid(room,project){
  if(!['meeting','huddle','training'].includes(room.kind))return true;if(room.extraKind&&(!extraRoomSpecs[room.extraKind]||(+room.plannedSeats||0)>extraRoomSpecs[room.extraKind].capacity))return false;const bounds=rect(room),items=meetingRoomFurniture(room),table=items[0],inside=area=>area.x>=bounds.x&&area.y>=bounds.y&&area.x+area.w<=bounds.x+bounds.w&&area.y+area.h<=bounds.y+bounds.h,door=room.door?.side,approach=door==='north'?{x:bounds.x+bounds.w/2-450,y:bounds.y,w:900,h:900}:door==='south'?{x:bounds.x+bounds.w/2-450,y:bounds.y+bounds.h-900,w:900,h:900}:door==='west'?{x:bounds.x,y:bounds.y+bounds.h/2-450,w:900,h:900}:{x:bounds.x+bounds.w-900,y:bounds.y+bounds.h/2-450,w:900,h:900};
  return items.length===Math.max(1,Number(room.plannedSeats)||1)+1&&items.every((item,index)=>{const area=furnitureRect(item);return inside(area)&&!overlap(area,approach)&&!items.some((other,j)=>j>index&&overlap(area,furnitureRect(other)))})&&table.useZones.every(area=>inside(area)&&!overlap(area,approach))&&!(project.furniture||[]).some(item=>overlap(bounds,furnitureRect(item)));
}
function roomFurniture(room){
  if(['meeting','huddle','training'].includes(room.kind))return meetingRoomFurniture(room);
  if(!['office','pantry','focus','collaboration','waiting','canteen','kitchenette','print','storage','it','lactation','video','display','lockers'].includes(room.kind))return [];
  const bounds=rect(room),side=room.door?.side,turn=side==='north'?180:side==='east'?270:side==='west'?90:0,anchor={x:bounds.x+bounds.w/2,y:bounds.y+bounds.h/2,rot:turn};
  const item=(kind,key,x,y)=>{const spec=catalog.find(c=>c.kind===kind),point=rotateLocal(anchor,x,y);return {id:`${room.id}-${key}`,type:'furniture',kind,sku:spec.sku,catalogVersion:SAMPLE_CATALOG_VERSION,name:spec.name,w:spec.width,h:spec.depth,z:spec.height,price:spec.samplePrice,priceStatus:'illustrative',x:point.x,y:point.y,rot:turn,roomId:room.id,derived:true}};
  if(room.kind==='video')return [...meetingRoomFurniture(room),item('videoScreen','screen',0,-1400)];
  if(['office','focus'].includes(room.kind)){const desk=item(room.kind==='office'?'manager':'desk','desk',0,-850),chair=chairItems(desk)[0];chair.roomId=room.id;chair.derived=true;desk.useZones=chairUseZones(desk);return [desk,chair]}
  if(['pantry','kitchenette'].includes(room.kind)){const counter=item('pantryCounter','counter',0,-1150),table=item('pantryTable','table',0,-100),chairs=[item('diningChair','chair-0',-850,-100),item('diningChair','chair-1',850,-100)];table.useZones=[rotatedLocalBox(table,-1300,-300,800,600),rotatedLocalBox(table,500,-300,800,600)];return [counter,table,...chairs]}
  if(['collaboration','waiting'].includes(room.kind))return [item('lounge2','seating',0,-400)];
  if(room.kind==='canteen')return [item('dining4','seating',0,-450)];
  if(room.kind==='print')return [item('printer','printer',-650,-900),item('cabinet','supplies',650,-900)];
  if(room.kind==='storage')return [item('shelf','shelf-0',-700,-850),item('shelf','shelf-1',700,-850)];
  if(room.kind==='it')return [item('serverRack','rack-0',-650,-850),item('serverRack','rack-1',650,-850)];
  if(room.kind==='display')return [item('displayPlinth','display-0',-650,-850),item('displayPlinth','display-1',650,-850)];
  if(room.kind==='lockers')return [item('locker','locker-0',-650,-850),item('locker','locker-1',650,-850)];
  return [item('lactationChair','chair',-500,-550),item('sideTable','table',600,-550)];
}
function roomFurnitureValid(room,project){
  if(['meeting','huddle','training'].includes(room.kind))return meetingRoomFurnitureValid(room,project);
  if(!['office','pantry','focus','collaboration','waiting','canteen','kitchenette','print','storage','it','lactation','video','display','lockers'].includes(room.kind))return true;
  if(room.extraKind&&(!extraRoomSpecs[room.extraKind]||(+room.plannedSeats||0)>extraRoomSpecs[room.extraKind].capacity))return false;
  const bounds=rect(room),items=roomFurniture(room),side=room.door?.side,inside=area=>area.x>=bounds.x&&area.y>=bounds.y&&area.x+area.w<=bounds.x+bounds.w&&area.y+area.h<=bounds.y+bounds.h;
  const approach=side==='north'?{x:bounds.x+bounds.w/2-450,y:bounds.y,w:900,h:900}:side==='south'?{x:bounds.x+bounds.w/2-450,y:bounds.y+bounds.h-900,w:900,h:900}:side==='west'?{x:bounds.x,y:bounds.y+bounds.h/2-450,w:900,h:900}:{x:bounds.x+bounds.w-900,y:bounds.y+bounds.h/2-450,w:900,h:900};
  return items.every((item,index)=>{const area=furnitureRect(item);return inside(area)&&!overlap(area,approach)&&!items.some((other,j)=>j>index&&overlap(area,furnitureRect(other)))&&(!item.useZones||item.useZones.every(zone=>inside(zone)&&!overlap(zone,approach)))})&&!(project.furniture||[]).some(item=>overlap(bounds,furnitureRect(item)));
}
function roomDoorPoint(o){const r=rect(o),side=o.door?.side;return {x:side==='west'?r.x:side==='east'?r.x+r.w:r.x+r.w/2,y:side==='north'?r.y:side==='south'?r.y+r.h:r.y+r.h/2}}
function roomHasCorridorAccess(o,objects){if(!o.door||!['north','south','east','west'].includes(o.door.side))return false;const point=roomDoorPoint(o);return objects.some(c=>{if(c.type!=='corridor')return false;const r=rect(c);return o.door.side==='north'?point.x>=r.x&&point.x<=r.x+r.w&&Math.abs(point.y-(r.y+r.h))<=50:o.door.side==='south'?point.x>=r.x&&point.x<=r.x+r.w&&Math.abs(point.y-r.y)<=50:o.door.side==='west'?point.y>=r.y&&point.y<=r.y+r.h&&Math.abs(point.x-(r.x+r.w))<=50:point.y>=r.y&&point.y<=r.y+r.h&&Math.abs(point.x-r.x)<=50})}
function placementRelation(kind,rule,role=''){const aliases=role==='executive'?['executive','ceo','总经理']:role==='director'?['director','总监']:kind==='reception'?['reception','前台','接待']:kind==='meeting'?['meeting','会议']:kind==='office'?['office','办公室']:kind==='workstation'?['workstation','desk','工位']:[];return (P.broker?.relations||[]).find(relation=>relation.rule===rule&&aliases.some(alias=>String(relation.from||'').toLowerCase().includes(alias)))||null}
function placementScore(kind,point,role=''){const box=point.x2==null?{x:point.x,y:point.y,w:0,h:0}:rect(point),center={x:box.x+box.w/2,y:box.y+box.h/2},distance=type=>{const markers=P.objects.filter(o=>o.type===type);return markers.length?Math.min(...markers.map(o=>Math.hypot(center.x-o.x,center.y-o.y))):null};let score=0;for(const [rule,type,defaultWeight] of [['entrance','door',kind==='reception'?1:0],['window','window',kind==='workstation'?0.25:0]]){const explicit=placementRelation(kind,rule,role)||role&&placementRelation('office',rule),weight=explicit?(explicit.priority==='must'?3:1.5):defaultWeight,metres=distance(type);if(weight&&metres!=null)score-=weight*metres/1000}return score}
function layoutSkeleton(pattern,shift={x:0,y:0}){
  const w=P.w,h=P.h,baseY=Math.round(h/2-600),baseX=Math.round(w/2-600),midY=Math.max(pattern==='core'?3500:3000,Math.min(h-(pattern==='core'?4500:4000),baseY+(shift.y||0))),midX=Math.max(3000,Math.min(w-4200,baseX+(shift.x||0)));
  const corridor=(x,y,x2,y2,kind='main')=>({id:id(),type:'corridor',kind,x,y,x2,y2,generated:true});
  const slot=(x0,x1,y0,y1,side)=>({x0,x1,y0,y1,side});
  if(pattern==='core'){
    const top=midY-2700,bottom=midY+3900;
    return {corridors:[corridor(0,top,w,top+1200),corridor(0,bottom-1200,w,bottom),corridor(0,top,1200,bottom,'minor'),corridor(w-1200,top,w,bottom,'minor')],slots:[slot(1500,w-1500,top+1200,bottom-1200,'north'),slot(1500,w-1500,top+1200,bottom-1200,'south')],zones:[{x0:650,x1:w-650,y0:650,y1:top-250},{x0:650,x1:w-650,y0:bottom+250,y1:h-650}]};
  }
  if(pattern==='perimeter'){
    const roomsBottom=h>=11000,start=Math.max(3500,Math.min(roomsBottom?Math.min(6500,h-6000):h-4000,3500+(shift.y||0))),end=start+1200,corridors=[corridor(0,start,w,end)],slots=[slot(500,w-500,500,start,'south')],zones=[];
    if(roomsBottom){corridors.push(corridor(0,h-4700,w,h-3500,'minor'),corridor(0,end,1200,h-4700,'minor'),corridor(w-1200,end,w,h-4700,'minor'));slots.push(slot(500,w-500,h-3500,h-500,'north'));zones.push({x0:1450,x1:w-1450,y0:end+250,y1:h-4950})}
    else zones.push({x0:650,x1:w-650,y0:end+250,y1:h-650});
    return {corridors,slots,zones};
  }
  if(pattern==='neighborhood'){
    const corridors=[corridor(0,midY,w,midY+1200),corridor(midX,0,midX+1200,h,'minor')];
    const slots=[slot(500,midX,500,midY,'east'),slot(midX+1200,w-500,500,midY,'west')];
    if(h>=11000)slots.push(slot(500,midX,midY+1200,h-500,'east'),slot(midX+1200,w-500,midY+1200,h-500,'west'));
    const zones=[{x0:650,x1:midX-250,y0:650,y1:midY-250},{x0:midX+1450,x1:w-650,y0:650,y1:midY-250},{x0:650,x1:midX-250,y0:midY+1450,y1:h-650},{x0:midX+1450,x1:w-650,y0:midY+1450,y1:h-650}];
    return {corridors,slots,zones};
  }
  return {corridors:[corridor(0,midY,w,midY+1200)],slots:[slot(500,w-500,500,midY,'south')],zones:[{x0:650,x1:w-650,y0:650,y1:midY-250},{x0:650,x1:w-650,y0:midY+1450,y1:h-650}]};
}
function planRooms(objects,brief,slots){
  const existing=kind=>objects.filter(o=>o.type==='room'&&o.kind===kind&&!o.extraKind&&(kind!=='meeting'||o.plannedSeats>=brief.roomSeats)&&roomHasCorridorAccess(o,objects)&&rect(o).w>=roomSpec(kind,o.plannedSeats,o.door?.side).w&&rect(o).h>=roomSpec(kind,o.plannedSeats,o.door?.side).h&&roomFurnitureValid(o,{...P,objects,furniture:[]})).length;
  const officeNeeded=Math.max(0,Math.min(30,+brief.offices||0)-existing('office')),roles=brief.officeRoles||{},roleRequests=[...Array(Math.min(officeNeeded,+roles.executive||0)).fill({kind:'office',role:'executive',name:'Executive office'}),...Array(Math.min(Math.max(0,officeNeeded-(+roles.executive||0)),+roles.director||0)).fill({kind:'office',role:'director',name:'Director office'})];
  const requests=[...Array(Math.max(0,Math.min(10,+brief.meetingRooms||0)-existing('meeting'))).fill({kind:'meeting',seats:+brief.roomSeats||6}),...roleRequests,...Array(Math.max(0,officeNeeded-roleRequests.length)).fill({kind:'office'}),...(brief.pantry&&!existing('pantry')?[{kind:'pantry'}]:[])];
  for(const space of brief.requirements?.spaces?.filter(s=>s.origin==='extra')||[]){const spec=extraRoomSpecs[space.kind],requested=+space.seats||0,seats=requested||(space.kind==='meeting'?6:space.kind==='huddle'||space.kind==='video'?4:space.kind==='training'?8:spec?.capacity||0);if(!spec||seats>spec.capacity)continue;for(let n=0;n<Math.min(30,+space.count||0);n++)requests.push({kind:space.kind,name:spec.name,seats,extraKind:space.kind,requirementId:space.id})}
  for(const request of requests){
    const {kind,role}=request;
    const candidates=[];
    for(const slot of slots){
      const {w,h}=roomSpec(kind,request.seats||0,slot.side);
      const horizontal=['north','south'].includes(slot.side),fixed=horizontal?slot.side==='north'?slot.y0:slot.y1-h:slot.side==='west'?slot.x0:slot.x1-w;
      const start=horizontal?slot.x0:slot.y0,end=horizontal?slot.x1-w:slot.y1-h;
      for(let p=start;p<=end;p+=250){
        const x=horizontal?p:fixed,y=horizontal?fixed:p,side=slot.side;
        const candidate={id:id(),type:'room',kind,role:role||null,name:request.name||roomNames[kind],plannedSeats:request.seats||0,extraKind:request.extraKind||null,requirementId:request.requirementId||null,x,y,x2:x+w,y2:y+h,door:{side,width:900},conceptOnly:true,generated:true};
        const area=rect(candidate);
        if(!inSite(area)||!roomHasCorridorAccess(candidate,objects)||objects.some(o=>['column','blocked','corridor','room'].includes(o.type)&&overlap(area,rect(o)))||!roomFurnitureValid(candidate,{...P,objects,furniture:[]}))continue;
        candidates.push(candidate);
      }
    }
    candidates.sort((a,b)=>placementScore(kind,b,role)-placementScore(kind,a,role)||a.y-b.y||a.x-b.x);
    if(candidates.length)objects.push(candidates[0]);
  }
}
const sharedZoneSpecs={reception:{name:'Reception',w:3200,h:2800,kind:'reception',capacity:1},coffee:{name:'Coffee bar',w:3000,h:2800,kind:'coffeeBar',capacity:1},dining:{name:'Dining area',w:3000,h:2800,kind:'dining4',capacity:4},lounge:{name:'Lounge',w:3000,h:2600,kind:'lounge2',capacity:2}};
function zoneHasCorridorAccess(zone,objects){const a=rect(zone);return objects.some(o=>{if(o.type!=='corridor')return false;const b=rect(o);return ((Math.abs(a.y-(b.y+b.h))<=50||Math.abs(a.y+a.h-b.y)<=50)&&a.x<b.x+b.w&&a.x+a.w>b.x)||((Math.abs(a.x-(b.x+b.w))<=50||Math.abs(a.x+a.w-b.x)<=50)&&a.y<b.y+b.h&&a.y+a.h>b.y)})}
function validSharedZone(zone,objects,furniture){const area=rect(zone),spec=sharedZoneSpecs[zone.kind],item=furniture.find(f=>f.zoneId===zone.id&&f.kind===spec?.kind);if(!spec||!item||!inSite(area)||area.w<spec.w||area.h<spec.h||!zoneHasCorridorAccess(zone,objects))return false;const inside=box=>box.x>=area.x&&box.y>=area.y&&box.x+box.w<=area.x+area.w&&box.y+box.h<=area.y+area.h;if(!occupiedFurnitureRects(item).every(inside))return false;return !objects.some(o=>o.id!==zone.id&&['column','blocked','corridor','room','zone'].includes(o.type)&&overlap(area,rect(o)))&&!furniture.some(f=>f.id!==item.id&&overlap(area,furnitureRect(f)))}
function planSharedZones(objects,brief,furniture){
  const requests=[...(brief.reception?['reception']:[]),...(brief.coffeeBar?['coffee']:[]),...Array(Math.min(10,Math.ceil(Math.max(0,+brief.diningSeats||0)/4))).fill('dining'),...Array(Math.min(10,Math.ceil(Math.max(0,+brief.loungeSeats||0)/2))).fill('lounge')];
  for(const kind of requests){const spec=sharedZoneSpecs[kind],candidates=[];
    for(const corridor of objects.filter(o=>o.type==='corridor')){
      const c=rect(corridor),horizontal=c.w>=c.h,edges=horizontal?[{axis:'x',fixed:c.y-spec.h},{axis:'x',fixed:c.y+c.h}]:[{axis:'y',fixed:c.x-spec.w},{axis:'y',fixed:c.x+c.w}];
      for(const edge of edges){const start=horizontal?Math.max(300,c.x+300):Math.max(300,c.y+300),end=horizontal?Math.min(P.w-spec.w-300,c.x+c.w-spec.w-300):Math.min(P.h-spec.h-300,c.y+c.h-spec.h-300);
        for(let p=start;p<=end;p+=250){const x=horizontal?p:edge.fixed,y=horizontal?edge.fixed:p,zone={id:id(),type:'zone',kind,name:spec.name,capacity:spec.capacity,x,y,x2:x+spec.w,y2:y+spec.h,generated:true,conceptOnly:true},area=rect(zone);
          if(!inSite(area)||!zoneHasCorridorAccess(zone,objects)||objects.some(o=>['column','blocked','corridor','room','zone'].includes(o.type)&&overlap(area,rect(o)))||furniture.some(f=>overlap(area,furnitureRect(f))))continue;
          const item=makeFurniture(spec.kind,x+spec.w/2,y+spec.h/2);if(!canPlaceFurniture(item,furniture,objects))continue;item.zoneId=zone.id;candidates.push({zone,item});
        }
      }
    }
    candidates.sort((a,b)=>placementScore(kind,b.zone)-placementScore(kind,a.zone)||a.zone.y-b.zone.y||a.zone.x-b.zone.x);
    if(candidates.length){objects.push(candidates[0].zone);furniture.push(candidates[0].item)}
  }
}
function conceptAtShift(pattern,people,meetingSeats,phoneCount,style,shift){
  const structural=P.objects.filter(o=>['wall','door','window','exit','column','blocked','partition'].includes(o.type)||(o.type==='room'&&!o.generated)).map(o=>({...o}));
  const layout=layoutSkeleton(pattern,shift),markedCorridors=P.objects.filter(o=>o.type==='corridor'&&!o.generated).map(o=>({...o}));
  const objects=[...structural,...markedCorridors,...layout.corridors],furniture=[],zones=layout.zones;
  if(P.broker){planRooms(objects,P.broker,layout.slots);planSharedZones(objects,P.broker,furniture)}
  const meetings=P.broker?0:Math.ceil(meetingSeats/6);
  for(let i=0;i<meetings;i++){const x=P.w-2400-i*3900,y=i%2?2200:P.h-2200;putIfFree('meeting',x,y,furniture,objects)}
  for(let i=0;i<phoneCount;i++){const x=1000+i*1450,y=P.h-1500;putIfFree('phone',x,y,furniture,objects)}
  const stationKind=style==='private'?'cubicle':'desk',seats=fillWorkstations(stationKind,people,zones,furniture,objects);
  const names={spine:['Central spine','One main aisle with rooms and desks on either side'],core:['Central room core','Enclosed rooms in a central band; desks near the perimeter'],perimeter:['Perimeter rooms','Enclosed rooms at the edge; shared work area in the middle'],neighborhood:['Team neighborhoods','Cross-aisle divides desks into four team zones']};
  const sharedZones=kind=>objects.filter(o=>o.type==='zone'&&o.kind===kind);
  return {id:id(),label:names[pattern][0],purpose:names[pattern][1],layoutPattern:pattern,corridorShift:{x:shift.x||0,y:shift.y||0},objects,furniture,meta:{requested:people,seats,meetings:P.broker?objects.filter(o=>o.type==='room'&&o.kind==='meeting'&&!o.extraKind).length:furniture.filter(f=>f.kind==='meeting').length*6,offices:objects.filter(o=>o.type==='room'&&o.kind==='office'&&!o.extraKind).length,pantries:objects.filter(o=>o.type==='room'&&o.kind==='pantry'&&!o.extraKind).length,phones:furniture.filter(f=>f.kind==='phone').length,diningSeats:sharedZones('dining').reduce((n,z)=>n+z.capacity,0),loungeSeats:sharedZones('lounge').reduce((n,z)=>n+z.capacity,0),coffeeBars:sharedZones('coffee').length,receptions:sharedZones('reception').length}};
}
function corridorVariants(pattern){if(P.objects.some(o=>o.type==='corridor'&&!o.generated))return [{x:0,y:0}];return pattern==='neighborhood'?[{x:0,y:0},{x:-1000,y:0},{x:1000,y:0},{x:0,y:-1000},{x:0,y:1000}]:[{x:0,y:0},{x:0,y:-1000},{x:0,y:1000}]}
function concept(pattern,people,meetingSeats,phoneCount,style){const mode=style==='private'?'private':P.broker?.mode||'hybrid',variants=corridorVariants(pattern).map(shift=>conceptAtShift(pattern,people,meetingSeats,phoneCount,style,shift));variants.sort((a,b)=>draftScore(a,P.broker,mode)-draftScore(b,P.broker,mode)||Math.abs(a.corridorShift.x)+Math.abs(a.corridorShift.y)-Math.abs(b.corridorShift.x)-Math.abs(b.corridorShift.y));return variants[0]}
function draftScore(d,brief,mode){const m=d.meta,roomGap=brief?Math.max(0,brief.meetingRooms-m.meetings)+Math.max(0,brief.offices-m.offices)+Math.max(0,(brief.pantry?1:0)-m.pantries):0,extraGap=brief?(brief.requirements?.spaces||[]).filter(s=>s.origin==='extra'&&s.priority!=='preferred').reduce((n,s)=>n+Math.max(0,s.count-d.objects.filter(o=>o.type==='room'&&o.requirementId===s.id&&(!s.seats||o.plannedSeats>=s.seats)).length),0):0,seatGap=Math.max(0,m.requested-m.seats),phoneGap=Math.max(0,(brief?.phones??0)-m.phones),sharedGap=brief?Math.max(0,(+brief.diningSeats||0)-m.diningSeats)+Math.max(0,(+brief.loungeSeats||0)-m.loungeSeats)+4*Math.max(0,(brief.coffeeBar?1:0)-m.coffeeBars)+4*Math.max(0,(brief.reception?1:0)-m.receptions):0,preference=mode==='private'&&d.layoutPattern==='perimeter'?15:mode==='open'&&d.layoutPattern==='spine'?15:mode==='hybrid'&&d.layoutPattern==='neighborhood'?15:0,placement=brief&&typeof evaluatePlacementRules==='function'?evaluatePlacementRules({...P,objects:d.objects,furniture:d.furniture,drafts:[d]},brief).filter(Boolean):[],hardPlacementGap=placement.filter(r=>r.priority==='must'&&r.status==='fail').length;return (roomGap+extraGap)*120+seatGap*10+phoneGap*50+sharedGap*20+hardPlacementGap*100-preference}
function generateDrafts(){if(readOnly)return;const readiness=siteReadiness();if(!readiness.ready){$('#hint').textContent=readiness.recognitionPending?'Use the dimension-based fallback or complete assisted import before generating concepts.':'Mark at least one entrance and one emergency exit before generating concepts.';render();return}const people=Math.max(4,+$('#briefPeople').value||36),meeting=Math.max(0,+$('#briefMeeting').value||0),phone=Math.max(0,+$('#briefPhone').value||0),mode=$('#briefMode').value;const patterns=['spine','core','perimeter','neighborhood'];snapshot();comparisonCollapsed=false;P.site.confirmed=true;P.site.confirmedAt=new Date().toISOString();P.draftsStale=false;const candidates=patterns.map(pattern=>concept(pattern,people,meeting,phone,mode==='private'?'private':'hybrid'));candidates.sort((a,b)=>draftScore(a,P.broker,mode)-draftScore(b,P.broker,mode)||patterns.indexOf(a.layoutPattern)-patterns.indexOf(b.layoutPattern));P.drafts=candidates.slice(0,3);applyDraft(P.drafts[0].id,false);save()}
function applyDraft(draftId,keepHistory=true){const d=(P.drafts||[]).find(x=>x.id===draftId);if(!d)return;if(keepHistory)snapshot();P.objects=JSON.parse(JSON.stringify(d.objects));P.furniture=JSON.parse(JSON.stringify(d.furniture));P.activeDraft=d.id;selected=null;render()}
function setTool(){document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));document.querySelectorAll('[data-setup-tool]').forEach(b=>{const active=b.dataset.setupTool===tool;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const wallPlacement=['door','exit'].includes(tool),hint=$('#hint');hint.classList.toggle('guided-placement',wallPlacement&&!readOnly);hint.textContent=tool==='select'?'Scroll to zoom · Hold Space to pan · Drag objects to move':tool==='door'?'Entrance selected — click the correct exterior wall to place it.':tool==='exit'?'Exit selected — click the correct exterior wall to place it.':`${typeName[tool]||'Furniture'}: ${tool==='window'?'click near a wall to place':'drag on the plan to create'}`}
function lineHit(a,b,x,y){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/l));return Math.hypot(x-(a.x+t*dx),y-(a.y+t*dy))<180}
function hit(x,y){for(const f of [...P.furniture].reverse())if(overlap({x,y,w:1,h:1},furnitureRect(f))||chairItems(f).some(chair=>overlap({x,y,w:1,h:1},furnitureRect(chair))))return f;for(const o of [...P.objects].reverse()){if(['wall','partition'].includes(o.type)&&lineHit(o,{x:o.x2,y:o.y2},x,y))return o;if(!['wall','partition','door','window','exit'].includes(o.type)){let r=rect(o);if(overlap({x,y,w:1,h:1},r))return o}if(['door','window','exit'].includes(o.type)&&Math.hypot(x-o.x,y-o.y)<280)return o}return null}
function drawLine(o,color,width=3,dash=[]){const [a,b]=[screen(o.x,o.y),screen(o.x2,o.y2)];ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();ctx.restore()}
function drawRoom2d(o){const r=rect(o),[x,y]=screen(r.x,r.y),w=r.w*V.scale,h=r.h*V.scale,colors={meeting:['#ecfdf5','#047857'],office:['#f5f3ff','#6d28d9'],pantry:['#fff7ed','#c2410c']},[fill,line]=colors[o.kind]||['#f8fafc','#475569'];ctx.save();ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);ctx.strokeStyle=line;ctx.lineWidth=o.id===selected?4:3;ctx.strokeRect(x,y,w,h);ctx.fillStyle=line;ctx.font='600 12px system-ui';ctx.textAlign='center';const fullLabel=o.name||roomNames[o.kind]||'Room',shortLabel={meeting:'Meeting',office:'Office',pantry:'Pantry',huddle:'Huddle',focus:'Focus',training:'Training',collaboration:'Collab',waiting:'Waiting',canteen:'Canteen',kitchenette:'Kitchen',print:'Print',storage:'Storage',it:'IT',lactation:'Private',video:'Video',display:'Display',lockers:'Lockers'}[o.kind]||'Room',label=ctx.measureText(fullLabel).width+12<=w?fullLabel:ctx.measureText(shortLabel).width+8<=w?shortLabel:'';if(label&&h>=24)ctx.fillText(label,x+w/2,y+h/2);if(o.door){const point=roomDoorPoint(o),[dx,dy]=screen(point.x,point.y),vertical=['east','west'].includes(o.door.side),gap=Math.min(900*V.scale,(vertical?h:w)*.5);ctx.strokeStyle=fill;ctx.lineWidth=7;ctx.beginPath();if(vertical){ctx.moveTo(dx,dy-gap/2);ctx.lineTo(dx,dy+gap/2)}else{ctx.moveTo(dx-gap/2,dy);ctx.lineTo(dx+gap/2,dy)}ctx.stroke();ctx.strokeStyle=line;ctx.lineWidth=2;ctx.beginPath();if(vertical){ctx.moveTo(dx,dy-gap/2);ctx.lineTo(dx+(o.door.side==='west'?gap/2:-gap/2),dy)}else{ctx.moveTo(dx-gap/2,dy);ctx.lineTo(dx,dy+(o.door.side==='north'?gap/2:-gap/2))}ctx.stroke()}ctx.restore()}
function draw2d(){ctx.clearRect(0,0,cv.width,cv.height);ctx.save();ctx.fillStyle='#e9eef3';ctx.fillRect(0,0,cv.clientWidth,cv.clientHeight);const [sx,sy]=screen(0,0),[ex,ey]=screen(P.w,P.h);ctx.fillStyle='#fff';ctx.fillRect(sx,sy,ex-sx,ey-sy);const planImage=sourceUnderlay();if(planImage?.complete&&planImage.naturalWidth){ctx.save();ctx.globalAlpha=.28;ctx.drawImage(planImage,sx,sy,ex-sx,ey-sy);ctx.restore()}ctx.strokeStyle='#d7dde5';ctx.lineWidth=1;const grid=1000;for(let x=0;x<=P.w;x+=grid){let [a,b]=[screen(x,0),screen(x,P.h)];ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}for(let y=0;y<=P.h;y+=grid){let [a,b]=[screen(0,y),screen(P.w,y)];ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}
for(const o of P.objects){if(['wall','partition'].includes(o.type))drawLine(o,o.type==='wall'?'#263238':'#64748b',o.type==='wall'?6:3,o.type==='partition'?[8,5]:[]);else if(['door','window','exit'].includes(o.type)){const [x,y]=screen(o.x,o.y),isEdgeMarker=o.type==='door'||o.type==='exit',label=o.type==='door'?'Entrance':o.type==='exit'?'Exit':'';ctx.save();ctx.translate(x,y);ctx.fillStyle=o.type==='exit'?'#15803d':o.type==='door'?'#b45309':'#0284c7';ctx.fillRect(-8,-8,16,16);if(isEdgeMarker){ctx.font='600 12px system-ui';ctx.textBaseline='middle';const onLeft=o.x<P.w*.1,onRight=o.x>P.w*.9,onTop=o.y<P.h*.1;ctx.textAlign=onLeft?'left':onRight?'right':'center';ctx.fillText(label,onLeft?13:onRight?-13:0,onLeft||onRight?0:onTop?18:-18)}ctx.restore()}else{const r=rect(o),[x,y]=screen(r.x,r.y),shared=o.type==='zone',zoneColors={dining:['rgba(251,191,36,.2)','#b45309'],lounge:['rgba(244,114,182,.2)','#be185d'],coffee:['rgba(167,139,250,.2)','#6d28d9'],reception:['rgba(45,212,191,.2)','#0f766e']};ctx.fillStyle=shared?(zoneColors[o.kind]?.[0]||'#f1f5f9'):o.type==='corridor'?'rgba(37,99,235,.15)':o.type==='blocked'?'rgba(220,38,38,.18)':'#94a3b8';ctx.strokeStyle=shared?(zoneColors[o.kind]?.[1]||'#475569'):o.type==='corridor'?'#2563eb':o.type==='blocked'?'#dc2626':'#475569';ctx.setLineDash(o.type==='corridor'?[8,4]:shared?[5,4]:[]);ctx.fillRect(x,y,r.w*V.scale,r.h*V.scale);ctx.strokeRect(x,y,r.w*V.scale,r.h*V.scale);ctx.setLineDash([]);if(shared){ctx.fillStyle=ctx.strokeStyle;ctx.font='600 11px system-ui';ctx.textAlign='center';ctx.fillText(o.name||'Shared area',x+r.w*V.scale/2,y+15)}}}
for(const o of P.objects.filter(o=>o.type==='room'))drawRoom2d(o);
for(const f of allDisplayFurniture(P.furniture)){const r=furnitureRect(f),[x,y]=screen(r.x,r.y),chair=['chair','meetingChair','diningChair','barStool'].includes(f.kind);ctx.save();ctx.translate(x+r.w*V.scale/2,y+r.h*V.scale/2);ctx.rotate((f.rot||0)*Math.PI/180);ctx.fillStyle=chair?'#cbd5e1':f.id===selected?'#bfdbfe':'#dbeafe';ctx.strokeStyle=chair?'#475569':f.id===selected?'#2563eb':'#3b82f6';ctx.lineWidth=2;if(chair){ctx.beginPath();ctx.arc(0,0,Math.max(3,Math.min(r.w,r.h)*V.scale*.4),0,Math.PI*2);ctx.fill();ctx.stroke()}else{ctx.fillRect(-r.w*V.scale/2,-r.h*V.scale/2,r.w*V.scale,r.h*V.scale);ctx.strokeRect(-r.w*V.scale/2,-r.h*V.scale/2,r.w*V.scale,r.h*V.scale)}ctx.fillStyle='#1e3a8a';ctx.font='12px system-ui';ctx.textAlign='center';if(!chair&&r.w*V.scale>=Math.max(100,ctx.measureText(f.name).width+12)&&r.h*V.scale>=30)ctx.fillText(f.name,0,4);ctx.restore()}
for(const f of allDisplayFurniture(P.furniture).filter(item=>['dining4','lounge2'].includes(item.kind))){const [x,y]=screen(f.x,f.y),w=f.w*V.scale,h=f.h*V.scale;ctx.save();ctx.translate(x,y);ctx.rotate((f.rot||0)*Math.PI/180);ctx.fillStyle='#f8fafc';ctx.strokeStyle='#475569';ctx.lineWidth=1.5;if(f.kind==='dining4'){ctx.fillRect(-w*.23,-h*.2,w*.46,h*.4);ctx.strokeRect(-w*.23,-h*.2,w*.46,h*.4);for(const [cx,cy] of [[-w*.34,0],[w*.34,0],[0,-h*.34],[0,h*.34]]){ctx.beginPath();ctx.arc(cx,cy,Math.max(3,Math.min(w,h)*.09),0,Math.PI*2);ctx.fill();ctx.stroke()}}else{for(const cx of [-w*.28,w*.28]){ctx.fillRect(cx-w*.14,-h*.23,w*.28,h*.36);ctx.strokeRect(cx-w*.14,-h*.23,w*.28,h*.36)}ctx.beginPath();ctx.arc(0,h*.22,Math.max(3,Math.min(w,h)*.1),0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
for(const islandId of new Set(P.furniture.filter(f=>f.islandId).map(f=>f.islandId))){const members=P.furniture.filter(f=>f.islandId===islandId),r=islandEnvelope(members),[x,y]=screen(r.x,r.y),active=members.some(f=>f.id===selected);ctx.save();ctx.strokeStyle=active?'#1d4ed8':'#64748b';ctx.lineWidth=active?2:1;ctx.setLineDash([5,4]);ctx.strokeRect(x,y,r.w*V.scale,r.h*V.scale);ctx.setLineDash([]);ctx.fillStyle=active?'#1d4ed8':'#475569';ctx.font='600 11px system-ui';ctx.textAlign='left';if(r.w*V.scale>48)ctx.fillText(`${members.length} seats`,x+4,y+13);ctx.restore()}
if(selected){const o=find(selected);if(o?.type!=='furniture'){const r=rect(o);if(r.w&&r.h){const [x,y]=screen(r.x,r.y);ctx.strokeStyle='#2563eb';ctx.lineWidth=2;ctx.strokeRect(x-3,y-3,r.w*V.scale+6,r.h*V.scale+6)}}}ctx.restore()}
function draw3d(){
  ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='#dbe5ef';ctx.fillRect(0,0,cv.clientWidth,cv.clientHeight);
  const r=cv.getBoundingClientRect(),s=Math.min((r.width-90)/P.w,(r.height-90)/P.h),ox=(r.width-P.w*s)/2,oy=(r.height-P.h*s)/2+20;
  const p=(x,y,z=0)=>[ox+(x-y)*s*.72+P.h*s*.36,oy+(x+y)*s*.28-z*s*.45];
  const poly=(points,fill,stroke='#64748b')=>{ctx.beginPath();points.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.stroke()};
  const colors={wood:['#a57446','#8d623b','#d2a46d'],metal:['#64748b','#475569','#94a3b8'],screen:['#6b8198','#4d667d','#9badbd'],fabric:['#527e89','#386671','#7da6aa']};
  poly([p(0,0),p(P.w,0),p(P.w,P.h),p(0,P.h)],'#f8fafc');
  for(const o of P.objects.filter(o=>o.type==='zone')){const r=rect(o),fill={dining:'#fef3c7',lounge:'#fce7f3',coffee:'#ede9fe',reception:'#ccfbf1'}[o.kind]||'#e2e8f0';poly([p(r.x,r.y),p(r.x+r.w,r.y),p(r.x+r.w,r.y+r.h),p(r.x,r.y+r.h)],fill)}
  for(const o of P.objects.filter(o=>o.type==='room')){const r=rect(o),color=o.kind==='meeting'?'#047857':o.kind==='office'?'#6d28d9':'#c2410c',a=p(r.x,r.y),b=p(r.x+r.w,r.y),c=p(r.x+r.w,r.y+r.h),d=p(r.x,r.y+r.h);poly([a,b,c,d],o.kind==='meeting'?'#d1fae5':o.kind==='office'?'#ede9fe':'#ffedd5',color);ctx.strokeStyle=color;ctx.lineWidth=2;for(const [u,v] of [[a,p(r.x,r.y,2200)],[b,p(r.x+r.w,r.y,2200)],[c,p(r.x+r.w,r.y+r.h,2200)],[d,p(r.x,r.y+r.h,2200)]]){ctx.beginPath();ctx.moveTo(...u);ctx.lineTo(...v);ctx.stroke()}ctx.beginPath();[p(r.x,r.y,2200),p(r.x+r.w,r.y,2200),p(r.x+r.w,r.y+r.h,2200),p(r.x,r.y+r.h,2200),p(r.x,r.y,2200)].forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.stroke()}
  for(const f of allDisplayFurniture(P.furniture).sort((a,b)=>a.x+a.y-b.x-b.y)){
    const item=catalog.find(c=>c.kind===f.kind),height=f.z||item?.height||700,turn=(f.rot||0)*Math.PI/180;
    const point=(u,v,z)=>{const x=(u-.5)*f.w,y=(v-.5)*f.h;return p(f.x+x*Math.cos(turn)-y*Math.sin(turn),f.y+x*Math.sin(turn)+y*Math.cos(turn),z*height)};
    for(const [material,x,y,z,w,d,h] of item?.modelParts||[['metal',0,0,0,1,1,1]]){
      const a=point(x,y,z),b=point(x+w,y,z),c=point(x+w,y+d,z),e=point(x,y+d,z);
      const A=point(x,y,z+h),B=point(x+w,y,z+h),C=point(x+w,y+d,z+h),E=point(x,y+d,z+h),shade=colors[material]||colors.metal;
      poly([a,b,B,A],shade[0]);poly([b,c,C,B],shade[1]);poly([A,B,C,E],shade[2]);
    }
  }
  for(const o of P.objects.filter(o=>['wall','partition'].includes(o.type))){const z=o.type==='wall'?3000:2400;ctx.strokeStyle=o.type==='wall'?'#334155':'#94a3b8';ctx.lineWidth=o.type==='wall'?4:2;ctx.beginPath();ctx.moveTo(...p(o.x,o.y,z));ctx.lineTo(...p(o.x2,o.y2,z));ctx.stroke()}
  ctx.fillStyle='#475569';ctx.font='13px system-ui';ctx.fillText('Illustrative 3D models · Return to 2D to edit',18,25);
}
function find(i){return P.furniture.find(x=>x.id===i)||P.objects.find(x=>x.id===i)}
function checks(){
  const issues=[];
  for(const f of P.furniture){const r=furnitureRect(f);if(!inSite(r))issues.push({level:'bad',text:`${f.name} extends beyond the site boundary`});for(const o of P.objects){if(['column','blocked','room'].includes(o.type)&&overlap(r,rect(o)))issues.push({level:'bad',text:`${f.name} overlaps ${o.type==='room'?o.name:typeName[o.type].toLowerCase()}`});if(o.type==='corridor'&&overlap(r,rect(o)))issues.push({level:'bad',text:`${f.name} blocks a corridor`});if(o.type==='zone'&&f.zoneId!==o.id&&overlap(r,rect(o)))issues.push({level:'bad',text:`${f.name} overlaps ${o.name}`})}for(const g of P.furniture)if(g.id>f.id&&overlap(r,furnitureRect(g)))issues.push({level:'bad',text:`${f.name} collides with ${g.name}`})}
  for(const f of P.furniture.filter(item=>chairSeats(item).length))if(!furnitureHasClearance(f,P))issues.push({level:'bad',text:`${f.name} chair or chair-use area is blocked; its seats need review`});
  for(const islandId of new Set(P.furniture.filter(f=>f.islandId).map(f=>f.islandId))){const member=P.furniture.find(f=>f.islandId===islandId);if(!islandSpacingValid(member,P))issues.push({level:'bad',text:`${member.islandSeats}-person workstation island needs space from another island, room or corridor`})}
  for(const room of P.objects.filter(o=>o.type==='room')){const r=rect(room),minimum=roomSpec(room.kind,room.plannedSeats,room.door?.side);if(!inSite(r))issues.push({level:'bad',text:`${room.name} extends beyond the site boundary`});if(r.w<minimum.w||r.h<minimum.h)issues.push({level:'bad',text:`${room.name} is smaller than the MVP placeholder footprint`});if(!roomHasCorridorAccess(room,P.objects))issues.push({level:'bad',text:`${room.name} door does not connect to the marked corridor`});if(!roomFurnitureValid(room,P))issues.push({level:'bad',text:`${room.name} furniture, seating or door approach do not fit`});for(const o of P.objects)if(o.id!==room.id&&['column','blocked','corridor','room','zone'].includes(o.type)&&overlap(r,rect(o)))issues.push({level:'bad',text:`${room.name} overlaps ${o.type==='room'||o.type==='zone'?o.name:typeName[o.type].toLowerCase()}`})}
  for(const zone of P.objects.filter(o=>o.type==='zone'))if(!validSharedZone(zone,P.objects,P.furniture))issues.push({level:'bad',text:`${zone.name} zone or its furniture needs placement review`});
  for(const c of P.objects.filter(o=>o.type==='corridor')){const r=rect(c),clear=Math.min(r.w,r.h),min=c.kind==='main'?P.rules.main:P.rules.minor;if(clear<min)issues.push({level:'warn',text:`${c.kind==='main'?'Main':'Secondary'} aisle is ${Math.round(clear)} mm wide; the project minimum is ${min} mm`})}
  if(!P.objects.some(o=>o.type==='exit'))issues.push({level:'warn',text:'No emergency exit has been marked'});
  return issues;
}
function renderPanel(){
  const o=find(selected),ins=$('#inspector');if(!o){ins.textContent='Select an object to view its size and position.';return}
  const f=o.type==='furniture',room=o.type==='room',zone=o.type==='zone',label=room||zone?o.name:f?o.name:typeName[o.type];
  ins.innerHTML=`<div class="field"><label>Type</label><b>${esc(label)}</b></div><div class="row"><div class="field"><label>X (mm)</label><input data-prop="x" type="number" value="${Math.round(o.x)}"></div><div class="field"><label>Y (mm)</label><input data-prop="y" type="number" value="${Math.round(o.y)}"></div></div>${f?`<div class="row"><div class="field"><label>Width (mm)</label><input data-prop="w" type="number" value="${o.w}"></div><div class="field"><label>Depth (mm)</label><input data-prop="h" type="number" value="${o.h}"></div></div><div class="field"><label>Rotation</label><input data-prop="rot" type="number" value="${o.rot||0}" step="90"></div>`:o.x2!=null?`<div class="row"><div class="field"><label>X2 (mm)</label><input data-prop="x2" type="number" value="${Math.round(o.x2)}"></div><div class="field"><label>Y2 (mm)</label><input data-prop="y2" type="number" value="${Math.round(o.y2)}"></div></div>`:''}${room?`<div class="field"><label>Door side</label><select id="roomDoorSide"><option value="north" ${o.door?.side==='north'?'selected':''}>North</option><option value="south" ${o.door?.side==='south'?'selected':''}>South</option><option value="east" ${o.door?.side==='east'?'selected':''}>East</option><option value="west" ${o.door?.side==='west'?'selected':''}>West</option></select></div>${o.kind==='meeting'?`<div class="field"><label>Planned seats</label><input id="roomSeats" type="number" min="1" value="${o.plannedSeats||6}"></div>`:''}<div class="empty">Concept room only; access and compliance require review.</div>`:''}<button class="btn" id="deleteSelected">Delete object</button>`;
  if(f&&o.islandId){ins.querySelectorAll('[data-prop="rot"],[data-prop="w"],[data-prop="h"]').forEach(input=>input.disabled=true);ins.insertAdjacentHTML('beforeend',`<div class="empty">${o.islandSeats}-person workstation island · move or delete as one group</div>`)}
  ins.querySelectorAll('[data-prop]').forEach(i=>i.onchange=()=>{snapshot();if(!f&&!room&&!zone)markSiteChanged();const old=o[i.dataset.prop],next=+i.value;if(f&&o.islandId&&['x','y'].includes(i.dataset.prop)){moveIslandMember(o,i.dataset.prop==='x'?next:o.x,i.dataset.prop==='y'?next:o.y);save();return}if(zone&&['x','y'].includes(i.dataset.prop)){const item=P.furniture.find(v=>v.zoneId===o.id);if(item)item[i.dataset.prop]+=next-old}o[i.dataset.prop]=next;save()});
  if(room){$('#roomDoorSide').onchange=e=>{snapshot();o.door={side:e.target.value,width:900};save()};const seats=$('#roomSeats');if(seats)seats.onchange=e=>{snapshot();o.plannedSeats=Math.max(1,+e.target.value||1);save()}}
  $('#deleteSelected').onclick=()=>{snapshot();if(!f&&!room&&!zone)markSiteChanged();P.furniture=P.furniture.filter(x=>x.id!==o.id&&x.zoneId!==o.id&&(!o.islandId||x.islandId!==o.islandId));P.objects=P.objects.filter(x=>x.id!==o.id);selected=null;save()};
}
const money=n=>'$'+n.toLocaleString('en-US');
function renderStats(){
  const displayed=allDisplayFurniture(P.furniture),workstations=workstationSeatsForAssessment(P),chairs=displayed.filter(f=>f.kind==='chair').length,meetingChairs=displayed.filter(f=>f.kind==='meetingChair').length;
  const meetingSeats=P.furniture.filter(f=>f.kind==='meeting').length*6+P.objects.filter(o=>o.type==='room'&&o.kind==='meeting'&&meetingRoomFurnitureValid(o,P)).reduce((n,o)=>n+(+o.plannedSeats||0),0);
  const sum=displayed.reduce((n,f)=>n+(+f.price||0),0),issues=checks();
  $('#stats').innerHTML=`<div class="metric"><span>Workstations with chair clearance</span><b>${workstations}</b></div><div class="metric"><span>Planned meeting seats</span><b>${meetingSeats}</b></div><div class="metric"><span>Task chairs</span><b>${chairs}</b></div><div class="metric"><span>Meeting chairs</span><b>${meetingChairs}</b></div><div class="metric"><span>Furniture items</span><b>${displayed.length}</b></div><div class="metric"><span>Illustrative furniture value</span><b>${money(sum)}</b></div><div class="empty">Chair-use allowance is conceptual · demo prices only</div>`;
  const groups=displayed.reduce((m,f)=>{const key=f.sku||f.kind,entry=m[key]||(m[key]={name:f.name,sku:f.sku||'Legacy item',quantity:0});entry.quantity++;return m},{});
  $('#bom').innerHTML=displayed.length?Object.values(groups).map(g=>`<div class="item"><span>${esc(g.name)}<small>${esc(g.sku)}</small></span><b>× ${g.quantity}</b></div>`).join(''):'<div class="empty">No furniture added yet</div>';
  $('#checks').innerHTML=issues.length?issues.map(i=>`<div class="status ${i.level}">${esc(i.text)}</div>`).join(''):'<div class="status ok">No basic conflicts found</div>';
}
function renderRoomSchedule(){const rooms=P.objects.filter(o=>o.type==='room'),zones=P.objects.filter(o=>o.type==='zone'&&validSharedZone(o,P.objects,P.furniture)),count=kind=>rooms.filter(o=>o.kind===kind&&!o.extraKind).length,zoneCount=kind=>zones.filter(o=>o.kind===kind).length,extra=Object.entries(extraRoomSpecs).filter(([kind])=>rooms.some(o=>o.extraKind===kind)).map(([kind,spec])=>`<div class="item"><span>${spec.name}</span><b>× ${rooms.filter(o=>o.extraKind===kind).length}</b></div>`).join('');$('#roomSchedule').innerHTML=rooms.length||zones.length?`<div class="empty">Concept rooms & valid shared-use zones · not construction-ready</div>${[['meeting','Meeting rooms'],['office','Private offices'],['pantry','Pantry']].filter(([kind])=>count(kind)).map(([kind,name])=>`<div class="item"><span>${name}</span><b>× ${count(kind)}</b></div>`).join('')}${extra}${[['dining','Dining seats',4],['lounge','Lounge seats',2],['coffee','Coffee bar',1],['reception','Reception',1]].filter(([kind])=>zoneCount(kind)).map(([kind,name,seats])=>`<div class="item"><span>${name}</span><b>× ${zoneCount(kind)*seats}</b></div>`).join('')}`:''}
function comparisonMeasures(objects,furniture,meta){
  const brief=P.broker,seatCount=workstationSeatsForAssessment({...P,objects,furniture}),phones=furniture.filter(f=>f.kind==='phone').length;
  const validRooms=objects.filter(o=>o.type==='room'&&(typeof validRoomForAssessment==='function'?validRoomForAssessment(o,{...P,objects,furniture}):roomHasCorridorAccess(o,objects)&&inSite(rect(o)))),validZones=objects.filter(o=>o.type==='zone'&&validSharedZone(o,objects,furniture)),zoneCount=kind=>validZones.filter(z=>z.kind===kind).length;
  const count=kind=>validRooms.filter(o=>o.kind===kind&&!o.extraKind).length,rows=[{name:'Workstations',actual:seatCount,required:brief?.people??meta.requested}];
  if(brief){rows.push({name:'Meeting rooms',actual:validRooms.filter(o=>o.kind==='meeting'&&!o.extraKind&&o.plannedSeats>=brief.roomSeats).length,required:brief.meetingRooms},{name:'Private offices',actual:count('office'),required:brief.offices},{name:'Pantry',actual:count('pantry'),required:brief.pantry?1:0},{name:'Dining seats',actual:zoneCount('dining')*4,required:+brief.diningSeats||0},{name:'Lounge seats',actual:zoneCount('lounge')*2,required:+brief.loungeSeats||0},{name:'Coffee bar',actual:zoneCount('coffee'),required:brief.coffeeBar?1:0},{name:'Reception',actual:zoneCount('reception'),required:brief.reception?1:0});for(const space of brief.requirements?.spaces?.filter(s=>s.origin==='extra')||[])rows.push({name:extraRoomSpecs[space.kind]?.name||space.kind,actual:validRooms.filter(o=>o.requirementId===space.id&&(!space.seats||o.plannedSeats>=space.seats)).length,required:space.count})}
  else rows.push({name:'Meeting seats',actual:furniture.filter(f=>f.kind==='meeting').length*6,required:+$('#briefMeeting').value||0});
  rows.push({name:'Phone booths',actual:phones,required:brief?.phones??(+$('#briefPhone').value||0)});
  return rows.filter(row=>row.required>0).map(row=>({...row,shortfall:Math.max(0,row.required-row.actual)}));
}
function comparisonThumbnail(d){
  const width=250,height=125,pad=6,scale=Math.min((width-2*pad)/P.w,(height-2*pad)/P.h),ox=(width-P.w*scale)/2,oy=(height-P.h*scale)/2;
  const shape=(r,fill,stroke='none')=>`<rect x="${(ox+r.x*scale).toFixed(1)}" y="${(oy+r.y*scale).toFixed(1)}" width="${Math.max(0,r.w*scale).toFixed(1)}" height="${Math.max(0,r.h*scale).toFixed(1)}" fill="${fill}" stroke="${stroke}"/>`;
  const objects=d.objects||[],furniture=d.furniture||[],corridors=objects.filter(o=>o.type==='corridor').map(o=>shape(rect(o),'#bfdbfe')).join(''),zones=objects.filter(o=>o.type==='zone').map(o=>shape(rect(o),({dining:'#fcd34d',lounge:'#f9a8d4',coffee:'#c4b5fd',reception:'#5eead4'})[o.kind]||'#e2e8f0','#475569')).join(''),rooms=objects.filter(o=>o.type==='room').map(o=>shape(rect(o),({meeting:'#a7f3d0',office:'#ddd6fe',pantry:'#fed7aa'})[o.kind]||'#e2e8f0','#475569')).join(''),fixed=objects.filter(o=>['column','blocked'].includes(o.type)).map(o=>shape(rect(o),'#64748b')).join(''),desks=furniture.filter(f=>['desk','cubicle','bench2'].includes(f.kind)).map(f=>shape(furnitureRect(f),'#475569')).join(''),chairs=furniture.flatMap(chairItems).map(f=>shape(furnitureRect(f),'#94a3b8')).join(''),roomItems=objects.filter(o=>o.type==='room').flatMap(roomFurniture).map(f=>shape(furnitureRect(f),['chair','meetingChair','diningChair'].includes(f.kind)?'#64748b':'#14532d')).join('');
  return `<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><rect x="${ox.toFixed(1)}" y="${oy.toFixed(1)}" width="${(P.w*scale).toFixed(1)}" height="${(P.h*scale).toFixed(1)}" fill="#fff" stroke="#94a3b8"/>${corridors}${zones}${rooms}${fixed}${desks}${chairs}${roomItems}</svg>`;
}
function currentPlanEdited(project=P){const active=project.drafts?.find(d=>d.id===project.activeDraft);return !!active&&(JSON.stringify(project.objects)!==JSON.stringify(active.objects)||JSON.stringify(project.furniture)!==JSON.stringify(active.furniture))}
function renderComparison(){
  const panel=$('#comparisonPanel'),drafts=P.drafts||[];panel.hidden=!drafts.length;if(!drafts.length)return;
  panel.querySelector('.comparison-head h2').textContent=P.source?.kind==='simulated'?'Step 3 of 3 · Compare layouts A / B / C':'Compare layouts A / B / C';
  panel.querySelector('.comparison-head p').textContent=P.draftsStale?'The site or client needs changed. Previous A / B / C results are hidden until you regenerate.':`Same space: ${P.name}. Select a layout to view it below; these are early concepts, not approved plans.`;
  panel.classList.toggle('collapsed',comparisonCollapsed);$('#comparisonToggle').textContent=comparisonCollapsed?'Show comparison':'Hide comparison';$('#comparisonToggle').setAttribute('aria-expanded',String(!comparisonCollapsed));
  const active=P.drafts.find(d=>d.id===P.activeDraft),edited=currentPlanEdited();
  if(P.draftsStale){$('#comparisonGrid').innerHTML='';const current=$('#comparisonCurrent');current.hidden=false;current.classList.remove('bad');current.textContent='Previous A / B / C snapshots are out of date and cannot be compared or shared. Review the site and needs, then regenerate layouts.';return}
  const unassessed=(P.broker?.requirements?.spaces||[]).filter(s=>s.origin==='extra').length+(P.broker?.requirements?.relations||[]).filter(r=>typeof placementTarget!=='function'||!placementTarget(r)).length+(P.broker?.requirements?.departments?.length||0)+(P.broker?.requirements?.tradeoffs?.length||0);
  $('#comparisonGrid').innerHTML=drafts.map((d,index)=>{const rows=comparisonMeasures(d.objects,d.furniture,d.meta),gaps=rows.filter(r=>r.shortfall),placement=P.broker&&typeof evaluatePlacementRules==='function'?evaluatePlacementRules({...P,objects:d.objects,furniture:d.furniture,drafts:[d]},P.broker).filter(Boolean):[],hardMiss=placement.some(r=>r.priority==='must'&&r.status==='fail'),takeaway=(gaps.length?`Still needed: ${gaps.map(r=>`${r.name} ${r.shortfall}`).join(' · ')}.`:'Shown quantities placed as concepts; professional review still needed.')+(hardMiss?' A required location rule misses the MVP screen.':'')+(unassessed?` ${unassessed} additional requirement(s) not assessed.`:'');return `<button class="comparison-card ${d.id===P.activeDraft?'active':''}" type="button" data-compare-draft="${esc(d.id)}" aria-pressed="${d.id===P.activeDraft}" ${readOnly||P.draftsStale?'disabled':''}><span class="comparison-card-head"><b>${'ABC'[index]} · ${esc(d.label)}</b><small>${d.id===P.activeDraft?'Viewing':'View plan'}</small></span><span class="comparison-purpose">${esc(d.purpose)}</span>${comparisonThumbnail(d)}${rows.map(r=>`<span class="comparison-row ${r.shortfall?'short':''}"><span>${esc(r.name)}</span><b>${r.actual}/${r.required}</b></span>`).join('')}${placement.map(r=>`<span class="comparison-position ${r.status==='fail'?'short':''}">${esc(r.label)} · ${esc(r.status==='pass'?'Within MVP distance':r.status==='fail'?'Misses MVP distance':'Cannot assess')}<small>${esc(r.reason)}</small></span>`).join('')}<span class="comparison-takeaway">${esc(takeaway)}</span></button>`}).join('');
  if(edited)panel.querySelector('.comparison-card.active .comparison-card-head small').textContent='Original snapshot';
  const current=$('#comparisonCurrent');current.hidden=!edited;
  if(edited){
    const rows=comparisonMeasures(P.objects,P.furniture,active.meta),placement=P.broker&&typeof evaluatePlacementRules==='function'?evaluatePlacementRules(P,P.broker).filter(Boolean):[];
    const positions=placement.map(r=>`${r.priority==='must'?'Required':'Preferred'} ${r.label}: ${r.status==='pass'?'within MVP distance':r.status==='fail'?'misses MVP distance':'cannot assess'} (${r.reason})`);
    current.textContent=`Current edited plan · separate from A / B / C snapshots. ${rows.map(r=>`${r.name} ${r.actual}/${r.required}${r.shortfall?' short':''}`).join(' · ')}.${positions.length?` Location checks: ${positions.join(' · ')}.`:''} The customer summary checks this edited plan; access and compliance still need review.`;
    current.classList.toggle('bad',placement.some(r=>r.priority==='must'&&r.status==='fail'));
  }else current.classList.remove('bad');
  panel.querySelectorAll('[data-compare-draft]').forEach(button=>button.onclick=()=>{if(currentPlanEdited()&&!confirm('Opening an A / B / C snapshot replaces the current edited plan. You can use Undo afterward. Continue?'))return;applyDraft(button.dataset.compareDraft);save()});
}
function renderDrafts(){const host=$('#drafts'),drafts=P.drafts||[];if(!drafts.length){host.innerHTML='<div class="empty">Complete the brief to generate plans.</div>';return}if(P.draftsStale){host.innerHTML='<div class="status warn">Previous A / B / C snapshots are out of date. Review the site and needs, then regenerate before comparing or sharing.</div>';return}host.innerHTML=drafts.map(d=>{const gap=Math.max(0,d.meta.requested-d.meta.seats),active=d.id===P.activeDraft,rooms=P.broker?` · Meeting rooms ${d.meta.meetings}/${P.broker.meetingRooms} · Offices ${d.meta.offices}/${P.broker.offices} · Pantry ${d.meta.pantries}/${P.broker.pantry?1:0}`:` · Meeting seats ${d.meta.meetings}`,roomGap=P.broker?Math.max(0,P.broker.meetingRooms-d.meta.meetings)+Math.max(0,P.broker.offices-d.meta.offices)+Math.max(0,(P.broker.pantry?1:0)-d.meta.pantries):0;return `<button class="tool ${active?'active':''}" data-draft="${d.id}" ${readOnly?'disabled':''}><b>${d.label}${active?' · Selected':''}</b><small>${d.purpose}</small><small>Seats ${d.meta.seats}/${d.meta.requested}${rooms} · Booths ${d.meta.phones}/${P.broker?.phones??$('#briefPhone').value}${gap?` · ${gap} seats short`:''}${roomGap?` · ${roomGap} rooms short`:''}</small></button>`}).join('');host.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{applyDraft(b.dataset.draft);save()})}
function render(){P.rules.main=+$('#mainClear').value||1200;P.rules.minor=+$('#minorClear').value||900;$('#projectTitle').textContent=readOnly?`${P.name} · Read-only`:`${P.name} · Saved locally`;(view==='2d'?draw2d:draw3d)();renderSiteStatus();renderPhaseBar();renderPanel();renderStats();renderRoomSchedule();renderDrafts();renderComparison()}
function pointer(e){const r=cv.getBoundingClientRect();return world(e.clientX-r.left,e.clientY-r.top)}
function moveIslandMember(item,nextX,nextY){const members=item.islandId?P.furniture.filter(f=>f.islandId===item.islandId):[item],box=item.islandId?islandEnvelope(members):furnitureRect(item),dx=Math.max(-box.x,Math.min(P.w-box.x-box.w,nextX-item.x)),dy=Math.max(-box.y,Math.min(P.h-box.y-box.h,nextY-item.y));for(const member of members){member.x+=dx;member.y+=dy}}
cv.addEventListener('pointerdown',e=>{const [x,y]=pointer(e);if(e.button===1||spaceDown){drag={pan:true,x:e.clientX,y:e.clientY,vx:V.x,vy:V.y};return}if(readOnly)return;if(tool==='select'){const h=hit(x,y);selected=h?.id||null;if(h){snapshot();drag={move:h,ox:x-h.x,oy:y-h.y,changed:false}}render();return}snapshot();if(['door','window','exit'].includes(tool)){const placedType=tool,wall=P.objects.find(o=>o.type==='wall'&&lineHit(o,{x:o.x2,y:o.y2},x,y));if(!wall){history.pop();$('#hint').textContent=`Move closer to an exterior wall, then click to place the ${placedType==='door'?'entrance':placedType}.`;return}markSiteChanged();P.objects.push({id:id(),type:placedType,x:clamp(x),y:clamp(y),wallId:wall.id});selected=P.objects.at(-1).id;if(placedType==='door'&&!P.objects.some(o=>o.type==='exit'))tool='exit';else if(placedType==='exit')tool='select';setTool();save();return}const roomKind={meetingRoom:'meeting',officeRoom:'office',pantryRoom:'pantry'}[tool];if(!roomKind)markSiteChanged();drag={create:roomKind?{id:id(),type:'room',kind:roomKind,name:roomNames[roomKind],plannedSeats:roomKind==='meeting'?Number(P.broker?.roomSeats)||6:0,x:clamp(x),y:clamp(y),x2:clamp(x),y2:clamp(y),door:{side:'south',width:900},conceptOnly:true}:{id:id(),type:tool,x:clamp(x),y:clamp(y),x2:clamp(x),y2:clamp(y)}};P.objects.push(drag.create);selected=drag.create.id;render()});
cv.addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){V.x=drag.vx+e.clientX-drag.x;V.y=drag.vy+e.clientY-drag.y;render();return}const [x,y]=pointer(e);if(drag.create){drag.create.x2=clamp(x);drag.create.y2=clamp(y)}else if(drag.move){const o=drag.move;if(!drag.changed&&!['furniture','room','zone'].includes(o.type)){markSiteChanged();drag.changed=true}if(o.type==='furniture'){moveIslandMember(o,clamp(x-drag.ox),clamp(y-drag.oy))}else if(o.x2!=null){const dx=clamp(x-drag.ox)-o.x,dy=clamp(y-drag.oy)-o.y;o.x+=dx;o.y+=dy;o.x2+=dx;o.y2+=dy;if(o.type==='zone'){const item=P.furniture.find(f=>f.zoneId===o.id);if(item){item.x+=dx;item.y+=dy}}}else{o.x=clamp(x-drag.ox);o.y=clamp(y-drag.oy)}}render()});
addEventListener('pointerup',()=>{if(drag?.create?.type==='room'){const room=drag.create,corridor=P.objects.find(o=>o.type==='corridor');room.door.side=corridor&&(rect(room).y+rect(room).h/2)>=rect(corridor).y+rect(corridor).h/2?'north':'south'}if(drag&&!drag.pan)save();drag=null});cv.addEventListener('wheel',e=>{e.preventDefault();const r=cv.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,[wx,wy]=world(mx,my),z=e.deltaY<0?1.12:.89;V.scale=Math.max(.008,Math.min(.18,V.scale*z));V.x=mx-wx*V.scale;V.y=my-wy*V.scale;render()},{passive:false});
addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)){spaceDown=true;e.preventDefault()}});addEventListener('keyup',e=>{if(e.code==='Space')spaceDown=false});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#tools').onclick=e=>{const b=e.target.closest('[data-tool]');if(b){tool=b.dataset.tool;setTool()}};$('#catalog').innerHTML=visibleCatalog.map(c=>`<button class="tool" data-kind="${c.kind}">${esc(c.name)}<small>${esc(c.sku)} · ${c.width} × ${c.depth} × ${c.height} mm</small></button>`).join('');$('#catalog').onclick=e=>{const b=e.target.closest('[data-kind]');if(b)addFurniture(b.dataset.kind)};$('#fitBtn').onclick=fit;$('#undoBtn').onclick=undo;$('#mainClear').onchange=$('#minorClear').onchange=save;
$('#comparisonToggle').onclick=()=>{comparisonCollapsed=!comparisonCollapsed;renderComparison()};
$('#drafts').addEventListener('click',event=>{if(event.target.closest('[data-draft]')&&currentPlanEdited()&&!confirm('Opening an A / B / C snapshot replaces the current edited plan. You can use Undo afterward. Continue?')){event.preventDefault();event.stopImmediatePropagation()}},true);
$('#generateDrafts').onclick=generateDrafts;
$('#newProject').onclick=()=>{$('#welcomeModal').hidden=false;$('#projectModal').hidden=true;$('#briefModal').hidden=true};
function syncSourceMode(){const upload=document.querySelector('[name="sourceMode"]:checked')?.value==='upload';$('#uploadFields').hidden=!upload;$('#siteFile').required=upload;$('#widthLabel').textContent=upload?'Approx. overall width (mm)':'Clear width (mm)';$('#depthLabel').textContent=upload?'Approx. overall depth (mm)':'Clear depth (mm)';$('#createProjectSubmit').textContent=upload?'Attach plan & create review canvas':'Create review canvas'}
document.querySelectorAll('[name="sourceMode"]').forEach(i=>i.onchange=syncSourceMode);
function makePlanPreview(file){if(!file?.type?.startsWith('image/'))return Promise.resolve(null);return new Promise(resolve=>{const reader=new FileReader();reader.onerror=()=>resolve(null);reader.onload=()=>{const image=new Image();image.onerror=()=>resolve(null);image.onload=()=>{const limit=1600,scale=Math.min(1,limit/Math.max(image.naturalWidth,image.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(image.naturalWidth*scale));c.height=Math.max(1,Math.round(image.naturalHeight*scale));const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(image,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};image.src=reader.result};reader.readAsDataURL(file)})}
$('#siteFile').onchange=e=>{const f=e.target.files[0];$('#siteFileMeta').textContent=f?`${f.name} · ${f.size<1048576?Math.max(1,Math.round(f.size/1024))+' KB':(f.size/1048576).toFixed(1)+' MB'}`:'No file selected';$('#siteFileHelp').textContent=f?.type?.startsWith('image/')?'The image will appear below the walls as a tracing reference. Confirm scale and every fixed condition before planning.':'PDF and DWG use assisted import in this MVP. The file name is recorded, and the dimensions create a fallback review canvas.'};
$('#startProject').onclick=()=>{$('#projectForm').reset();$('#siteFileMeta').textContent='No file selected';$('#siteFileHelp').textContent='JPG and PNG are placed under the review canvas for manual checking. PDF and DWG use the assisted-import fallback in this MVP.';syncSourceMode();$('#welcomeModal').hidden=true;$('#projectModal').hidden=false};
$('#cancelProject').onclick=()=>{$('#projectModal').hidden=true;$('#welcomeModal').hidden=false};
$('#projectForm').onsubmit=async e=>{e.preventDefault();const mode=document.querySelector('[name="sourceMode"]:checked')?.value||'dimensions',file=$('#siteFile').files[0];if(mode==='upload'&&!file){$('#siteFile').setCustomValidity('Choose a PDF, JPG, PNG or DWG floor plan.');$('#siteFile').reportValidity();return}$('#siteFile').setCustomValidity('');const submit=$('#createProjectSubmit'),label=submit.textContent;submit.disabled=true;submit.textContent=mode==='upload'?'Preparing review…':label;const preview=mode==='upload'?await makePlanPreview(file):null;submit.disabled=false;submit.textContent=label;const source=mode==='upload'?{kind:'upload',fileName:file.name,fileType:file.type||file.name.split('.').pop()?.toLowerCase(),fileSize:file.size,status:preview?'tracing_reference':'awaiting_recognition',...(preview?{preview}:{})}:{kind:'dimensions'};snapshot();P=fresh($('#projectName').value,+$('#siteWidth').value,+$('#siteHeight').value,source);selected=null;$('#projectModal').hidden=true;tool='door';setTool();save();fit()};
document.querySelectorAll('[data-setup-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.setupTool;setTool()});
function openBrief(){
  const ready=siteReadiness();
  if(ready.recognitionPending){const {fileName,fileType,fileSize}=P.source;P.source={kind:'dimensions',originalFile:{fileName,fileType,fileSize}};markSiteChanged();$('#hint').textContent='Using the dimension-based canvas. Mark entrances, exits and fixed constraints before continuing.';save();return}
  if(!ready.ready){tool=ready.entrances?'exit':'door';setTool();$('#setupBar').classList.add('warn');$('#setupText').textContent=`Add ${!ready.entrances?'an entrance':ready.exits?'the remaining fixed conditions':'an emergency exit'} before continuing.`;$('#hint').textContent='The site must have at least one entrance and one emergency exit before concepts are generated.';return}
  P.site.confirmed=true;
  P.site.confirmedAt=new Date().toISOString();
  $('#wizardPeople').value=$('#briefPeople').value;
  $('#wizardMode').value=$('#briefMode').value;
  $('#wizardMeeting').value=$('#briefMeeting').value;
  $('#wizardPhone').value=$('#briefPhone').value;
  const source=P.source?.kind==='dimensions'&&!P.source?.originalFile?'entered dimensions':sourceLabel();
  $('#briefSiteSummary').textContent=`${P.name} · ${(P.w/1000).toFixed(1)} × ${(P.h/1000).toFixed(1)} m · ${source}. Set the planning priorities for three comparable concepts.`;
  $('#briefModal').hidden=false;
  save();
}
$('#openBrief').onclick=openBrief;
$('#backToSetup').onclick=()=>$('#briefModal').hidden=true;
$('#briefForm').onsubmit=e=>{e.preventDefault();$('#briefPeople').value=$('#wizardPeople').value;$('#briefMode').value=$('#wizardMode').value;$('#briefMeeting').value=$('#wizardMeeting').value;$('#briefPhone').value=$('#wizardPhone').value;$('#briefModal').hidden=true;generateDrafts();fit()};
$('#useExample').onclick=()=>{snapshot();P=fresh('Example · 36-person hybrid office',18000,12000,{kind:'example'});P.objects.push({id:id(),type:'door',x:0,y:6000,wallId:P.objects[3].id},{id:id(),type:'exit',x:18000,y:6000,wallId:P.objects[1].id},{id:id(),type:'column',x:8400,y:2500,x2:9000,y2:3100},{id:id(),type:'blocked',x:0,y:0,x2:3200,y2:2400});$('#briefPeople').value=36;$('#briefMode').value='hybrid';$('#briefMeeting').value=12;$('#briefPhone').value=2;$('#welcomeModal').hidden=true;generateDrafts();fit()};
$('#exportBtn').onclick=()=>{const a=document.createElement('a'),data=JSON.stringify(P,null,2);a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download=`${P.name||'office-plan'}.json`;a.click()};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p.version!==1)throw Error();snapshot();P=normalizeProject(p);selected=null;$('#welcomeModal').hidden=true;save();fit()}catch{alert('This is not a valid project file.')}};r.readAsText(f)};
$('#shareBtn').onclick=async()=>{if(P.draftsStale){$('#hint').textContent='Regenerate the concept plans before sharing this site revision.';render();return}const shared=JSON.parse(JSON.stringify(P));if(shared.source?.preview)delete shared.source.preview;const raw=new TextEncoder().encode(JSON.stringify(shared)),text=btoa(String.fromCharCode(...raw));const u=new URL('studio.html',location.href);u.hash='project='+encodeURIComponent(text);await navigator.clipboard.writeText(u);alert('Read-only link copied. The planning data is embedded in the link; the source-plan preview is excluded and the link cannot be revoked after sharing.')};
P=load();if(location.hash.startsWith('#project=')){try{P=normalizeProject(JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(decodeURIComponent(location.hash.slice(9))),x=>x.charCodeAt(0)))));readOnly=true}catch{}}if(readOnly){document.querySelectorAll('#tools button,#catalog button,#newProject,#importBtn,#shareBtn,#generateDrafts').forEach(b=>b.disabled=true);$('#welcomeModal').hidden=true;$('#projectModal').hidden=true;$('#briefModal').hidden=true;$('#setupBar').hidden=true;$('#hint').textContent='Read-only share · View 2D, 3D, summary and checks';$('#projectTitle').textContent='Read-only share';}else{$('#welcomeModal').hidden=hasSavedProject}$('#projectName').value=P.name;$('#siteWidth').value=P.w;$('#siteHeight').value=P.h;$('#mainClear').value=P.rules.main||1200;$('#minorClear').value=P.rules.minor||900;syncSourceMode();new ResizeObserver(()=>{resizeCanvas();if(!V.scale)fit();render()}).observe(cv);resizeCanvas();fit();setTool();render();
