/* 通用办公空间 MVP：所有坐标单位为 mm，持久化仅存浏览器 localStorage。 */
const $ = s => document.querySelector(s), cv = $('#canvas'), ctx = cv.getContext('2d');
const STORE = 'office-planner-mvp-v1';
const catalog = [
  ['desk','单人办公桌',1400,700,380],['bench2','双人工位',2800,1400,980],['cubicle','屏风格子间',1600,1600,620],['meeting','会议桌 6 人',3600,1200,720],['phone','电话亭',1200,1200,1600],['manager','经理桌',1800,800,1200],['cabinet','文件柜',900,450,420],['reception','前台',2400,700,2200],['sofa','沙发茶几组',2200,1600,1800]
];
const typeName={wall:'墙体',door:'门',window:'窗',partition:'隔断',column:'柱',corridor:'通道',exit:'安全出口',blocked:'禁占区'};
let P, tool='select', selected=null, drag=null, view='2d', history=[], readOnly=false;
let V={scale:0.04,x:0,y:0};
function id(){return Math.random().toString(36).slice(2,10)}
function fresh(name='未命名办公空间',w=18000,h=12000){return {version:1,name,w,h,rules:{main:1200,minor:900},objects:[{id:id(),type:'wall',x:0,y:0,x2:w,y2:0},{id:id(),type:'wall',x:w,y:0,x2:w,y2:h},{id:id(),type:'wall',x:w,y:h,x2:0,y2:h},{id:id(),type:'wall',x:0,y:h,x2:0,y2:0}],furniture:[],drafts:[]}}
function load(){try{const p=JSON.parse(localStorage.getItem(STORE));if(p?.version===1)return p}catch{}return fresh()}
function save(){localStorage.setItem(STORE,JSON.stringify(P));render()}
function snapshot(){history.push(JSON.stringify(P));if(history.length>30)history.shift()}
function undo(){if(!history.length)return;P=JSON.parse(history.pop());selected=null;save()}
function fit(){const r=cv.getBoundingClientRect(), pad=70;V.scale=Math.min((r.width-pad)/P.w,(r.height-pad)/P.h);V.x=(r.width-P.w*V.scale)/2;V.y=(r.height-P.h*V.scale)/2;render()}
function resizeCanvas(){const r=cv.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h}ctx.setTransform(d,0,0,d,0,0)}
function screen(x,y){return [V.x+x*V.scale,V.y+y*V.scale]}; function world(x,y){return [(x-V.x)/V.scale,(y-V.y)/V.scale]};
function rect(o){return {x:Math.min(o.x,o.x2),y:Math.min(o.y,o.y2),w:Math.abs(o.x2-o.x),h:Math.abs(o.y2-o.y)}}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function inSite(r){return r.x>=0&&r.y>=0&&r.x+r.w<=P.w&&r.y+r.h<=P.h}
function clamp(n){return Math.round(n/50)*50}
function furnitureRect(f){return {x:f.x-f.w/2,y:f.y-f.h/2,w:f.w,h:f.h}}
function addFurniture(kind){if(readOnly)return;snapshot();const c=catalog.find(x=>x[0]===kind);P.furniture.push({id:id(),type:'furniture',kind,name:c[1],w:c[2],h:c[3],price:c[4],x:P.w/2,y:P.h/2,rot:0});selected=P.furniture.at(-1).id;tool='select';setTool();save()}
function seatsOfFurniture(f){return f.kind==='bench2'?2:f.kind==='cubicle'||f.kind==='desk'?1:f.kind==='meeting'?6:0}
function makeFurniture(kind,x,y){const c=catalog.find(v=>v[0]===kind);return {id:id(),type:'furniture',kind,name:c[1],w:c[2],h:c[3],price:c[4],x,y,rot:0}}
function plannerBlocks(objects){return objects.filter(o=>['column','blocked','corridor'].includes(o.type)).map(rect)}
function canPlaceFurniture(f,placed,objects){const r=furnitureRect(f);return inSite(r)&&!plannerBlocks(objects).some(b=>overlap(r,b))&&!placed.some(x=>overlap(r,furnitureRect(x)))}
function putIfFree(kind,x,y,placed,objects){const f=makeFurniture(kind,x,y);if(!canPlaceFurniture(f,placed,objects))return false;placed.push(f);return true}
function fillWorkstations(kind,target,zones,placed,objects){let total=placed.filter(f=>['bench2','cubicle','desk'].includes(f.kind)).reduce((n,f)=>n+seatsOfFurniture(f),0);for(const z of zones){const unit=catalog.find(v=>v[0]===kind),stepX=unit[2]+450,stepY=unit[3]+650;for(let y=z.y0+unit[3]/2;y<=z.y1-unit[3]/2&&total<target;y+=stepY)for(let x=z.x0+unit[2]/2;x<=z.x1-unit[2]/2&&total<target;x+=stepX){if(putIfFree(kind,x,y,placed,objects))total+=seatsOfFurniture(placed.at(-1))}}return total}
function concept(label,purpose,people,meetingSeats,phoneCount,style){const structural=P.objects.filter(o=>['wall','door','window','exit','column','blocked'].includes(o.type)).map(o=>({...o}));const corridorY=Math.round(P.h/2-600),objects=[...structural,{id:id(),type:'corridor',x:0,y:corridorY,x2:P.w,y2:corridorY+1200}],furniture=[];const zones=[{x0:650,y0:650,x1:P.w-650,y1:corridorY-250},{x0:650,y0:corridorY+1450,x1:P.w-650,y1:P.h-650}];const meetings=style==='capacity'?Math.min(1,Math.ceil(meetingSeats/6)):Math.ceil(meetingSeats/6);for(let i=0;i<meetings;i++){const x=P.w-2400-i*3900,y=i%2?2200:P.h-2200;putIfFree('meeting',x,y,furniture,objects)}for(let i=0;i<(style==='capacity'?0:phoneCount);i++){const x=1000+i*1450,y=P.h-1500;putIfFree('phone',x,y,furniture,objects)}const stationKind=style==='private'?'cubicle':'bench2';const requested=style==='capacity'?Math.ceil(people*1.15):people;const seats=fillWorkstations(stationKind,requested,zones,furniture,objects);return {id:id(),label,purpose,objects,furniture,meta:{requested:people,seats,meetings:furniture.filter(f=>f.kind==='meeting').length*6,phones:furniture.filter(f=>f.kind==='phone').length}}}
function generateDrafts(){if(readOnly)return;const people=Math.max(4,+$('#briefPeople').value||36),meeting=Math.max(0,+$('#briefMeeting').value||0),phone=Math.max(0,+$('#briefPhone').value||0),mode=$('#briefMode').value;const middle=mode==='open'?'capacity':mode==='private'?'private':'hybrid';snapshot();P.drafts=[concept('Plan A','Capacity first · maximum open workstations',people,meeting,phone,'capacity'),concept('Plan B','Balanced hybrid · meetings and focus booths',people,meeting,phone,middle==='private'?'hybrid':middle),concept('Plan C','Privacy first · more enclosed individual workspaces',people,meeting,phone,'private')];applyDraft(P.drafts[mode==='open'?0:mode==='private'?2:1].id,false);save()}
function applyDraft(draftId,keepHistory=true){const d=(P.drafts||[]).find(x=>x.id===draftId);if(!d)return;if(keepHistory)snapshot();P.objects=d.objects.map(o=>({...o}));P.furniture=d.furniture.map(f=>({...f}));P.activeDraft=d.id;selected=null;render()}
function setTool(){document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#hint').textContent=tool==='select'?'滚轮缩放 · 按住空格拖动画布 · 拖动对象移动':`${typeName[tool]||'家具'}：${tool==='door'||tool==='window'||tool==='exit'?'点击靠近墙体的位置放置':'在场地中拖动创建'}`}
function lineHit(a,b,x,y){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/l));return Math.hypot(x-(a.x+t*dx),y-(a.y+t*dy))<180}
function hit(x,y){for(const f of [...P.furniture].reverse())if(overlap({x,y,w:1,h:1},furnitureRect(f)))return f;for(const o of [...P.objects].reverse()){if(['wall','partition'].includes(o.type)&&lineHit(o,{x:o.x2,y:o.y2},x,y))return o;if(!['wall','partition','door','window','exit'].includes(o.type)){let r=rect(o);if(overlap({x,y,w:1,h:1},r))return o}if(['door','window','exit'].includes(o.type)&&Math.hypot(x-o.x,y-o.y)<280)return o}return null}
function drawLine(o,color,width=3,dash=[]){const [a,b]=[screen(o.x,o.y),screen(o.x2,o.y2)];ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();ctx.restore()}
function draw2d(){ctx.clearRect(0,0,cv.width,cv.height);ctx.save();ctx.fillStyle='#e9eef3';ctx.fillRect(0,0,cv.clientWidth,cv.clientHeight);const [sx,sy]=screen(0,0),[ex,ey]=screen(P.w,P.h);ctx.fillStyle='#fff';ctx.fillRect(sx,sy,ex-sx,ey-sy);ctx.strokeStyle='#d7dde5';ctx.lineWidth=1;const grid=1000;for(let x=0;x<=P.w;x+=grid){let [a,b]=[screen(x,0),screen(x,P.h)];ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}for(let y=0;y<=P.h;y+=grid){let [a,b]=[screen(0,y),screen(P.w,y)];ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}
for(const o of P.objects){if(['wall','partition'].includes(o.type))drawLine(o,o.type==='wall'?'#263238':'#64748b',o.type==='wall'?6:3,o.type==='partition'?[8,5]:[]);else if(['door','window','exit'].includes(o.type)){const [x,y]=screen(o.x,o.y);ctx.save();ctx.translate(x,y);ctx.fillStyle=o.type==='exit'?'#16a34a':o.type==='door'?'#b45309':'#0284c7';ctx.fillRect(-7,-7,14,14);ctx.restore()}else{const r=rect(o),[x,y]=screen(r.x,r.y);ctx.fillStyle=o.type==='corridor'?'rgba(37,99,235,.15)':o.type==='blocked'?'rgba(220,38,38,.18)':'#94a3b8';ctx.strokeStyle=o.type==='corridor'?'#2563eb':o.type==='blocked'?'#dc2626':'#475569';ctx.setLineDash(o.type==='corridor'?[8,4]:[]);ctx.fillRect(x,y,r.w*V.scale,r.h*V.scale);ctx.strokeRect(x,y,r.w*V.scale,r.h*V.scale);ctx.setLineDash([])}}
for(const f of P.furniture){const r=furnitureRect(f),[x,y]=screen(r.x,r.y);ctx.save();ctx.translate(x+r.w*V.scale/2,y+r.h*V.scale/2);ctx.rotate((f.rot||0)*Math.PI/180);ctx.fillStyle=f.id===selected?'#bfdbfe':'#dbeafe';ctx.strokeStyle=f.id===selected?'#2563eb':'#3b82f6';ctx.lineWidth=2;ctx.fillRect(-r.w*V.scale/2,-r.h*V.scale/2,r.w*V.scale,r.h*V.scale);ctx.strokeRect(-r.w*V.scale/2,-r.h*V.scale/2,r.w*V.scale,r.h*V.scale);ctx.fillStyle='#1e3a8a';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(f.name,0,4);ctx.restore()}
if(selected){const o=find(selected);if(o?.type!=='furniture'){const r=rect(o);if(r.w&&r.h){const [x,y]=screen(r.x,r.y);ctx.strokeStyle='#2563eb';ctx.lineWidth=2;ctx.strokeRect(x-3,y-3,r.w*V.scale+6,r.h*V.scale+6)}}}ctx.restore()}
function draw3d(){ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='#dbe5ef';ctx.fillRect(0,0,cv.clientWidth,cv.clientHeight);const r=cv.getBoundingClientRect(),s=Math.min((r.width-90)/P.w,(r.height-90)/P.h),ox=(r.width-P.w*s)/2,oy=(r.height-P.h*s)/2+20;const p=(x,y,z=0)=>[ox+(x-y)*s*.72+P.h*s*.36,oy+(x+y)*s*.28-z*s*.45];const poly=(points,fill,stroke='#64748b')=>{ctx.beginPath();points.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.stroke()};poly([p(0,0),p(P.w,0),p(P.w,P.h),p(0,P.h)],'#f8fafc');for(const f of P.furniture){const q=furnitureRect(f),z=700,top=[p(q.x,q.y,z),p(q.x+q.w,q.y,z),p(q.x+q.w,q.y+q.h,z),p(q.x,q.y+q.h,z)];poly([p(q.x,q.y),p(q.x+q.w,q.y),top[1],top[0]],'#93c5fd');poly([p(q.x+q.w,q.y),p(q.x+q.w,q.y+q.h),top[2],top[1]],'#60a5fa');poly(top,'#bfdbfe')}for(const o of P.objects.filter(o=>['wall','partition'].includes(o.type))){const z=o.type==='wall'?3000:2400;ctx.strokeStyle=o.type==='wall'?'#334155':'#94a3b8';ctx.lineWidth=o.type==='wall'?4:2;ctx.beginPath();ctx.moveTo(...p(o.x,o.y,z));ctx.lineTo(...p(o.x2,o.y2,z));ctx.stroke()}ctx.fillStyle='#475569';ctx.font='13px system-ui';ctx.fillText('3D 预览（编辑请返回 2D）',18,25)}
function find(i){return P.furniture.find(x=>x.id===i)||P.objects.find(x=>x.id===i)}
function checks(){const issues=[];for(const f of P.furniture){const r=furnitureRect(f);if(!inSite(r))issues.push({level:'bad',text:`${f.name} 超出场地边界`});for(const o of P.objects){if(['column','blocked'].includes(o.type)&&overlap(r,rect(o)))issues.push({level:'bad',text:`${f.name} 与${typeName[o.type]}重叠`});if(o.type==='corridor'&&overlap(r,rect(o)))issues.push({level:'bad',text:`${f.name} 占用通道`})}for(const g of P.furniture)if(g.id>f.id&&overlap(r,furnitureRect(g)))issues.push({level:'bad',text:`${f.name} 与 ${g.name} 碰撞`})}for(const c of P.objects.filter(o=>o.type==='corridor')){const r=rect(c),clear=Math.min(r.w,r.h),min=P.rules.minor;if(clear<min)issues.push({level:'warn',text:`通道净宽 ${Math.round(clear)} mm，低于设定的 ${min} mm`})}if(!P.objects.some(o=>o.type==='exit'))issues.push({level:'warn',text:'尚未标记安全出口'});return issues}
function renderPanel(){const o=find(selected),ins=$('#inspector');if(!o)ins.textContent='选择一个对象以查看尺寸和位置。';else{const f=o.type==='furniture';ins.innerHTML=`<div class="field"><label>类型</label><b>${f?o.name:typeName[o.type]}</b></div><div class="row"><div class="field"><label>X mm</label><input data-prop="x" type="number" value="${Math.round(o.x)}"></div><div class="field"><label>Y mm</label><input data-prop="y" type="number" value="${Math.round(o.y)}"></div></div>${f?`<div class="row"><div class="field"><label>宽 mm</label><input data-prop="w" type="number" value="${o.w}"></div><div class="field"><label>深 mm</label><input data-prop="h" type="number" value="${o.h}"></div></div><div class="field"><label>旋转角度</label><input data-prop="rot" type="number" value="${o.rot||0}" step="90"></div>`:`${o.x2!=null?`<div class="row"><div class="field"><label>X2 mm</label><input data-prop="x2" type="number" value="${Math.round(o.x2)}"></div><div class="field"><label>Y2 mm</label><input data-prop="y2" type="number" value="${Math.round(o.y2)}"></div></div>`:''}`}<button class="btn" id="deleteSelected">删除对象</button>`;ins.querySelectorAll('[data-prop]').forEach(i=>i.onchange=()=>{snapshot();o[i.dataset.prop]=+i.value;save()});$('#deleteSelected').onclick=()=>{snapshot();P.furniture=P.furniture.filter(x=>x.id!==o.id);P.objects=P.objects.filter(x=>x.id!==o.id);selected=null;save()}}}
const money=n=>'¥'+n.toLocaleString('zh-CN');
function renderStats(){const seats=P.furniture.reduce((n,f)=>n+(f.kind==='bench2'?2:f.kind==='cubicle'?1:f.kind==='desk'?1:f.kind==='meeting'?6:0),0),issues=checks(),sum=P.furniture.reduce((n,f)=>n+f.price,0);$('#stats').innerHTML=`<div class="metric"><span>工位 / 座位</span><b>${seats}</b></div><div class="metric"><span>家具数量</span><b>${P.furniture.length}</b></div><div class="metric"><span>预计家具金额</span><b>${money(sum)}</b></div>`;$('#bom').innerHTML=P.furniture.length?Object.entries(P.furniture.reduce((m,f)=>{m[f.name]=(m[f.name]||0)+1;return m},{})).map(([n,q])=>`<div class="item"><span>${n}</span><b>× ${q}</b></div>`).join(''):'<div class="empty">尚未添加家具</div>';$('#checks').innerHTML=issues.length?issues.map(i=>`<div class="status ${i.level}">${i.text}</div>`).join(''):'<div class="status ok">未发现基础冲突</div>'}
function renderDrafts(){const host=$('#drafts'),drafts=P.drafts||[];if(!drafts.length){host.innerHTML='<div class="empty">填写需求后生成初稿。</div>';return}host.innerHTML=drafts.map(d=>{const gap=Math.max(0,d.meta.requested-d.meta.seats),active=d.id===P.activeDraft;return `<button class="tool ${active?'active':''}" data-draft="${d.id}" ${readOnly?'disabled':''}><b>${d.label}</b><small>${d.purpose}</small><small>工位 ${d.meta.seats}/${d.meta.requested} · 会议 ${d.meta.meetings} 席 · 电话亭 ${d.meta.phones}${gap?` · 缺 ${gap} 席`:''}</small></button>`}).join('');host.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{applyDraft(b.dataset.draft);save()})}
function render(){P.rules.main=+$('#mainClear').value||1200;P.rules.minor=+$('#minorClear').value||900;(view==='2d'?draw2d:draw3d)();renderPanel();renderStats();renderDrafts()}
function pointer(e){const r=cv.getBoundingClientRect();return world(e.clientX-r.left,e.clientY-r.top)}
cv.addEventListener('pointerdown',e=>{const [x,y]=pointer(e);if(e.button===1||e.spaceKey){drag={pan:true,x:e.clientX,y:e.clientY,vx:V.x,vy:V.y};return}if(readOnly)return;if(tool==='select'){const h=hit(x,y);selected=h?.id||null;if(h){snapshot();drag={move:h,ox:x-h.x,oy:y-h.y}}render();return}snapshot();if(['door','window','exit'].includes(tool)){const wall=P.objects.find(o=>o.type==='wall'&&lineHit(o,{x:o.x2,y:o.y2},x,y));if(!wall){history.pop();return}P.objects.push({id:id(),type:tool,x:clamp(x),y:clamp(y),wallId:wall.id});selected=P.objects.at(-1).id;save();return}drag={create:{id:id(),type:tool,x:clamp(x),y:clamp(y),x2:clamp(x),y2:clamp(y)}};P.objects.push(drag.create);selected=drag.create.id;render()});
cv.addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){V.x=drag.vx+e.clientX-drag.x;V.y=drag.vy+e.clientY-drag.y;render();return}const [x,y]=pointer(e);if(drag.create){drag.create.x2=clamp(x);drag.create.y2=clamp(y)}else if(drag.move){const o=drag.move;if(o.type==='furniture'){o.x=clamp(x-drag.ox);o.y=clamp(y-drag.oy)}else if(o.x2!=null){const dx=clamp(x-drag.ox)-o.x,dy=clamp(y-drag.oy)-o.y;o.x+=dx;o.y+=dy;o.x2+=dx;o.y2+=dy}}render()});
addEventListener('pointerup',()=>{if(drag&&!drag.pan)save();drag=null});cv.addEventListener('wheel',e=>{e.preventDefault();const r=cv.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,[wx,wy]=world(mx,my),z=e.deltaY<0?1.12:.89;V.scale=Math.max(.008,Math.min(.18,V.scale*z));V.x=mx-wx*V.scale;V.y=my-wy*V.scale;render()},{passive:false});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#tools').onclick=e=>{const b=e.target.closest('[data-tool]');if(b){tool=b.dataset.tool;setTool()}};$('#catalog').innerHTML=catalog.map(c=>`<button class="tool" data-kind="${c[0]}">${c[1]}<small>${c[2]} × ${c[3]} mm</small></button>`).join('');$('#catalog').onclick=e=>{const b=e.target.closest('[data-kind]');if(b)addFurniture(b.dataset.kind)};$('#fitBtn').onclick=fit;$('#undoBtn').onclick=undo;$('#mainClear').onchange=$('#minorClear').onchange=save;
$('#generateDrafts').onclick=generateDrafts;
$('#newProject').onclick=()=>$('#projectModal').hidden=false;$('#cancelProject').onclick=()=>$('#projectModal').hidden=true;$('#projectForm').onsubmit=e=>{e.preventDefault();snapshot();P=fresh($('#projectName').value,+$('#siteWidth').value,+$('#siteHeight').value);selected=null;$('#projectModal').hidden=true;save();fit()};
$('#exportBtn').onclick=()=>{const a=document.createElement('a'),data=JSON.stringify(P,null,2);a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download=`${P.name||'office-plan'}.json`;a.click()};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(p.version!==1)throw Error();snapshot();P=p;selected=null;save();fit()}catch{alert('不是有效的项目文件')}};r.readAsText(f)};
$('#shareBtn').onclick=async()=>{const raw=new TextEncoder().encode(JSON.stringify(P)),text=btoa(String.fromCharCode(...raw));const u=new URL('studio.html',location.href);u.hash='project='+encodeURIComponent(text);await navigator.clipboard.writeText(u);alert('只读链接已复制。提示：MVP 链接包含完整方案数据，分享后无法撤回。')};
P=load();P.drafts=P.drafts||[];if(location.hash.startsWith('#project=')){try{P=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(decodeURIComponent(location.hash.slice(9))),x=>x.charCodeAt(0))));P.drafts=P.drafts||[];readOnly=true}catch{}}if(readOnly){document.querySelectorAll('#tools button,#catalog button,#newProject,#importBtn,#shareBtn,#generateDrafts').forEach(b=>b.disabled=true);$('#hint').textContent='只读分享模式 · 可查看 2D、3D、统计与校核';document.querySelector('.top span').textContent='只读分享';}$('#projectName').value=P.name;$('#siteWidth').value=P.w;$('#siteHeight').value=P.h;$('#mainClear').value=P.rules.main||1200;$('#minorClear').value=P.rules.minor||900;new ResizeObserver(()=>{resizeCanvas();if(!V.scale)fit();render()}).observe(cv);resizeCanvas();fit();setTool();render();
