// Functional-area customization is explicit, regenerates the whole plan, and preserves one restore snapshot.
const { chromium }=require('playwright');
const { createServer }=require('node:http');
const { readFile }=require('node:fs/promises');
const assert=require('node:assert/strict');
const path=require('node:path');

const files=new Set(['studio.html','sample-furniture.js','studio.js','broker.js','zone-program.js','zone-assist.js']);
const server=createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1);if(!files.has(name)){res.writeHead(404);res.end();return}res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8');res.end(await readFile(path.join(__dirname,name)))});

(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
  try{
    browser=await chromium.launch({channel:process.env.MVP_BROWSER_CHANNEL||'msedge',headless:true});
    const page=await browser.newPage({viewport:{width:1360,height:900}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/studio.html`);
    await page.locator('#useExample').click();await page.locator('[data-simulation="compact"]').click();
    const original=await page.evaluate(()=>({broker:structuredClone(P.broker),drafts:structuredClone(P.drafts),objects:structuredClone(P.objects),furniture:structuredClone(P.furniture),site:structuredClone(P.site)}));
    await page.locator('#zoneProgramOpen').click();
    assert.equal(await page.locator('#zoneProgramModal').isVisible(),true);
    assert.equal(await page.locator('#zoneProgramBeforeMap svg').count(),1,'current functional areas should be drawn before editing');
    assert.equal(await page.locator('#zoneProgramAfterMap svg').count(),0,'an unchanged form should not fabricate a different plan');
    await page.locator('#zoneProgramSave').click();
    assert.equal(await page.locator('#zoneProgramModal').isVisible(),false,'unchanged form should close without regenerating');
    assert.deepEqual(await page.evaluate(()=>P.drafts),original.drafts);
    await page.locator('#zoneProgramOpen').click();
    await page.locator('[data-program-field="people"]').fill('40');
    await page.locator('[data-program-bool="reception"]').check();
    await page.locator('summary').filter({hasText:'Additional rooms and team areas'}).click();
    await page.locator('#zoneProgramAddExtra').click();
    await page.locator('#zoneProgramExtraRows [data-program-extra="kind"]').last().selectOption('focus');
    await page.locator('#zoneProgramExtraRows [data-program-extra="seats"]').last().fill('1');
    await page.locator('#zoneProgramAddWork').click();
    await page.locator('#zoneProgramWorkRows [data-work-area="name"]').last().fill('Research');
    await page.locator('#zoneProgramWorkRows [data-work-area="targetDesks"]').last().fill('4');
    await page.locator('summary').filter({hasText:'Placement and size rules'}).click();
    await page.locator('#zoneProgramReceptionRule').selectOption('must');
    await page.locator('[data-program-size="base-reception"]').selectOption('fixed');
    await page.locator('#zoneProgramAfterMap svg').waitFor({timeout:30000});
    assert.match(await page.locator('#zoneProgramPreviewStatus').textContent(),/Preview only/);
    assert.match(await page.locator('#zoneProgramAfterSummary').textContent(),/Workstations \d+\/40/);
    assert.notEqual(await page.locator('#zoneProgramAfterMap svg').innerHTML(),await page.locator('#zoneProgramBeforeMap svg').innerHTML(),'changed needs should produce a different visible zoning sketch');
    const simulatedDiagram=await page.locator('#zoneProgramAfterMap svg').evaluate(element=>element.outerHTML);
    assert.deepEqual(await page.evaluate(()=>P.broker),original.broker,'form edits must not mutate the client brief before confirmation');
    assert.deepEqual(await page.evaluate(()=>P.objects),original.objects,'form edits must not mutate geometry before confirmation');
    assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem(STORE)).broker),original.broker,'preview must not persist customer needs');
    await page.locator('#zoneProgramSave').click();
    assert.equal(await page.locator('#zoneProgramModal').isVisible(),false,await page.locator('#zoneProgramError').textContent());
    const changed=await page.evaluate(()=>({broker:P.broker,drafts:P.drafts,previous:P.zoneProgramPrevious,stale:P.draftsStale}));
    assert.equal(changed.broker.people,40);assert.equal(changed.broker.reception,true);
    assert.equal(changed.broker.extraSpaces.some(item=>item.kind==='focus'&&item.count===1&&item.seats===1),true);
    assert.equal(changed.broker.workAreas.some(item=>item.name==='Research'&&item.targetDesks===4),true);
    assert.equal(changed.broker.requirements.spaceSizing['base-reception'].mode,'fixed');
    assert.equal(changed.broker.requirements.relations.some(item=>item.from==='Reception'&&item.rule==='entrance'&&item.priority==='must'),true);
    assert.equal(changed.drafts.length,3);assert.notEqual(changed.drafts[0].id,original.drafts[0].id);assert.equal(changed.stale,false);
    assert.equal(await page.evaluate(()=>{const host=document.createElement('div');host.innerHTML=functionalZoneDiagram(P.drafts[0]);return host.firstElementChild.outerHTML}),simulatedDiagram,'confirmed top-ranked plan should match the previewed zoning geometry');
    assert.deepEqual(changed.previous.broker,original.broker);assert.deepEqual(changed.previous.drafts,original.drafts);
    assert.deepEqual(await page.evaluate(()=>P.site),original.site,'site geometry and its confirmation should not be rewritten');
    const shared=await page.evaluate(async()=>{let copied='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{copied=value}}});const oldAlert=window.alert;window.alert=()=>{};try{await shareBrokerReport()}finally{window.alert=oldAlert}const data=atob(decodeURIComponent(new URL(copied).hash.slice(9))),bytes=Uint8Array.from(data,character=>character.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))});
    assert.equal('zoneProgramPrevious' in shared,false,'shared client links should not carry a private restore snapshot');
    await page.reload();assert.equal(await page.locator('#zoneProgramRestore').isVisible(),true,'restore action should survive reload');
    page.once('dialog',dialog=>dialog.accept());await page.locator('#zoneProgramRestore').click();
    assert.deepEqual(await page.evaluate(()=>P.broker),original.broker);
    assert.deepEqual(await page.evaluate(()=>P.drafts),original.drafts);
    assert.deepEqual(await page.evaluate(()=>P.objects),original.objects);
    assert.deepEqual(await page.evaluate(()=>P.furniture),original.furniture);
    assert.equal(await page.evaluate(()=>P.zoneProgramPrevious),null);
    await page.locator('#zoneProgramOpen').click();await page.locator('#zoneProgramModal details').filter({hasText:'Additional rooms and team areas'}).evaluate(element=>element.open=true);
    await page.locator('#zoneProgramAddWork').click();
    await page.locator('#zoneProgramWorkRows [data-work-area="name"]').last().fill('Too large');
    await page.locator('#zoneProgramWorkRows [data-work-area="targetDesks"]').last().fill('300');
    await page.locator('#zoneProgramSave').click();
    assert.match(await page.locator('#zoneProgramError').textContent(),/exceed the total requested workstations/i);
    assert.deepEqual(await page.evaluate(()=>P.broker),original.broker,'invalid work-area target must not alter client needs');
    await page.locator('#zoneProgramCancel').click();
    await page.locator('#zoneProgramOpen').click();await page.locator('#zoneProgramModal details').filter({hasText:'Additional rooms and team areas'}).evaluate(element=>element.open=true);
    await page.locator('#zoneProgramAddExtra').click();await page.locator('#zoneProgramExtraRows [data-program-extra="kind"]').last().selectOption('focus');
    await page.locator('#zoneProgramSave').click();assert.equal(await page.evaluate(()=>P.broker.extraSpaces.some(item=>item.kind==='focus')),true);
    await page.locator('#zoneProgramOpen').click();await page.locator('#zoneProgramModal details').filter({hasText:'Additional rooms and team areas'}).evaluate(element=>element.open=true);
    await page.locator('#zoneProgramExtraRows [data-program-remove="extra"]').last().click();await page.locator('#zoneProgramSave').click();
    assert.equal(await page.evaluate(()=>P.broker.extraSpaces.some(item=>item.kind==='focus')),false,'removing an area must regenerate without retaining that requirement');
    await page.setViewportSize({width:390,height:844});await page.locator('#zoneProgramOpen').click();
    assert.equal(await page.locator('#zoneProgramModal').isVisible(),true,'mobile users must have the same customization entry');
    assert.equal(await page.locator('#zoneProgramBeforeMap svg').isVisible(),true,'functional-zone preview must remain visible on mobile');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true,'customization should not cause horizontal page overflow on mobile');
    await page.locator('#zoneProgramCancel').click();
    assert.deepEqual(errors,[]);
    console.log('PASS custom functional areas: draft-only edit, validation, full regeneration, reload and restore');
    await page.close();
  }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve))}
})().catch(error=>{console.error(error);process.exitCode=1});
